import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'ACL and ACE', back: 'An **ACL** is an ordered list of **access control entries** (ACEs); each ACE is one permit or deny statement.' },
  { id: 'f2', front: 'Four common uses of ACLs', back: 'Interface packet filtering, NAT (which sources to translate), QoS classification, and management access (VTY `access-class`, SNMP, NTP).' },
  { id: 'f3', front: 'When is an inbound ACL processed?', back: 'As packets arrive on the interface, **before** the routing decision.' },
  { id: 'f4', front: 'When is an outbound ACL processed?', back: 'After routing, as packets leave the interface. Packets generated by the router itself are **not** filtered by it.' },
  { id: 'f5', front: 'Maximum IPv4 ACLs on one interface', back: 'Two — one inbound and one outbound (one ACL per interface, per direction, per protocol).' },
  { id: 'f6', front: 'ACL processing order', back: 'Top-down by sequence number; the **first match** decides and processing stops.' },
  { id: 'f7', front: 'Implicit deny', back: 'An invisible `deny any` (`deny ip any any` in extended ACLs) at the end of every ACL. It never shows a counter.' },
  { id: 'f8', front: 'Wildcard bit 0 vs 1', back: '**0** = the packet bit must match the ACE address bit; **1** = ignore that bit.' },
  { id: 'f9', front: 'Wildcard from a subnet mask', back: '255.255.255.255 − subnet mask (e.g. 255.255.255.240 → `0.0.0.15`).' },
  { id: 'f10', front: 'Wildcard for a /26', back: '`0.0.0.63`' },
  { id: 'f11', front: 'Wildcard for a /20', back: '`0.0.15.255`' },
  { id: 'f12', front: 'Wildcard for a /30', back: '`0.0.0.3`' },
  { id: 'f13', front: 'Wildcard for a /22', back: '`0.0.3.255`' },
  { id: 'f14', front: '`host 10.1.1.10` is equivalent to', back: '`10.1.1.10 0.0.0.0` — exactly one address.' },
  { id: 'f15', front: '`any` is equivalent to', back: '`0.0.0.0 255.255.255.255` — every IPv4 address.' },
  { id: 'f16', front: 'Standard numbered ACL ranges', back: '**1–99** and **1300–1999**.' },
  { id: 'f17', front: 'Extended numbered ACL ranges', back: '**100–199** and **2000–2699**.' },
  { id: 'f18', front: 'What can a standard ACL match?', back: 'Only the **source** IPv4 address.' },
  { id: 'f19', front: 'Where to place a standard ACL, and why', back: 'Close to the **destination**: it cannot see the destination, so near the source it would block that source from everything.' },
  { id: 'f20', front: 'Create a named standard ACL', back: '`ip access-list standard NAME` → prompt `R1(config-std-nacl)#`.' },
  { id: 'f21', front: 'Apply an ACL to an interface', back: '`ip access-group {number | name} {in | out}` in interface configuration mode.' },
  { id: 'f22', front: 'Default ACL sequence numbers', back: 'Start at **10** and increment by **10**.' },
  { id: 'f23', front: '`show access-lists`', back: 'Lists every ACL entry with its sequence number and match counters.' },
  { id: 'f24', front: 'Which command shows the ACL applied to an interface in each direction?', back: '`show ip interface [interface]` → “Outgoing access list is …” and “Inbound access list is …”.' },
  { id: 'f25', front: 'Reset ACL match counters', back: '`clear access-list counters [name | number]`' },
  { id: 'f26', front: 'An interface references an ACL that does not exist', back: 'No filtering — all traffic is permitted until the ACL is created.' },
  { id: 'f27', front: '`access-list 10 permit 10.1.1.77 0.0.0.255` is stored as', back: '`10.1.1.0 0.0.0.255` — IOS zeroes the address bits that the wildcard ignores.' },
  { id: 'f28', front: 'ACE matching 172.16.32.0 – 172.16.47.255', back: '`172.16.32.0 0.0.15.255` (a /20).' },
  { id: 'f29', front: 'Delete a numbered ACL completely', back: '`no access-list 10` — then remove any `ip access-group 10` reference.' },
  { id: 'f30', front: 'A second `ip access-group` in the same direction', back: 'Replaces the first — only one ACL per interface per direction.' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'What happens to a packet that does not match any entry in an interface ACL?',
    options: [
      'It is dropped by the implicit deny at the end of the ACL',
      'It is forwarded, because only explicit denies drop traffic',
      'It is sent to the router CPU for inspection',
      'It is checked against the ACL applied in the other direction',
    ],
    answer: 0,
    difficulty: 1,
    explanation:
      'Every ACL ends with an invisible **implicit deny**, so a packet that matches no entry is dropped. There is no default permit, no punt to the CPU and no fallback to the ACL in the other direction.',
  },
  {
    id: 'q2',
    type: 'input',
    stem: 'Which wildcard mask matches exactly the addresses in 192.168.5.0/26?',
    answers: ['0.0.0.63'],
    placeholder: 'x.x.x.x',
    difficulty: 1,
    explanation:
      'A /26 mask is 255.255.255.192, and 255.255.255.255 − 255.255.255.192 = **0.0.0.63** (block size 64 − 1). The ACE `192.168.5.0 0.0.0.63` matches 192.168.5.0 – 192.168.5.63.',
  },
  {
    id: 'q3',
    type: 'single',
    stem: 'Where should a standard ACL normally be placed?',
    options: ['As close to the destination as possible', 'As close to the source as possible', 'On the router’s loopback interface', 'On every interface in both directions'],
    answer: 0,
    difficulty: 1,
    explanation:
      'A standard ACL matches only the **source**, so near the source it would block that source from every destination. Placing it **near the destination** limits its effect to traffic heading there. Extended ACLs are the ones placed near the source.',
  },
  {
    id: 'q4',
    type: 'multi',
    stem: 'Which two numbers identify standard numbered IPv4 ACLs? (Choose two.)',
    options: ['50', '150', '1500', '2100', '199'],
    answers: [0, 2],
    difficulty: 2,
    explanation:
      'Standard ACLs use **1–99** and **1300–1999**, so 50 and 1500 are standard. 150 and 199 fall in the extended range 100–199, and 2100 falls in the extended expanded range 2000–2699.',
  },
  {
    id: 'q5',
    type: 'single',
    stem: 'Which configuration applies ACL BRANCH-IN to packets arriving on G0/0/0?',
    options: [
      '`interface g0/0/0` then `ip access-group BRANCH-IN in`',
      '`interface g0/0/0` then `ip access-group BRANCH-IN out`',
      '`interface g0/0/0` then `access-class BRANCH-IN in`',
      '`ip access-group BRANCH-IN in` in global configuration mode',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'Interface ACLs are applied in **interface configuration mode** with `ip access-group NAME in` for arriving packets. `out` would filter packets leaving the interface, `access-class` is the line (VTY) command, and `ip access-group` is not a global command.',
  },
  {
    id: 'q6',
    type: 'match',
    stem: 'Match each ACL element to its meaning.',
    pairs: [
      { left: 'Wildcard bit 0', right: 'The bit must match' },
      { left: 'Wildcard bit 1', right: 'The bit is ignored' },
      { left: '`host 10.1.1.10`', right: 'One address: wildcard 0.0.0.0' },
      { left: '`any`', right: 'Every address: wildcard 255.255.255.255' },
    ],
    difficulty: 1,
    explanation:
      'Wildcard logic is the inverse of a subnet mask: **0 = match**, **1 = ignore**. `host` is shorthand for an all-zeros wildcard (one address) and `any` is shorthand for 0.0.0.0 with an all-ones wildcard (every address).',
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'ACL 10 contains `10 deny 10.1.1.0, wildcard bits 0.0.0.255` and `20 permit any`. Which source address is permitted?',
    options: ['10.1.2.1', '10.1.1.200', '10.1.1.1', '10.1.1.255'],
    answer: 0,
    difficulty: 2,
    explanation:
      'Entry 10 denies every source whose first three octets are 10.1.1, so 10.1.1.200, 10.1.1.1 and 10.1.1.255 are all denied. **10.1.2.1** differs in the third octet, fails entry 10 and is permitted by entry 20.',
  },
  {
    id: 'q8',
    type: 'categorize',
    stem: 'Classify each match criterion.',
    categories: ['A standard ACL can match it', 'Needs an extended ACL'],
    items: [
      { text: 'Source IPv4 address', category: 0 },
      { text: 'A source subnet such as 10.1.0.0/16', category: 0 },
      { text: 'Any source (`any`)', category: 0 },
      { text: 'Destination IPv4 address', category: 1 },
      { text: 'TCP destination port 80', category: 1 },
      { text: 'Protocol type (ICMP vs TCP)', category: 1 },
    ],
    difficulty: 2,
    explanation:
      'Standard ACLs look at nothing but the **source address** — a host, a subnet or any. Destination addresses, protocols and port numbers require an **extended** ACL.',
  },
];

export const exam: Question[] = [
  {
    id: 'e1',
    type: 'single',
    stem: 'Which statement describes how Cisco IOS processes the entries of an ACL?',
    options: [
      'Entries are checked top-down and the first matching entry determines the action',
      'All entries are checked and the most specific match determines the action',
      'Deny entries are checked before permit entries, regardless of order',
      'Entries are checked bottom-up so that the newest entry wins',
    ],
    answer: 0,
    difficulty: 1,
    explanation:
      'IOS walks the ACL **top-down** in sequence order and stops at the **first match**. It does not look for a longest or most specific match (that is routing-table logic), deny entries get no priority, and new entries are appended at the end rather than checked first.',
  },
  {
    id: 'e2',
    type: 'single',
    stem: 'Refer to the exhibit. BRANCH-FILTER is applied inbound on R1 G0/0/1. A packet with source address 172.16.45.9 arrives on G0/0/1. Which statement is true?',
    exhibit: {
      kind: 'cli',
      text: `R1# show access-lists BRANCH-FILTER
Standard IP access list BRANCH-FILTER
    10 deny   172.16.40.0, wildcard bits 0.0.3.255 (18 matches)
    20 permit 172.16.32.0, wildcard bits 0.0.15.255 (240 matches)
    30 deny   any (6 matches)`,
    },
    options: [
      'It matches entry 20 and is permitted',
      'It matches entry 10 and is denied',
      'It matches entry 30 and is denied',
      'It matches no entry and is dropped by the implicit deny',
    ],
    answer: 0,
    difficulty: 3,
    explanation:
      'Entry 10 covers 172.16.40.0 – 172.16.43.255 (block of 4 in the third octet); 45 is outside it. Entry 20 covers 172.16.32.0 – 172.16.47.255 (block of 16), and 45 is inside, so the packet is **permitted** by entry 20 and its counter becomes 241. Entry 30 and the implicit deny are never reached because processing stops at the first match.',
  },
  {
    id: 'e3',
    type: 'input',
    stem: 'Enter the wildcard mask that matches exactly the addresses of subnet 10.20.64.0/19.',
    answers: ['0.0.31.255'],
    placeholder: 'x.x.x.x',
    difficulty: 2,
    explanation:
      'A /19 mask is 255.255.224.0; 255.255.255.255 − 255.255.224.0 = **0.0.31.255**. The block size in the third octet is 32, and 64 is a multiple of 32, so `10.20.64.0 0.0.31.255` matches 10.20.64.0 – 10.20.95.255.',
  },
  {
    id: 'e4',
    type: 'single',
    stem: 'Which ACE matches source addresses 192.168.10.16 through 192.168.10.23 and nothing else?',
    options: [
      '`permit 192.168.10.16 0.0.0.7`',
      '`permit 192.168.10.16 0.0.0.8`',
      '`permit 192.168.10.16 0.0.0.15`',
      '`permit 192.168.10.16 255.255.255.248`',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'The range holds 8 addresses starting on a multiple of 8, so the wildcard is 8 − 1 = **0.0.0.7**. `0.0.0.8` ignores only one bit and matches just .16 and .24; `0.0.0.15` matches .16 – .31; and `255.255.255.248` is a subnet mask typed as a wildcard — it ignores the first 29 bits and matches any address whose last three bits are 0.',
  },
  {
    id: 'e5',
    type: 'single',
    stem: 'Refer to the exhibit. A standard ACL must stop the Sales LAN from reaching the HR servers while Sales keeps access to Engineering and all other networks. Where should the ACL be applied?',
    exhibit: {
      kind: 'diagram',
      diagram: {
        type: 'topology',
        width: 10,
        height: 5,
        nodes: [
          { id: 's', icon: 'pc', label: 'Sales', sub: '192.168.10.0/24', x: 1, y: 1.3 },
          { id: 'r1', icon: 'router', label: 'R1', x: 3.4, y: 2.5 },
          { id: 'r2', icon: 'router', label: 'R2', x: 6.3, y: 2.5 },
          { id: 'hr', icon: 'server', label: 'HR servers', sub: '192.168.30.0/24', x: 9, y: 1.3 },
          { id: 'eng', icon: 'pc', label: 'Engineering', sub: '192.168.20.0/24', x: 9, y: 3.7 },
        ],
        links: [
          { from: 's', to: 'r1', toLabel: 'G0/0/0' },
          { from: 'r1', to: 'r2', fromLabel: 'G0/0/1', toLabel: 'G0/0/0', label: '10.0.12.0/30' },
          { from: 'r2', to: 'hr', fromLabel: 'G0/0/1' },
          { from: 'r2', to: 'eng', fromLabel: 'G0/0/2' },
        ],
      },
    },
    options: ['R2 G0/0/1, outbound', 'R1 G0/0/0, inbound', 'R2 G0/0/1, inbound', 'R1 G0/0/1, outbound'],
    answer: 0,
    difficulty: 3,
    explanation:
      'A standard ACL matches only the source, so it must sit where **only HR-bound traffic** passes: outbound on R2 G0/0/1. Inbound on R1 G0/0/0 or outbound on R1 G0/0/1 would block Sales from Engineering and everything else behind R2. Inbound on R2 G0/0/1 would only see traffic coming **from** the HR servers, not Sales traffic going to them.',
  },
  {
    id: 'e6',
    type: 'multi',
    stem: 'Which two statements about the implicit deny in an IPv4 ACL are true? (Choose two.)',
    options: [
      'It exists at the end of every ACL, standard and extended',
      'It does not appear in `show access-lists` and has no match counter',
      'It applies only to extended ACLs',
      'It can be removed with the command `no deny any`',
      'It applies only to ACLs applied inbound',
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation:
      'Every ACL — standard or extended, inbound or outbound — ends with an **invisible** deny that shows no line and no counter. It cannot be removed; to override it you add an explicit `permit any` (or `permit ip any any`) as the last entry, and to count what it would drop you add an explicit `deny any log`.',
  },
  {
    id: 'e7',
    type: 'single',
    stem: 'An engineer needs a standard ACL that denies host 10.1.1.10, permits every other host in 10.1.1.0/24 and denies all other sources. Which configuration meets the requirement?',
    options: [
      '`access-list 5 deny host 10.1.1.10`\n`access-list 5 permit 10.1.1.0 0.0.0.255`',
      '`access-list 5 permit 10.1.1.0 0.0.0.255`\n`access-list 5 deny host 10.1.1.10`',
      '`access-list 5 deny host 10.1.1.10`\n`access-list 5 permit any`',
      '`access-list 5 deny 10.1.1.10 0.0.0.255`\n`access-list 5 permit 10.1.1.0 0.0.0.255`',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'The specific host deny must come **first**, then the subnet permit; the implicit deny handles every other source. With the permit first, 10.1.1.10 matches the permit and the deny never fires (newer IOS even refuses to add the shadowed entry). `permit any` would also admit all other networks. `10.1.1.10 0.0.0.255` is stored as 10.1.1.0/24, so it would deny the whole subnet.',
  },
  {
    id: 'e8',
    type: 'single',
    stem: 'Refer to the exhibit. Which statement is true?',
    exhibit: {
      kind: 'cli',
      text: `R1# show ip interface GigabitEthernet0/0/0
GigabitEthernet0/0/0 is up, line protocol is up
  Internet address is 10.1.1.1/24
<output omitted>
  Outgoing access list is not set
  Inbound  access list is 10
<output omitted>`,
    },
    options: [
      'ACL 10 filters packets arriving on G0/0/0 before R1 routes them',
      'ACL 10 filters packets that R1 sends out of G0/0/0',
      'No ACL is active on G0/0/0 because the outgoing access list is not set',
      'ACL 10 filters only packets addressed to 10.1.1.1',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      '“Inbound access list is 10” means `ip access-group 10 in`: ACL 10 checks every packet **arriving** on G0/0/0, before the routing decision. Nothing filters packets leaving G0/0/0, but that does not make the inbound ACL inactive, and an interface ACL checks transit traffic as well as traffic addressed to the router.',
  },
  {
    id: 'e9',
    type: 'order',
    stem: 'R1 routes a packet from G0/0/0 to G0/0/1. G0/0/0 has an inbound ACL and G0/0/1 has an outbound ACL. Put the processing steps in order.',
    items: [
      'The packet arrives on G0/0/0',
      'The inbound ACL on G0/0/0 is evaluated',
      'R1 looks up the destination in its routing table',
      'The outbound ACL on G0/0/1 is evaluated',
      'R1 encapsulates the packet and transmits it out G0/0/1',
    ],
    difficulty: 2,
    explanation:
      'Inbound ACLs are checked as the packet arrives, **before** routing; the routing lookup selects G0/0/1 as the exit; the outbound ACL on G0/0/1 is checked **after** routing and before the packet is encapsulated in a new frame and sent.',
  },
  {
    id: 'e10',
    type: 'match',
    stem: 'Match each prefix length to its wildcard mask.',
    pairs: [
      { left: '/27', right: '`0.0.0.31`' },
      { left: '/22', right: '`0.0.3.255`' },
      { left: '/29', right: '`0.0.0.7`' },
      { left: '/17', right: '`0.0.127.255`' },
      { left: '/12', right: '`0.15.255.255`' },
    ],
    difficulty: 2,
    explanation:
      'Subtract the mask from 255.255.255.255: /27 = 255.255.255.224 → 0.0.0.31; /22 = 255.255.252.0 → 0.0.3.255; /29 = 255.255.255.248 → 0.0.0.7; /17 = 255.255.128.0 → 0.0.127.255; /12 = 255.240.0.0 → 0.15.255.255.',
  },
  {
    id: 'e11',
    type: 'single',
    stem: 'Refer to the exhibit. PROTECT-SERVERS is applied outbound on R2 G0/0/1, which connects to the server LAN. After the counters are cleared, host 10.1.1.55 sends five pings to server 10.3.3.30, and host 10.1.1.10 sends five pings to the same server. No other traffic crosses G0/0/1. What does `show access-lists PROTECT-SERVERS` display now?',
    exhibit: {
      kind: 'cli',
      text: `R2# clear access-list counters PROTECT-SERVERS
R2# show access-lists PROTECT-SERVERS
Standard IP access list PROTECT-SERVERS
    10 permit 10.1.1.10
    20 deny   10.1.1.0, wildcard bits 0.0.0.255
    30 permit any`,
    },
    options: [
      'Entry 10 shows 5 matches, entry 20 shows 5 matches and entry 30 shows no counter',
      'Entry 10 shows 10 matches because the echo replies are counted too',
      'Entries 10, 20 and 30 each show 5 matches, because the replies match `permit any`',
      'Entry 10 shows 5 matches and entry 20 shows no counter, because denied packets are not counted',
    ],
    answer: 0,
    difficulty: 3,
    explanation:
      'Only packets **leaving** G0/0/1 are checked. The five echo requests from 10.1.1.10 match entry 10 and the five from 10.1.1.55 match entry 20 — denied packets are counted too. The server’s echo replies **enter** G0/0/1 and leave through another interface, so this outbound ACL never evaluates them; entry 30 therefore stays without a counter.',
  },
  {
    id: 'e12',
    type: 'multi',
    stem: 'Refer to the exhibit. ACL 20 is applied inbound on a router interface. Which two source addresses are permitted? (Choose two.)',
    exhibit: {
      kind: 'cli',
      text: `R1# show access-lists 20
Standard IP access list 20
    10 deny   192.168.4.0, wildcard bits 0.0.1.255
    20 permit 192.168.0.0, wildcard bits 0.0.7.255`,
    },
    options: ['192.168.5.200', '192.168.3.1', '192.168.6.10', '192.168.8.1', '192.168.4.4'],
    answers: [1, 2],
    difficulty: 3,
    explanation:
      'Entry 10 denies 192.168.4.0 – 192.168.5.255, which catches 192.168.5.200 and 192.168.4.4. Entry 20 permits 192.168.0.0 – 192.168.7.255, so **192.168.3.1** and **192.168.6.10** are permitted. 192.168.8.1 lies outside both ranges and is dropped by the implicit deny.',
  },
  {
    id: 'e13',
    type: 'categorize',
    stem: 'Classify each numbered ACL by type.',
    categories: ['Standard ACL', 'Extended ACL'],
    items: [
      { text: 'ACL 7', category: 0 },
      { text: 'ACL 99', category: 0 },
      { text: 'ACL 1450', category: 0 },
      { text: 'ACL 101', category: 1 },
      { text: 'ACL 199', category: 1 },
      { text: 'ACL 2050', category: 1 },
    ],
    difficulty: 1,
    explanation:
      'Standard ranges are **1–99** and **1300–1999**; extended ranges are **100–199** and **2000–2699**. So 7, 99 and 1450 are standard, while 101, 199 and 2050 are extended.',
  },
  {
    id: 'e14',
    type: 'single',
    stem: 'Interface G0/0/0 already has `ip access-group 10 in`. An engineer enters `ip access-group 20 in` on the same interface. What is the result?',
    options: [
      'ACL 20 replaces ACL 10 for inbound traffic',
      'Both ACLs are evaluated inbound, ACL 10 first',
      'IOS rejects the command until ACL 10 is removed',
      'ACL 20 is applied outbound because the inbound direction is already in use',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'Only **one IPv4 ACL per interface per direction** is allowed, so the new command simply **replaces** the old one. IOS never chains two ACLs in the same direction, does not reject the command, and never changes the direction you typed.',
  },
  {
    id: 'e15',
    type: 'single',
    stem: 'An engineer applies `ip access-group 15 in` to G0/0/1 but forgets to create ACL 15. What happens to traffic entering G0/0/1?',
    options: [
      'All traffic is permitted, because a nonexistent ACL filters nothing',
      'All traffic is denied by the implicit deny',
      'IOS rejects the command because ACL 15 does not exist',
      'Only traffic from directly connected hosts is permitted',
    ],
    answer: 0,
    difficulty: 3,
    explanation:
      'IOS accepts a reference to an ACL that does not exist yet, and until the ACL is created the interface **permits everything**. The implicit deny belongs to an existing ACL with at least one entry, so it does not apply here. This behavior gives a false sense of security — always verify with `show access-lists` and `show ip interface`.',
  },
  {
    id: 'e16',
    type: 'multi',
    stem: 'Which two advantages do named ACLs offer over numbered ACLs built with global `access-list` commands? (Choose two.)',
    options: [
      'A descriptive name documents the ACL’s purpose',
      'Individual entries can be inserted or deleted using sequence numbers',
      'Named ACLs are processed faster than numbered ACLs',
      'Named ACLs do not end with an implicit deny',
      'Named standard ACLs can match destination addresses',
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation:
      'Names such as PROTECT-SERVERS are **self-documenting**, and the ACL sub-mode lets you **insert or delete single entries** by sequence number, while global `access-list` commands can only append. Processing speed, the implicit deny and the match criteria are identical for named and numbered ACLs of the same type.',
  },
  {
    id: 'e17',
    type: 'input',
    stem: 'Enter the interface configuration command that applies the named ACL WEB-ONLY to packets leaving the interface.',
    answers: ['ip access-group WEB-ONLY out'],
    placeholder: 'command',
    difficulty: 2,
    explanation:
      '`ip access-group WEB-ONLY out` filters packets as they exit the interface. `in` would filter arriving packets, and `access-class` is used under VTY lines rather than interfaces.',
  },
  {
    id: 'e18',
    type: 'single',
    stem: 'Which keyword, placed before an IPv4 address in an ACE, is equivalent to that address followed by the wildcard mask 0.0.0.0?',
    options: ['`host`', '`any`', '`eq`', '`log`'],
    answer: 0,
    difficulty: 1,
    explanation:
      '`host 10.1.1.10` means `10.1.1.10 0.0.0.0` — all 32 bits must match. `any` means every address, `eq` is a port operator used in extended ACLs, and `log` generates syslog messages for matches.',
  },
  {
    id: 'e19',
    type: 'single',
    stem: 'Refer to the exhibit. The engineer intended entry 10 to deny the 10.1.1.0/24 subnet. Which source addresses does entry 10 actually deny?',
    exhibit: {
      kind: 'cli',
      text: `R1(config)# access-list 30 deny 10.1.1.0 255.255.255.0
R1(config)# access-list 30 permit any
R1(config)# end
R1# show access-lists 30
Standard IP access list 30
    10 deny   0.0.0.0, wildcard bits 255.255.255.0
    20 permit any`,
    },
    options: [
      'Any address whose last octet is 0, such as 172.16.5.0',
      'Only addresses in 10.1.1.0/24',
      'No addresses, because IOS ignores subnet masks in an ACE',
      'Every address, because the stored address is 0.0.0.0',
    ],
    answer: 0,
    difficulty: 3,
    explanation:
      'The mask was entered where a **wildcard** belongs. Wildcard 255.255.255.0 ignores the first three octets and requires the last octet to equal 0, so IOS stores the address as 0.0.0.0 and the entry denies **any x.x.x.0** address — while hosts such as 10.1.1.25 fall through to `permit any`. The correct entry is `access-list 30 deny 10.1.1.0 0.0.0.255`.',
  },
  {
    id: 'e20',
    type: 'single',
    stem: 'ACL 1 is referenced by `ip nat inside source list 1 interface GigabitEthernet0/0/1 overload`. What happens to a packet from an inside source that ACL 1 denies?',
    options: [
      'It is routed without being translated',
      'It is dropped, because deny always means drop',
      'It is translated to the interface address anyway',
      'It is punted to the CPU and logged',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'When an ACL is used by NAT, permit means “translate this source” and deny means “**do not translate**” — the packet is still routed, just with its original address. Deny means drop only when the ACL filters traffic on an interface.',
  },
  {
    id: 'e21',
    type: 'multi',
    stem: 'Which two statements about outbound interface ACLs are true? (Choose two.)',
    options: [
      'They are evaluated after the routing decision',
      'They do not filter packets generated by the router itself',
      'They are evaluated before the routing table lookup',
      'They filter packets entering the interface',
      'Only one outbound ACL can exist on the entire router',
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation:
      'An outbound ACL checks packets **after** routing has chosen the exit interface, and packets that the router **originates** (pings, routing updates, syslog) bypass its own outbound ACLs. Inbound ACLs are the ones evaluated before routing on arriving packets, and the limit is one ACL per interface per direction, not one per router.',
  },
  {
    id: 'e22',
    type: 'single',
    stem: 'Refer to the exhibit. LAN A (10.1.1.0/24) connects to R1 G0/0/0. The goal was to stop LAN A from reaching one server subnet behind R2. After the change, LAN A users cannot reach anything beyond R1. What is the problem?',
    exhibit: {
      kind: 'cli',
      text: `R1# show access-lists 10
Standard IP access list 10
    10 deny   10.1.1.0, wildcard bits 0.0.0.255 (57 matches)
    20 permit any
R1# show running-config interface GigabitEthernet0/0/0
Building configuration...

Current configuration : 110 bytes
!
interface GigabitEthernet0/0/0
 ip address 10.1.1.1 255.255.255.0
 ip access-group 10 in
 negotiation auto
end`,
    },
    options: [
      'The standard ACL is applied inbound next to the source, so it drops all LAN A traffic regardless of destination',
      'The ACL is missing a final permit statement',
      'The wildcard mask should be 255.255.255.0',
      'The ACL should be applied outbound on G0/0/0 instead',
    ],
    answer: 0,
    difficulty: 3,
    explanation:
      'A standard ACL cannot see destinations, so inbound on LAN A’s own interface it drops **every** LAN A packet (57 matches so far). It should be applied outbound on the interface of the router closest to the server subnet. The ACL already ends with `permit any`, the wildcard 0.0.0.255 is correct, and outbound on G0/0/0 would filter traffic going **to** LAN A instead.',
  },
  {
    id: 'e23',
    type: 'match',
    stem: 'Match each command to what it does.',
    pairs: [
      { left: '`show access-lists`', right: 'Lists entries, sequence numbers and match counters' },
      { left: '`show ip interface G0/0/1`', right: 'Shows which ACL is applied in each direction' },
      { left: '`clear access-list counters`', right: 'Resets the match counters to zero' },
      { left: '`remark`', right: 'Adds a comment line to an ACL' },
    ],
    difficulty: 1,
    explanation:
      '`show access-lists` shows ACL contents and counters, `show ip interface` shows where ACLs are applied (“Inbound/Outgoing access list is …”), `clear access-list counters` restarts the counts for clean testing, and `remark` documents an ACL without affecting matching.',
  },
];
