import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: '10BASE-T', back: '10 Mbps over 2 UTP pairs (Cat3 or better), IEEE 802.3i, 100 m.' },
  { id: 'f2', front: '100BASE-TX (Fast Ethernet)', back: '100 Mbps over 2 UTP pairs (Cat5 or better), IEEE **802.3u**, 100 m.' },
  { id: 'f3', front: '1000BASE-T', back: '1 Gbps over **all 4** UTP pairs (Cat5e or better), IEEE **802.3ab**, 100 m.' },
  { id: 'f4', front: '10GBASE-T', back: '10 Gbps over UTP, IEEE **802.3an**: 100 m on Cat6a, only 55 m on Cat6.' },
  { id: 'f5', front: '1000BASE-SX', back: '1 Gbps at 850 nm over **multimode** fiber, up to about 550 m (802.3z).' },
  { id: 'f6', front: '1000BASE-LX', back: '1 Gbps at 1310 nm: **single-mode** up to 5 km, or multimode up to 550 m (802.3z).' },
  { id: 'f7', front: '10GBASE-SR', back: '10 Gbps at 850 nm over **multimode**: about 300 m on OM3, 400 m on OM4 (802.3ae).' },
  { id: 'f8', front: '10GBASE-LR', back: '10 Gbps at 1310 nm over **single-mode**, up to **10 km** (802.3ae).' },
  { id: 'f9', front: 'BASE in an Ethernet standard name', back: '**Baseband** signaling: the medium carries a single Ethernet signal.' },
  { id: 'f10', front: 'Maximum UTP Ethernet channel length', back: '**100 m** (90 m permanent link plus about 10 m of patch cords).' },
  { id: 'f11', front: 'Rated bandwidth: Cat5e / Cat6 / Cat6a', back: '100 MHz / 250 MHz / 500 MHz.' },
  { id: 'f12', front: 'Connector used by UTP Ethernet', back: '**RJ-45** (8P8C): eight pins.' },
  { id: 'f13', front: 'T568B colors on pins 1 and 2', back: 'White/orange and orange. (T568A: white/green and green.)' },
  { id: 'f14', front: 'Pins used by 10BASE-T and 100BASE-TX', back: 'Pins **1, 2** and **3, 6**.' },
  { id: 'f15', front: 'Transmit pins of PCs, routers and APs (MDI)', back: 'Pins **1 and 2**; they receive on 3 and 6.' },
  { id: 'f16', front: 'Transmit pins of switches and hubs (MDI-X)', back: 'Pins **3 and 6**; they receive on 1 and 2.' },
  { id: 'f17', front: 'Straight-through cable', back: 'Same pinout at both ends; connects **unlike** devices such as PC to switch or router to switch.' },
  { id: 'f18', front: 'Crossover cable', back: 'T568A at one end, T568B at the other (1 to 3, 2 to 6); connects **like** devices: switch-switch, router-router, PC-PC, PC-router.' },
  { id: 'f19', front: 'Auto-MDIX', back: 'The port detects the cable and swaps its transmit and receive pairs automatically (`mdix auto`), so either cable works.' },
  { id: 'f20', front: 'Multimode fiber (MMF)', back: 'Large core (**50 or 62.5 µm**), LED or VCSEL at 850 nm, hundreds of meters, cheaper optics.' },
  { id: 'f21', front: 'Single-mode fiber (SMF)', back: 'Small core (**8–10 µm**), laser at 1310 or 1550 nm, kilometers, more expensive optics.' },
  { id: 'f22', front: 'Cladding diameter of SMF and MMF', back: '**125 µm** for both; only the core differs.' },
  { id: 'f23', front: 'LC vs SC fiber connectors', back: 'LC: small push-latch, used on SFP/SFP+. SC: larger square push-pull, older optics and patch panels.' },
  { id: 'f24', front: 'SFP vs SFP+', back: 'Same hot-pluggable form factor: SFP = **1 Gbps**, SFP+ = **10 Gbps**.' },
  { id: 'f25', front: 'Hub', back: 'Layer 1 repeater: all ports share **one collision domain** and the bandwidth; devices use half duplex.' },
  { id: 'f26', front: 'CSMA/CD', back: 'Carrier sense multiple access with collision detection: listen, send, detect collisions, jam, random backoff; give up after 16 attempts.' },
  { id: 'f27', front: 'Collision domains on a switch', back: 'Each switch port is its own collision domain; full-duplex links have no collisions.' },
  { id: 'f28', front: 'Rollover (console) cable pinout', back: 'Pins reversed end to end: 1-8, 2-7, 3-6, 4-5.' },
  { id: 'f29', front: 'Default console terminal settings', back: '**9600** baud, 8 data bits, no parity, 1 stop bit, no flow control.' },
  { id: 'f30', front: 'Serial DTE vs DCE', back: 'The router serial port is DTE; the CSU/DSU (or DCE cable end) is DCE and supplies the clock (`clock rate`).' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'Auto-MDIX is not available. Which cable connects a PC to a switch port?',
    options: ['Straight-through', 'Crossover', 'Rollover', 'V.35 serial'],
    answer: 0,
    difficulty: 1,
    explanation:
      'A PC transmits on pins 1 and 2 and a switch on 3 and 6, so a **straight-through** cable matches transmitter to receiver. A crossover is for like devices, a rollover is the console cable, and V.35 is a serial WAN connector.',
  },
  {
    id: 'q2',
    type: 'multi',
    stem: 'Which two statements describe single-mode fiber? (Choose two.)',
    options: [
      'It uses a laser light source',
      'It supports longer distances than multimode fiber',
      'It has a 62.5 µm core',
      'It typically uses LED light sources',
      'It is limited to 100 m',
    ],
    answers: [0, 1],
    difficulty: 1,
    explanation:
      'Single-mode fiber uses **lasers** and reaches **kilometers**, far beyond multimode. The 62.5 µm core and LED sources belong to multimode fiber, and the 100 m limit belongs to twisted-pair copper.',
  },
  {
    id: 'q3',
    type: 'input',
    stem: 'How many wire pairs does 1000BASE-T use?',
    answers: ['4', 'four'],
    placeholder: 'pairs',
    difficulty: 1,
    explanation: '1000BASE-T uses **all four pairs**, each carrying data in both directions at once. 10BASE-T and 100BASE-TX use only two pairs (pins 1, 2 and 3, 6).',
  },
  {
    id: 'q4',
    type: 'match',
    stem: 'Match each Ethernet standard to its medium.',
    pairs: [
      { left: '1000BASE-T', right: 'Four-pair UTP, 100 m' },
      { left: '1000BASE-SX', right: 'Multimode fiber at 850 nm' },
      { left: '10GBASE-LR', right: 'Single-mode fiber, up to 10 km' },
      { left: '10GBASE-T', right: 'Cat6a UTP, 100 m' },
    ],
    difficulty: 2,
    explanation:
      'T names are twisted-pair copper (1000BASE-T on Cat5e or better, 10GBASE-T on Cat6a for 100 m). SX is short-wavelength multimode fiber, and LR is long-reach single-mode fiber up to 10 km.',
  },
  {
    id: 'q5',
    type: 'single',
    stem: 'Which statement about a hub is true?',
    options: [
      'All of its ports share one collision domain',
      'Each port is a separate collision domain',
      'It forwards frames based on destination MAC addresses',
      'It allows connected devices to use full duplex',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'A hub is a Layer 1 repeater, so every port is in **one collision domain** and devices must use half duplex with CSMA/CD. Separate collision domains per port and MAC-based forwarding describe a switch.',
  },
  {
    id: 'q6',
    type: 'single',
    stem: 'Which terminal settings are the defaults for a Cisco console connection?',
    options: [
      '9600 baud, 8 data bits, no parity, 1 stop bit',
      '115200 baud, 8 data bits, even parity, 1 stop bit',
      '9600 baud, 7 data bits, odd parity, 2 stop bits',
      '19200 baud, 8 data bits, no parity, 2 stop bits',
    ],
    answer: 0,
    difficulty: 1,
    explanation: 'The Cisco console default is **9600 baud, 8 data bits, no parity, 1 stop bit** (9600 8-N-1) with no flow control. The other combinations are not the defaults.',
  },
  {
    id: 'q7',
    type: 'categorize',
    stem: 'Auto-MDIX is disabled. Classify each connection by the cable it needs.',
    categories: ['Straight-through', 'Crossover'],
    items: [
      { text: 'PC to switch', category: 0 },
      { text: 'Router to switch', category: 0 },
      { text: 'Access point to switch', category: 0 },
      { text: 'Switch to switch', category: 1 },
      { text: 'Router to router', category: 1 },
      { text: 'PC directly to router', category: 1 },
    ],
    difficulty: 2,
    explanation:
      'Host-type devices (PCs, routers, APs) connect to switches with straight-through cables. Like devices, including a PC connected directly to a router, both transmit on pins 1 and 2 or both on 3 and 6, so they need a crossover.',
  },
];
