import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'CDP', back: 'Cisco Discovery Protocol: Cisco-proprietary Layer 2 protocol that advertises device information to directly connected neighbors.' },
  { id: 'f2', front: 'LLDP', back: 'Link Layer Discovery Protocol: the vendor-neutral **IEEE 802.1AB** Layer 2 discovery protocol.' },
  { id: 'f3', front: 'CDP default state on Cisco IOS', back: '**Enabled** globally and on all supported interfaces.' },
  { id: 'f4', front: 'LLDP default state on Cisco IOS', back: '**Disabled**; enable it globally with `lldp run`.' },
  { id: 'f5', front: 'CDP default timer / holdtime', back: '**60 s** / **180 s**' },
  { id: 'f6', front: 'LLDP default timer / holdtime', back: '**30 s** / **120 s**' },
  { id: 'f7', front: 'Turn CDP on or off for the whole device', back: '`cdp run` / `no cdp run` (global configuration).' },
  { id: 'f8', front: 'Turn CDP off on one interface', back: '`no cdp enable` (interface configuration).' },
  { id: 'f9', front: 'Stop sending LLDP on one interface', back: '`no lldp transmit`. The port can still receive LLDP.' },
  { id: 'f10', front: 'Stop processing LLDP on one interface', back: '`no lldp receive`. The port can still transmit LLDP.' },
  { id: 'f11', front: 'Change the CDP timers', back: '`cdp timer <seconds>` and `cdp holdtime <seconds>` (global).' },
  { id: 'f12', front: 'Change the LLDP timers', back: '`lldp timer <seconds>` and `lldp holdtime <seconds>` (global).' },
  { id: 'f13', front: 'CDP column *Local Intrfce*', back: 'The interface on the device where you ran the command.' },
  { id: 'f14', front: 'CDP column *Port ID*', back: "The **neighbor's** interface at the other end of the link." },
  { id: 'f15', front: 'CDP column *Holdtme*', back: 'Seconds left before the entry is removed if no new advertisement arrives; each advertisement resets it.' },
  { id: 'f16', front: 'Commands that show a neighbor IP address and software version', back: '`show cdp neighbors detail` or `show cdp entry *` (LLDP: `show lldp neighbors detail`).' },
  { id: 'f17', front: 'CDP capability codes R, S, H, P, I', back: 'Router, Switch, Host, Phone, IGMP.' },
  { id: 'f18', front: 'LLDP capability code B', back: '**Bridge**: a Layer 2 switch.' },
  { id: 'f19', front: 'LLDP capability code S', back: '**Station**: an end host, not a switch.' },
  { id: 'f20', front: 'LLDP capability codes R, T, W', back: 'Router, Telephone, WLAN access point.' },
  { id: 'f21', front: 'CDPv2 extras', back: 'Advertises native VLAN, duplex and VTP domain, so IOS can log native VLAN and duplex mismatches.' },
  { id: 'f22', front: '`show cdp interface`', back: 'Per-interface CDP status with encapsulation, advertisement interval and holdtime.' },
  { id: 'f23', front: '`show cdp`', back: 'Global CDP settings: timer, holdtime and whether CDPv2 advertisements are enabled.' },
  { id: 'f24', front: 'Why disable CDP and LLDP on edge ports?', back: 'They reveal hostname, model, software version, IP addresses and VLANs to anyone connected.' },
  { id: 'f25', front: 'Do CDP and LLDP need IP addresses?', back: 'No. Both run directly over Layer 2, so they work even when IP is misconfigured.' },
  { id: 'f26', front: 'Does CDP show devices two hops away?', back: 'No. Only directly connected neighbors; Cisco devices do not forward CDP frames.' },
  { id: 'f27', front: 'LLDP *System* vs *Enabled* Capabilities', back: 'System = what the device can do; Enabled = what it is doing now (for example B,R vs R).' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'Which discovery protocol is enabled by default on Cisco IOS routers and switches?',
    options: ['CDP', 'LLDP', 'Both CDP and LLDP', 'Neither'],
    answer: 0,
    difficulty: 1,
    explanation: '**CDP** runs by default. LLDP is disabled by default on Cisco IOS and must be enabled with `lldp run`.',
  },
  {
    id: 'q2',
    type: 'input',
    stem: 'What is the default LLDP advertisement interval, in seconds?',
    answers: ['30'],
    placeholder: 'seconds',
    difficulty: 1,
    explanation: 'LLDP advertises every **30 seconds** with a 120-second holdtime. CDP uses 60 and 180 seconds.',
  },
  {
    id: 'q3',
    type: 'multi',
    stem: 'Which two items appear in the output of `show cdp neighbors` without the detail keyword? (Choose two.)',
    options: [
      "The neighbor's port ID",
      'The local interface',
      "The neighbor's IP address",
      "The neighbor's software version",
      "The neighbor's MAC address table",
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation:
      "The summary shows Device ID, **Local Intrfce**, holdtime, capability, platform and **Port ID**. IP addresses and software versions need `show cdp neighbors detail` or `show cdp entry *`, and CDP never shares MAC address tables.",
  },
  {
    id: 'q4',
    type: 'single',
    stem: 'On SW1, the CDP entry for R1 shows Local Intrfce `Gig 1/0/24` and Port ID `Gig 0/0/0`. What does `Gig 0/0/0` identify?',
    options: [
      'The interface on R1 that connects to SW1',
      'The interface on SW1 that connects to R1',
      'The interface R1 uses to reach the Internet',
      'The CDP management interface of SW1',
    ],
    answer: 0,
    difficulty: 2,
    explanation: 'Port ID is always the **neighbor\'s** interface, so R1 uses Gi0/0/0 on this link. Local Intrfce (Gi1/0/24) is SW1\'s port.',
  },
  {
    id: 'q5',
    type: 'match',
    stem: 'Match each command to its effect.',
    pairs: [
      { left: '`cdp run`', right: 'Enables CDP on the whole device' },
      { left: '`no cdp enable`', right: 'Disables CDP on one interface' },
      { left: '`lldp run`', right: 'Enables LLDP on the whole device' },
      { left: '`no lldp transmit`', right: 'Stops sending LLDP on one interface' },
      { left: '`lldp holdtime 90`', right: 'Tells neighbors to keep the information for 90 seconds' },
    ],
    difficulty: 2,
    explanation:
      '`cdp run` and `lldp run` are global switches, `no cdp enable` and `no lldp transmit` act on one interface, and `lldp holdtime` sets the holdtime value advertised to neighbors.',
  },
  {
    id: 'q6',
    type: 'single',
    stem: 'In `show lldp neighbors` output, what does the capability code **B** mean?',
    options: ['Bridge (a switch)', 'Broadband router', 'Backup device', 'Base station (access point)'],
    answer: 0,
    difficulty: 2,
    explanation: 'LLDP uses the IEEE term **Bridge** for a switch. Routers are R, access points are W, and S means station (an end host).',
  },
  {
    id: 'q7',
    type: 'categorize',
    stem: 'Classify each fact as describing CDP or LLDP.',
    categories: ['CDP', 'LLDP'],
    items: [
      { text: 'Cisco proprietary', category: 0 },
      { text: 'Default timer of 60 seconds', category: 0 },
      { text: 'Default holdtime of 180 seconds', category: 0 },
      { text: 'Defined in IEEE 802.1AB', category: 1 },
      { text: 'Disabled by default on Cisco IOS', category: 1 },
      { text: 'Default timer of 30 seconds', category: 1 },
      { text: 'Default holdtime of 120 seconds', category: 1 },
    ],
    difficulty: 2,
    explanation: 'CDP: Cisco proprietary, on by default, 60/180 seconds. LLDP: IEEE 802.1AB, off by default on IOS, 30/120 seconds.',
  },
];
