import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'Purpose of a First Hop Redundancy Protocol', back: 'A redundant default gateway: routers share a virtual IP and virtual MAC, so a router failure is invisible to hosts.' },
  { id: 'f2', front: 'What do hosts use as their default gateway with an FHRP?', back: 'The **virtual IP address** (e.g. 10.1.1.254), never a physical router\'s real address.' },
  { id: 'f3', front: 'HSRP roles', back: '**Active** (forwards for the virtual IP/MAC) and **Standby** (takes over); other routers listen.' },
  { id: 'f4', front: 'HSRP priority: range and default', back: '0–255, default **100**. The highest priority becomes active.' },
  { id: 'f5', front: 'HSRP tie-breaker when priorities are equal', back: 'The highest interface IP address.' },
  { id: 'f6', front: 'HSRP preemption default', back: '**Disabled.** Enable it with `standby <group> preempt`.' },
  { id: 'f7', front: 'HSRP hello and hold timers', back: 'Hello **3 s**, hold **10 s**.' },
  { id: 'f8', front: 'HSRPv1 virtual MAC format', back: '**0000.0c07.acXX** — XX = group number in hex (group 1 → 0000.0c07.ac01).' },
  { id: 'f9', front: 'HSRPv2 virtual MAC format', back: '**0000.0c9f.fXXX** — XXX = group number in hex (group 1 → 0000.0c9f.f001).' },
  { id: 'f10', front: 'HSRPv1 and HSRPv2 multicast addresses', back: 'v1: **224.0.0.2** · v2: **224.0.0.102** (both over UDP 1985).' },
  { id: 'f11', front: 'HSRP group number ranges', back: 'v1: 0–255 · v2: 0–4095.' },
  { id: 'f12', front: 'Command that enables HSRP version 2', back: '`standby version 2` (interface mode). Version 2 is required for IPv6 gateways.' },
  { id: 'f13', front: 'HSRP states in order', back: 'Initial → Learn → Listen → Speak → Standby → Active.' },
  { id: 'f14', front: 'HSRP configuration: virtual IP, priority, preempt', back: '`standby 1 ip 10.1.1.254` · `standby 1 priority 110` · `standby 1 preempt`' },
  { id: 'f15', front: 'HSRP message a higher-priority router sends to take over with preempt', back: 'A **coup** message.' },
  { id: 'f16', front: 'VRRP standard', back: 'Open IETF standard: VRRPv2 RFC 3768, VRRPv3 (adds IPv6) RFC 5798.' },
  { id: 'f17', front: 'VRRP roles', back: '**Master** (forwards) and **Backup**.' },
  { id: 'f18', front: 'VRRP default priority and preemption', back: 'Priority **100**; preemption **enabled** by default.' },
  { id: 'f19', front: 'VRRP virtual MAC format', back: '**0000.5e00.01XX** — XX = VRID in hex (VRID 1 → 0000.5e00.0101).' },
  { id: 'f20', front: 'VRRP multicast address and advertisement interval', back: '**224.0.0.18** (IP protocol 112); the master advertises every **1 s**.' },
  { id: 'f21', front: 'Can the VRRP virtual IP be a router\'s real interface IP?', back: 'Yes — that router is the **IP address owner**, uses priority 255 and is master while it is up.' },
  { id: 'f22', front: 'VRRP configuration: virtual IP', back: '`vrrp 1 ip 10.1.1.254` (interface mode) on every router in the group.' },
  { id: 'f23', front: 'GLBP key advantage', back: 'Load balancing: several routers forward traffic at once for a single virtual IP.' },
  { id: 'f24', front: 'GLBP AVG', back: 'Active Virtual Gateway: answers ARP for the virtual IP and hands out different virtual MACs.' },
  { id: 'f25', front: 'GLBP AVF', back: 'Active Virtual Forwarder: forwards frames sent to its own virtual MAC. Up to **4** per group.' },
  { id: 'f26', front: 'GLBP virtual MAC example', back: '**0007.b400.0101** (group 1, forwarder 1) and 0007.b400.0102 (forwarder 2).' },
  { id: 'f27', front: 'GLBP default load-balancing method', back: '**Round-robin** (alternatives: weighted, host-dependent).' },
  { id: 'f28', front: '`show standby brief`: meaning of "local" and "P"', back: '"local" = this router holds that role; "P" = this router is configured to preempt.' },
  { id: 'f29', front: '`show vrrp brief`: key columns', back: 'Grp, Pri, Time (master-down ms), Own, Pre, State (Master/Backup), Master addr, Group addr (virtual IP).', tags: ['v2.0'] },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'What is the default HSRP priority?',
    options: ['0', '1', '100', '255'],
    answer: 2,
    difficulty: 1,
    explanation: 'HSRP routers default to priority **100**; the highest priority becomes active. VRRP and GLBP also default to 100.',
  },
  {
    id: 'q2',
    type: 'multi',
    stem: 'Which two statements about HSRP are true? (Choose two.)',
    options: [
      'Preemption is disabled by default',
      'The default hello and hold timers are 3 and 10 seconds',
      'It is an IETF open standard',
      'The standby router forwards half of the traffic',
      'Its virtual MAC address begins with 0000.5e00',
    ],
    answers: [0, 1],
    difficulty: 1,
    explanation:
      'HSRP has preemption **off** by default and uses **3-second hellos with a 10-second hold time**. It is Cisco proprietary (VRRP is the open standard), the standby router does not forward traffic, and 0000.5e00 is VRRP\'s MAC prefix.',
  },
  {
    id: 'q3',
    type: 'input',
    stem: 'Enter the HSRP version 1 virtual MAC address for group 10.',
    answers: ['0000.0c07.ac0a', '00:00:0c:07:ac:0a', '00-00-0c-07-ac-0a'],
    placeholder: 'xxxx.xxxx.xxxx',
    difficulty: 2,
    explanation: 'HSRPv1 uses 0000.0c07.acXX with the group in hex: 10 decimal = 0x0a, giving **0000.0c07.ac0a** — not ac10.',
  },
  {
    id: 'q4',
    type: 'match',
    stem: 'Match each protocol to its virtual MAC address format.',
    pairs: [
      { left: 'HSRPv1', right: '0000.0c07.acXX' },
      { left: 'HSRPv2', right: '0000.0c9f.fXXX' },
      { left: 'VRRP', right: '0000.5e00.01XX' },
      { left: 'GLBP', right: '0007.b400.XXYY' },
    ],
    difficulty: 2,
    explanation:
      'Cisco\'s HSRP uses the 0000.0c OUI with ac (v1) or 9f.f (v2); VRRP uses the IANA prefix 0000.5e00.01; GLBP uses 0007.b400 followed by the group and forwarder numbers.',
  },
  {
    id: 'q5',
    type: 'single',
    stem: 'Which first hop redundancy protocol is an open standard?',
    options: ['HSRP', 'VRRP', 'GLBP', 'All three'],
    answer: 1,
    difficulty: 1,
    explanation: '**VRRP** is defined by the IETF (RFC 3768 and RFC 5798). HSRP and GLBP are Cisco proprietary.',
  },
  {
    id: 'q6',
    type: 'single',
    stem: 'In GLBP, which role answers ARP requests for the virtual IP address?',
    options: ['AVG', 'AVF', 'Master', 'Standby'],
    answer: 0,
    difficulty: 1,
    explanation:
      'The **Active Virtual Gateway** answers ARP and hands out virtual MACs; the AVFs forward the traffic. Master is a VRRP role and standby an HSRP role.',
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'R1 (HSRP priority 110) is active and R2 (priority 100) is standby. R1 reloads, R2 becomes active, and R1 comes back online. Neither router has `standby preempt` configured. Which router is active now?',
    options: ['R1', 'R2', 'Both routers', 'Neither, until an administrator intervenes'],
    answer: 1,
    difficulty: 2,
    explanation:
      'Without preemption, the current active router keeps the role, so **R2** stays active and R1 becomes standby despite its higher priority. `standby 1 preempt` on R1 would let it take over again.',
  },
];
