import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'Global unicast range', back: '`2000::/3`: first hextet 2000 to 3FFF. Publicly routable.' },
  { id: 'f2', front: 'Unique local range', back: '`FC00::/7`; in practice `FD00::/8` (L bit = 1). Private, never routed on the Internet.' },
  { id: 'f3', front: 'Link-local range', back: '`FE80::/10` (used as FE80::/64). Automatic on every IPv6 interface; never forwarded by routers.' },
  { id: 'f4', front: 'Multicast range', back: '`FF00::/8`. The fourth hex digit is the scope: FF02 = link-local, FF05 = site-local.' },
  { id: 'f5', front: '`FF02::1`', back: 'All-nodes multicast: the closest thing IPv6 has to a broadcast.' },
  { id: 'f6', front: '`FF02::2`', back: 'All-routers multicast. Hosts send Router Solicitations here.' },
  { id: 'f7', front: '`FF02::5` / `FF02::6`', back: 'OSPFv3 all SPF routers / OSPFv3 DR and BDR.' },
  { id: 'f8', front: '`FF02::A`', back: 'EIGRP for IPv6 routers (IPv4 equivalent: 224.0.0.10).' },
  { id: 'f9', front: '`FF02::1:2`', back: 'All DHCPv6 servers and relay agents on the link.' },
  { id: 'f10', front: 'Solicited-node multicast format', back: '`FF02::1:FF` + the last 24 bits (six hex digits) of the unicast or anycast address.' },
  { id: 'f11', front: 'Solicited-node group of 2001:DB8::AB12:3456', back: '`FF02::1:FF12:3456`' },
  { id: 'f12', front: 'Ethernet MAC for an IPv6 multicast group', back: '33:33 + the last 32 bits of the group. Example: FF02::1 maps to 3333.0000.0001.' },
  { id: 'f13', front: 'Anycast address', back: 'A unicast address configured on several devices; each packet reaches the nearest one. No reserved range.' },
  { id: 'f14', front: '`::1`', back: 'IPv6 loopback address (like 127.0.0.1).' },
  { id: 'f15', front: '`::`', back: 'Unspecified address: no address yet. Source of DAD neighbor solicitations.' },
  { id: 'f16', front: 'Broadcast in IPv6', back: '**Does not exist.** Multicast (FF02::1 and solicited-node groups) replaces it.' },
  { id: 'f17', front: 'Modified EUI-64 steps', back: 'Split the MAC, insert `FFFE` in the middle, flip the 7th bit (U/L bit) of the first byte.' },
  { id: 'f18', front: 'EUI-64 interface ID of MAC 001A.2B3C.4D5E', back: '021A:2BFF:FE3C:4D5E, written 21A:2BFF:FE3C:4D5E.' },
  { id: 'f19', front: 'EUI-64: the MAC starts with byte 0C. What is the first byte of the interface ID?', back: '0E (C = 1100 becomes 1110 = E after flipping the 7th bit).' },
  { id: 'f20', front: 'Which hex digit changes in EUI-64?', back: 'Only the second hex digit: swap 0/2, 1/3, 4/6, 5/7, 8/A, 9/B, C/E, D/F.' },
  { id: 'f21', front: 'IOS command for an EUI-64 global address', back: '`ipv6 address 2001:DB8:ACAD:1::/64 eui-64`' },
  { id: 'f22', front: 'RS / RA ICMPv6 types', back: 'Router Solicitation **133** / Router Advertisement **134**.' },
  { id: 'f23', front: 'NS / NA ICMPv6 types', back: 'Neighbor Solicitation **135** / Neighbor Advertisement **136**. Together they replace ARP.' },
  { id: 'f24', front: 'DAD', back: 'Duplicate Address Detection: an NS for the tentative address, sent from `::`. Any NA reply means the address is a duplicate.' },
  { id: 'f25', front: 'RA M flag = 1', back: 'Stateful DHCPv6: hosts get their address (and other information) from a DHCPv6 server.' },
  { id: 'f26', front: 'RA O flag = 1 with M = 0', back: 'Stateless DHCPv6: address by SLAAC; DNS and other information from DHCPv6.' },
  { id: 'f27', front: 'Where IPv6 hosts learn the default gateway', back: 'From the source address of the Router Advertisement (router link-local). DHCPv6 has no gateway option.' },
  { id: 'f28', front: 'IOS commands that set the M and O flags', back: '`ipv6 nd managed-config-flag` / `ipv6 nd other-config-flag`' },
  { id: 'f29', front: 'Default IOS RA interval and lifetime', back: 'RAs every **200 s**; router lifetime **1800 s**.' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'Which prefix identifies IPv6 link-local addresses?',
    options: ['FE80::/10', 'FC00::/7', 'FF00::/8', '2000::/3'],
    answer: 0,
    difficulty: 1,
    explanation: 'Link-local addresses use **FE80::/10**. FC00::/7 is unique local, FF00::/8 is multicast and 2000::/3 is global unicast.',
  },
  {
    id: 'q2',
    type: 'input',
    stem: 'What is the solicited-node multicast address for 2001:DB8:1:1::AB:CDEF?',
    answers: ['FF02::1:FFAB:CDEF', 'FF02:0:0:0:0:1:FFAB:CDEF', 'FF02:0000:0000:0000:0000:0001:FFAB:CDEF'],
    placeholder: 'FF02::1:FF..:....',
    difficulty: 2,
    explanation: 'Take the last 24 bits (six hex digits) of the address, **AB:CDEF**, and append them to FF02::1:FF, giving **FF02::1:FFAB:CDEF**.',
  },
  {
    id: 'q3',
    type: 'multi',
    stem: 'Which two statements about IPv6 link-local addresses are true? (Choose two.)',
    options: [
      'They are created automatically on IPv6-enabled interfaces',
      'Routers never forward packets addressed to them onto another link',
      'They must be unique across the whole organization, not just one link',
      'They begin with FD, like unique local addresses',
      'They are assigned by a DHCPv6 server when the interface comes up',
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation:
      'Every IPv6 interface builds a link-local address **automatically**, and its scope is one link, so routers **never forward** it. It only needs to be unique on its own link, FD is the unique local prefix, and no DHCPv6 server is involved.',
  },
  {
    id: 'q4',
    type: 'input',
    stem: 'Using modified EUI-64, what is the interface ID for MAC address 001B.D4A1.9C22? (Answer in hextets.)',
    answers: ['021B:D4FF:FEA1:9C22', '21B:D4FF:FEA1:9C22'],
    placeholder: 'xxxx:xxxx:xxxx:xxxx',
    difficulty: 2,
    explanation:
      'Split into 001BD4 and A19C22, insert FFFE to get 001B:D4FF:FEA1:9C22, then flip the 7th bit of the first byte: 00 becomes **02**. Result: **021B:D4FF:FEA1:9C22** (21B:D4FF:FEA1:9C22).',
  },
  {
    id: 'q5',
    type: 'match',
    stem: 'Match each NDP message to its purpose.',
    pairs: [
      { left: 'Router Solicitation', right: 'A host asks routers to advertise now' },
      { left: 'Router Advertisement', right: 'A router announces the prefix, gateway and M/O flags' },
      { left: 'Neighbor Solicitation', right: 'Asks for the MAC address of an IPv6 address' },
      { left: 'Neighbor Advertisement', right: 'Answers with a MAC address' },
    ],
    difficulty: 2,
    explanation: 'RS and RA handle router discovery; NS and NA handle address resolution (and DAD), replacing ARP.',
  },
  {
    id: 'q6',
    type: 'single',
    stem: 'A router advertisement has the M flag clear and the O flag set. How do hosts obtain their IPv6 address and DNS server?',
    options: [
      'Address by SLAAC; DNS server from a stateless DHCPv6 server',
      'Address and DNS server from a stateful DHCPv6 server',
      'Address from a DHCPv6 server; DNS server from the RA',
      'Address and DNS server must be configured manually',
    ],
    answer: 0,
    difficulty: 2,
    explanation:
      'M=0, O=1 means **stateless DHCPv6**: hosts build their own address with SLAAC and ask DHCPv6 only for other information such as DNS. Stateful DHCPv6 requires M=1, and nothing forces manual configuration.',
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'Which statement about broadcast in IPv6 is true?',
    options: [
      'IPv6 has no broadcast address; multicast replaces it',
      'FF02::1 is the IPv6 broadcast address',
      'IPv6 broadcast is limited to the local link',
      'IPv6 uses broadcasts only for neighbor discovery',
    ],
    answer: 0,
    difficulty: 1,
    explanation:
      'IPv6 defines **no broadcast** at all. FF02::1 is the all-nodes **multicast** group, and neighbor discovery uses solicited-node multicast rather than broadcasts.',
  },
];
