import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'Default OSPF network type on Ethernet', back: '**Broadcast** — DR/BDR elected; hello 10 s, dead 40 s.' },
  { id: 'f2', front: 'Default OSPF network type on serial HDLC/PPP links', back: '**Point-to-point** — no DR/BDR; hello 10 s, dead 40 s.' },
  { id: 'f3', front: 'Command to make an Ethernet link OSPF point-to-point', back: '`ip ospf network point-to-point` in interface mode — on **both** ends.' },
  { id: 'f4', front: 'OSPF interface priority: range and default', back: '0–255, default **1**. Set with `ip ospf priority <value>` on the interface.' },
  { id: 'f5', front: 'OSPF priority 0', back: 'The router can never become DR or BDR on that segment; it is always a DROTHER.' },
  { id: 'f6', front: 'DR/BDR election criteria, in order', back: '1. Highest interface priority\n2. Highest router ID' },
  { id: 'f7', front: 'Is the DR/BDR election preemptive?', back: '**No.** A better router that joins later does not take over; roles change only when the DR/BDR fails or OSPF is reset.' },
  { id: 'f8', front: 'What happens when the DR fails?', back: 'The BDR is promoted to DR immediately, and a new BDR is elected.' },
  { id: 'f9', front: 'Adjacencies among 5 routers on one LAN: without vs with a DR/BDR', back: '10 (full mesh, n(n−1)/2) vs **7** (2n − 3).' },
  { id: 'f10', front: 'Neighbor state between two DROTHERs', back: '**2WAY/DROTHER** — normal; DROTHERs never become fully adjacent with each other.' },
  { id: 'f11', front: 'Neighbor state between a DROTHER and the DR or BDR', back: '**FULL** (shown as FULL/DR or FULL/BDR).' },
  { id: 'f12', front: '`FULL/  -` in `show ip ospf neighbor`', back: 'A full adjacency on a point-to-point network — there is no DR or BDR.' },
  { id: 'f13', front: 'OSPF wait timer', back: 'On a segment with no DR yet, a router waits the wait interval (= dead interval, 40 s by default) before electing.' },
  { id: 'f14', front: 'How to force a new DR election after changing priorities', back: 'Reset OSPF on the segment\'s routers, e.g. `clear ip ospf process` (or fail the current DR/BDR).' },
  { id: 'f15', front: 'Neighbor stuck in INIT', back: 'Hellos from the neighbor arrive, but it does not list our RID — Hellos are getting through in one direction only (e.g. an ACL).' },
  { id: 'f16', front: 'Neighbor stuck in EXSTART or EXCHANGE', back: 'Usually an **MTU mismatch**. Match the MTU (or, as a workaround, `ip ospf mtu-ignore`).' },
  { id: 'f17', front: 'Neighbor never appears in the neighbor table', back: 'Hellos not sent or rejected: passive interface, subnet/mask, area, timers or authentication mismatch, ACL, or interface down.' },
  { id: 'f18', front: 'Parameters that must match for an OSPF adjacency', back: 'Subnet and mask, area ID, hello/dead intervals, authentication, stub area flag, MTU — plus compatible network types.' },
  { id: 'f19', front: 'Parameters that may differ between OSPF neighbors', back: 'Process ID, priority, interface cost, reference bandwidth. (Router IDs must be **different**.)' },
  { id: 'f20', front: 'Log message for a duplicate router ID on a neighbor', back: '`%OSPF-4-DUP_RTRID_NBR` — the adjacency does not form until one RID is changed and OSPF reset.' },
  { id: 'f21', front: 'Broadcast vs point-to-point network type mismatch', back: 'Timers match, so neighbors can reach FULL, but routes are missing because each router describes the link differently.' },
  { id: 'f22', front: 'Commands that change OSPF timers', back: '`ip ospf hello-interval <s>` and `ip ospf dead-interval <s>` (interface mode). Setting only the hello makes dead = 4 × hello.' },
  { id: 'f23', front: 'Every router on a LAN has priority 0', back: 'No DR/BDR is elected, all neighbors stay in 2WAY/DROTHER, and no adjacency forms on that segment.' },
  { id: 'f24', front: 'Command showing an interface\'s role, DR, BDR and adjacency count', back: '`show ip ospf interface <interface>` (State, Designated Router, Neighbor Count / Adjacent neighbor count).' },
  { id: 'f25', front: 'Multicast address DROTHERs use to reach the DR and BDR', back: '`224.0.0.6` (AllDRouters). The DR re-floods to `224.0.0.5` (AllSPFRouters).' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'What is the default OSPF priority of a Cisco router interface?',
    options: ['0', '1', '100', '255'],
    answer: 1,
    difficulty: 1,
    explanation: 'The default priority is **1**, so by default every router ties and the highest router ID decides. 0 means never DR/BDR, and 255 is the maximum.',
  },
  {
    id: 'q2',
    type: 'multi',
    stem: 'Which two statements about the OSPF point-to-point network type are true? (Choose two.)',
    options: [
      'No DR or BDR is elected',
      'Neighbors appear as FULL/  - in `show ip ospf neighbor`',
      'The default hello interval is 30 seconds',
      'It is the default network type on Ethernet',
      'The DR originates a Type 2 LSA for the link',
    ],
    answers: [0, 1],
    difficulty: 1,
    explanation:
      'Point-to-point links elect **no DR/BDR**, so the role field shows a dash. The hello is 10 seconds (30 is NBMA/P2MP), Ethernet defaults to broadcast, and without a DR there is no Type 2 LSA.',
  },
  {
    id: 'q3',
    type: 'single',
    stem: 'Two DROTHERs on the same Ethernet segment normally show each other in which state?',
    options: ['FULL/DROTHER', '2WAY/DROTHER', 'INIT/DROTHER', 'EXSTART/DROTHER'],
    answer: 1,
    difficulty: 1,
    explanation:
      'DROTHERs become fully adjacent only with the DR and BDR, so with each other they stay at **2-WAY** — normal behaviour. FULL/DROTHER is what the DR or BDR shows for a DROTHER, while INIT and EXSTART indicate problems.',
  },
  {
    id: 'q4',
    type: 'input',
    stem: 'Which OSPF priority value prevents a router from ever becoming DR or BDR on a segment?',
    answers: ['0'],
    placeholder: 'value',
    difficulty: 1,
    explanation: 'Priority **0** makes the interface ineligible for the election; it always ends up a DROTHER.',
  },
  {
    id: 'q5',
    type: 'match',
    stem: 'Match each symptom to its most likely cause.',
    pairs: [
      { left: 'Neighbor stuck in EXSTART', right: 'MTU mismatch' },
      { left: 'Neighbor stuck in INIT', right: 'Hellos received in one direction only' },
      { left: 'Neighbor never appears', right: 'Hello/dead timer mismatch' },
      { left: '2WAY/DROTHER between two routers', right: 'Normal: both routers are DROTHERs' },
    ],
    difficulty: 2,
    explanation:
      'The MTU is checked in DBD packets (EXSTART/EXCHANGE), INIT means our RID is missing from the neighbor\'s Hellos, timer mismatches make Hellos be discarded so no neighbor appears, and DROTHER pairs stop at 2-WAY by design.',
  },
  {
    id: 'q6',
    type: 'single',
    stem: 'R1 (priority 1, RID 1.1.1.1) is the DR and R2 (priority 1, RID 2.2.2.2) is the BDR. R3 with priority 255 is then connected to the segment. What is R3\'s role?',
    options: ['DR', 'BDR', 'DROTHER', 'It triggers a new election and becomes DR'],
    answer: 2,
    difficulty: 2,
    explanation:
      'The election is **non-preemptive**: the existing DR and BDR keep their roles, so R3 becomes a DROTHER. It would become BDR only if one of the current roles became free.',
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'Which interface command makes an Ethernet link use the OSPF point-to-point network type?',
    options: ['`ip ospf network point-to-point`', '`ospf network p2p`', '`ip ospf point-to-point`', '`network point-to-point area 0`'],
    answer: 0,
    difficulty: 1,
    explanation: 'The command is `ip ospf network point-to-point`, configured on both ends of the link. The other options are not valid IOS syntax.',
  },
];
