import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'Four traffic characteristics QoS manages', back: '**Bandwidth**, **delay**, **jitter** and **loss**.' },
  { id: 'f2', front: 'Voice: maximum one-way delay', back: '**150 ms** one-way.' },
  { id: 'f3', front: 'Voice: jitter and loss targets', back: 'Jitter **≤ 30 ms**, loss **≤ 1%**.' },
  { id: 'f4', front: 'Jitter', back: 'The **variation** in one-way delay between consecutive packets of the same flow.' },
  { id: 'f5', front: 'Four components of delay', back: 'Serialization, propagation, processing and **queuing** (the part QoS controls).' },
  { id: 'f6', front: 'CoS: size and location', back: '3-bit **PCP** field in the **802.1Q tag** → values 0–7.' },
  { id: 'f7', front: 'DSCP: size and location', back: 'First **6 bits** of the IPv4 ToS / IPv6 Traffic Class byte → values 0–63.' },
  { id: 'f8', front: 'IP Precedence', back: 'First **3 bits** of the ToS byte (0–7). Legacy marking; DSCP CS values stay compatible with it.' },
  { id: 'f9', front: 'EF: DSCP value and use', back: '**46** (binary 101110) — voice media.' },
  { id: 'f10', front: 'AFxy formula', back: 'DSCP = **8x + 2y**; x = class (1–4), y = drop precedence (1–3).' },
  { id: 'f11', front: 'AF41 decimal value and typical use', back: '**34** — interactive video.' },
  { id: 'f12', front: 'AF11 vs AF13: which is dropped first?', back: '**AF13** — a higher drop precedence (y) is discarded first.' },
  { id: 'f13', front: 'Class Selector values', back: 'CSn = **8n**: CS1 8, CS2 16, CS3 24, CS4 32, CS5 40, CS6 48, CS7 56 (CS0 = 0).' },
  { id: 'f14', front: 'Recommended marking for call signaling', back: '**CS3** (DSCP 24), CoS 3.' },
  { id: 'f15', front: 'Typical CoS for voice media', back: '**CoS 5**.' },
  { id: 'f16', front: 'DSCP 0', back: '**DF / CS0** — default forwarding, best effort.' },
  { id: 'f17', front: 'Trust boundary', back: 'Where the network starts trusting markings. Place it **as close to the source as possible** (IP phone or access switch).' },
  { id: 'f18', front: 'NBAR', back: '**Network-Based Application Recognition**: classifies traffic by application signature using deep packet inspection.' },
  { id: 'f19', front: 'MQC building blocks', back: '`class-map` (match), `policy-map` (actions per class), `service-policy` (apply to an interface in a direction).' },
  { id: 'f20', front: 'Tail drop', back: 'Discarding newly arriving packets because the queue is **full**.' },
  { id: 'f21', front: 'CBWFQ', back: '**Class-Based Weighted Fair Queuing**: minimum bandwidth guarantee per class (`bandwidth`), served in weighted round-robin turns.' },
  { id: 'f22', front: 'LLQ', back: 'CBWFQ + a **strict-priority queue** (`priority`) that is always served first and is **policed** during congestion.' },
  { id: 'f23', front: 'TCP global synchronization', back: 'Tail drop makes many TCP flows back off and ramp up **together**, so the link swings between congested and under-used.' },
  { id: 'f24', front: 'RED / WRED', back: 'Randomly drop some packets **before** the queue is full (between min and max thresholds). WRED uses separate thresholds per IPP/DSCP.' },
  { id: 'f25', front: 'Policing', back: 'Excess traffic is **dropped or re-marked**; no buffering, no added delay; inbound or outbound.' },
  { id: 'f26', front: 'Shaping', back: 'Excess traffic is **buffered** and sent later at the set rate; adds delay; **outbound only**.' },
  { id: 'f27', front: 'Bc formula for a shaper', back: '**Bc = CIR × Tc** — e.g. 200 Mbps × 10 ms = 2,000,000 bits.' },
  { id: 'f28', front: 'IntServ vs DiffServ', back: '**IntServ**: per-flow RSVP reservations, poor scalability. **DiffServ**: DSCP marking + per-hop behaviors, scalable.' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'Which DSCP marking is recommended for voice media (RTP) traffic?',
    options: ['AF41 (34)', 'EF (46)', 'CS3 (24)', 'CS6 (48)'],
    answer: 1,
    difficulty: 1,
    explanation:
      "Voice media uses **Expedited Forwarding, DSCP 46**. AF41 is the usual marking for interactive video, CS3 is for call signaling, and CS6 is for routing protocols (network control).",
  },
  {
    id: 'q2',
    type: 'multi',
    stem: 'Which two statements about traffic shaping are true? (Choose two.)',
    options: [
      'It buffers traffic that exceeds the configured rate',
      'It immediately drops all traffic above the configured rate',
      'It is applied to outbound traffic',
      'It never adds delay',
      "It is the provider's usual tool for enforcing a CIR on customer traffic",
    ],
    answers: [0, 2],
    difficulty: 1,
    explanation:
      "A shaper **queues** excess traffic and releases it at the configured rate, and it works **outbound only**. Dropping or re-marking without delay is what a policer does, and policing is the provider's tool for enforcing the CIR. Because shaping buffers packets, it does add delay.",
  },
  {
    id: 'q3',
    type: 'input',
    stem: 'Using AFxy = 8x + 2y, what is the decimal DSCP value of AF32?',
    answers: ['28'],
    placeholder: 'decimal value',
    difficulty: 2,
    explanation: "8 × 3 + 2 × 2 = 24 + 4 = **28**. Do not swap x and y: 8 × 2 + 2 × 3 = 22 would be AF23.",
  },
  {
    id: 'q4',
    type: 'match',
    stem: 'Match each QoS tool to what it does.',
    pairs: [
      { left: 'Classification', right: 'Identifies which class a packet belongs to' },
      { left: 'Marking', right: 'Writes a CoS or DSCP value into a header' },
      { left: 'LLQ', right: 'Serves a strict-priority queue before all others' },
      { left: 'WRED', right: 'Drops some packets early to avoid congestion' },
      { left: 'Shaping', right: 'Buffers traffic to hold it to a configured rate' },
    ],
    difficulty: 1,
    explanation:
      "Classification decides the class, marking records it in the header, LLQ gives priority traffic a queue that is always served first, WRED drops early and randomly as a queue fills, and shaping delays traffic so it never exceeds a rate.",
  },
  {
    id: 'q5',
    type: 'single',
    stem: 'How many bits make up the CoS (PCP) field in an 802.1Q tag?',
    options: ['3', '6', '8', '12'],
    answer: 0,
    difficulty: 1,
    explanation: "CoS is **3 bits** (values 0–7). DSCP is 6 bits, the whole ToS byte is 8 bits, and 12 bits is the VLAN ID field.",
  },
  {
    id: 'q6',
    type: 'categorize',
    stem: 'Categorize each tool as congestion management (queuing) or congestion avoidance.',
    categories: ['Congestion management', 'Congestion avoidance'],
    items: [
      { text: 'CBWFQ', category: 0 },
      { text: 'LLQ', category: 0 },
      { text: 'Round robin', category: 0 },
      { text: 'RED', category: 1 },
      { text: 'WRED', category: 1 },
    ],
    difficulty: 2,
    explanation:
      "Queuing tools (FIFO, round robin, CBWFQ, LLQ) manage congestion by deciding which packet leaves next. RED and WRED avoid congestion by dropping some packets early, before the queue fills.",
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'Which QoS model uses RSVP to reserve bandwidth for each flow end to end?',
    options: ['Best effort', 'IntServ', 'DiffServ', 'LLQ'],
    answer: 1,
    difficulty: 1,
    explanation:
      "**IntServ** signals per-flow reservations with RSVP. DiffServ marks packets and applies per-hop behaviors without signaling, best effort has no QoS, and LLQ is a queuing tool rather than a model.",
  },
  {
    id: 'q8',
    type: 'single',
    stem: 'Where does Cisco recommend placing the QoS trust boundary?',
    options: [
      'As close to the traffic source as possible',
      'At the core layer, where traffic is aggregated',
      'At the Internet edge firewall',
      'On each user PC, which knows its own applications',
    ],
    answer: 0,
    difficulty: 1,
    explanation:
      "Trust markings **as close to the source as possible** — the IP phone or the access switch port — so traffic is correctly marked from the first link. User PCs are not trusted, and the core or Internet edge is too late in the path.",
  },
];
