import type { Slide } from '../../types';

export const slides: Slide[] = [
  {
    kind: 'title',
    title: 'Topology Architectures',
    subtitle: 'Two-tier, three-tier, spine-leaf, SOHO — and on-premises vs cloud',
    notes:
      "Knowing what each device does is only half the story; the other half is **how devices are arranged**. This deck covers the architectures the CCNA expects you to recognize and justify: the hierarchical campus with its **access, distribution and core** layers; the **two-tier (collapsed core)** and **three-tier** variants and when to choose each; the **spine-leaf** fabric used in modern data centers; the physical topologies underneath all of them (**star, extended star, full and partial mesh, hybrid**); the all-in-one **SOHO** network; and the choice between **on-premises and cloud** resources. Exam questions here are usually scenarios — 'a company with five buildings…', 'which link violates the design…' — so focus on the *rules* and the *reasons*. This lesson maps to v1.1 topics 1.2.a, 1.2.b, 1.2.c, 1.2.e and 1.2.f and to Domain 1 of v2.0; WAN architectures (topic 1.2.d) are covered in their own lesson.",
  },
  {
    kind: 'bullets',
    title: 'What a good architecture delivers',
    bullets: [
      '**Scalability** — grow by adding modules, not redesigning',
      '**Resiliency** — no single point of failure for critical paths',
      '**Performance** — enough bandwidth and predictable latency',
      '**Manageability** — consistent, repeatable building blocks',
      '**Security** — clear boundaries where policy is applied',
      '**Cost** — redundancy and capacity only where they pay off',
    ],
    notes:
      "Architecture is a set of trade-offs, and every design in this lesson optimizes a different mix. **Scalability** means you can add a building, a rack or a branch by repeating a known module rather than re-engineering the whole network. **Resiliency** comes from redundant devices and links arranged so that one failure does not isolate users — but every redundant link costs money and adds complexity. **Performance** means enough bandwidth where traffic concentrates and, in data centers, predictable latency between any two servers. **Manageability** improves when every access switch, distribution block or leaf looks the same. **Security** is easier when there are obvious boundaries — the distribution layer, the firewall at the edge — where policy is applied. Keep these goals in mind: when an exam scenario asks which design to choose, the right answer is the one that meets the stated requirement (fewest devices, most redundancy, east-west performance) without over- or under-building.",
  },
  {
    kind: 'bullets',
    title: 'Star and extended star',
    bullets: [
      '**Star**: every device connects to one central device',
      'Simple and cheap; one failed cable affects one device',
      'The center is a **single point of failure**',
      '**Extended star**: several stars joined to a central core',
      'Typical switched LAN and campus layout',
    ],
    diagram: {
      type: 'topology',
      width: 12,
      height: 5,
      nodes: [
        { id: 'core', icon: 'switch', label: 'Core', x: 6, y: 1, tone: 'accent' },
        { id: 's1', icon: 'switch', label: 'SW1', x: 2, y: 2.8 },
        { id: 's2', icon: 'switch', label: 'SW2', x: 6, y: 2.8 },
        { id: 's3', icon: 'switch', label: 'SW3', x: 10, y: 2.8 },
        { id: 'p1', icon: 'pc', x: 1.1, y: 4.3 },
        { id: 'p2', icon: 'pc', x: 2.9, y: 4.3 },
        { id: 'p3', icon: 'pc', x: 5.1, y: 4.3 },
        { id: 'p4', icon: 'pc', x: 6.9, y: 4.3 },
        { id: 'p5', icon: 'pc', x: 9.1, y: 4.3 },
        { id: 'p6', icon: 'pc', x: 10.9, y: 4.3 },
      ],
      links: [
        { from: 'core', to: 's1' },
        { from: 'core', to: 's2' },
        { from: 'core', to: 's3' },
        { from: 's1', to: 'p1' },
        { from: 's1', to: 'p2' },
        { from: 's2', to: 'p3' },
        { from: 's2', to: 'p4' },
        { from: 's3', to: 'p5' },
        { from: 's3', to: 'p6' },
      ],
      groups: [{ label: 'One star', x: 0.3, y: 2.0, w: 3.4, h: 2.9 }],
    },
    notes:
      "A **physical topology** describes how devices are cabled; a **logical topology** describes how data actually flows (for example, which VLAN or broadcast domain a host is in). The most common physical topology in LANs is the **star**: every endpoint cables back to one central switch. Stars are simple to build and troubleshoot, and a single broken cable affects only one device. Their weakness is the center — if the central switch fails, every device on it loses connectivity, making it a **single point of failure**. An **extended star** connects several stars to a central device, which is exactly what a campus looks like: access switches (small stars) uplinked to a distribution or core switch. The extended star inherits the same weakness at its center, which is why real campus designs add a second core or distribution switch and dual uplinks, turning the upper layers into a partial mesh. Older topologies such as bus and ring are mostly historical for LANs and rarely appear on the exam.",
  },
  {
    kind: 'bullets',
    title: 'Full mesh and partial mesh',
    bullets: [
      '**Full mesh**: every node links to every other node',
      'Links needed = ==n(n − 1) / 2== (5 nodes → 10 links)',
      'Maximum redundancy and direct paths — highest cost',
      '**Partial mesh**: only some nodes interconnected',
      'Redundancy where it matters; far fewer links',
      '**Hybrid**: a mix, e.g. star access + partial-mesh core',
    ],
    diagram: {
      type: 'topology',
      width: 12,
      height: 5,
      nodes: [
        { id: 'a', icon: 'router', label: 'A', x: 1.4, y: 1.3 },
        { id: 'b', icon: 'router', label: 'B', x: 4.4, y: 1.3 },
        { id: 'c', icon: 'router', label: 'C', x: 1.4, y: 3.8 },
        { id: 'd', icon: 'router', label: 'D', x: 4.4, y: 3.8 },
        { id: 'e', icon: 'router', label: 'E', x: 7.6, y: 1.3 },
        { id: 'f', icon: 'router', label: 'F', x: 10.6, y: 1.3 },
        { id: 'g', icon: 'router', label: 'G', x: 7.6, y: 3.8 },
        { id: 'h', icon: 'router', label: 'H', x: 10.6, y: 3.8 },
      ],
      links: [
        { from: 'a', to: 'b' },
        { from: 'a', to: 'c' },
        { from: 'a', to: 'd' },
        { from: 'b', to: 'c' },
        { from: 'b', to: 'd' },
        { from: 'c', to: 'd' },
        { from: 'e', to: 'f' },
        { from: 'e', to: 'g' },
        { from: 'e', to: 'h' },
        { from: 'f', to: 'h' },
      ],
      groups: [
        { label: 'Full mesh · 6 links', x: 0.3, y: 0.3, w: 5.2, h: 4.5 },
        { label: 'Partial mesh · 4 links', x: 6.5, y: 0.3, w: 5.2, h: 4.5 },
      ],
    },
    notes:
      "In a **full mesh**, every node has a direct link to every other node. It gives the most redundancy — any single link can fail and every pair can still talk, usually over a direct path — but the number of links grows quickly: ==n(n − 1) / 2==. Four routers need 6 links, five need 10, six need 15, and fifty would need 1,225. Each link also means another interface, another circuit bill and more configuration. A **partial mesh** connects only some nodes: typically the critical sites or devices get redundant links while others get one or two. The right-hand example gives E a direct path to everyone and F a backup path through H. Most real WANs and campus cores are partial meshes; full mesh is reserved for small groups of critical devices, such as a pair or quad of core switches. A **hybrid** topology simply combines several shapes — for example, star-wired access switches feeding a partial-mesh core — which describes nearly every real network. Expect calculation questions using the formula.",
  },
  {
    kind: 'table',
    title: 'Physical topologies compared',
    columns: ['Topology', 'Layout', 'Redundancy', 'Cost', 'Typical use'],
    rows: [
      ['Star', 'All nodes to one central device', 'Low — center is a single point of failure', 'Low', 'A single access switch and its hosts'],
      ['Extended star', 'Stars joined by a central device', 'Low unless uplinks are doubled', 'Medium', 'Campus LANs'],
      ['Full mesh', 'Every node to every node — n(n−1)/2 links', '**Highest**', '**Highest**', 'Small groups of critical core devices or sites'],
      ['Partial mesh', 'Selected nodes interconnected', 'Targeted', 'Medium', 'Most WANs and campus cores'],
      ['Hybrid', 'Combination of the above', 'Varies', 'Varies', 'Almost every real network'],
    ],
    notes:
      "Use this table to reason about trade-offs rather than to memorize labels. More links mean more redundancy and more cost, so the cheapest topology (star) has the weakest resiliency, and the most resilient (full mesh) is the most expensive and complex. Designers therefore spend redundancy selectively: dual uplinks from every access switch, a meshed pair of core switches, redundant WAN links for critical sites only. When the exam asks for 'the most redundant' design, the answer is full mesh; when it asks for 'redundancy at lower cost than full mesh', the answer is partial mesh; when it describes 'all devices connect to one central switch', the answer is star; and when it describes 'several of those stars connected to a central switch', it is extended star. Remember that a **hybrid** is not a separate special technology — it is the honest name for a mix of the other shapes, and it is what most enterprises actually run.",
  },
  {
    kind: 'diagram',
    title: 'The three-tier campus',
    diagram: {
      type: 'topology',
      width: 12,
      height: 6,
      nodes: [
        { id: 'c1', icon: 'l3switch', label: 'CORE1', x: 4.5, y: 0.9, tone: 'accent' },
        { id: 'c2', icon: 'l3switch', label: 'CORE2', x: 7.5, y: 0.9, tone: 'accent' },
        { id: 'd1', icon: 'l3switch', label: 'DSW-A1', x: 1.8, y: 2.9 },
        { id: 'd2', icon: 'l3switch', label: 'DSW-A2', x: 4.2, y: 2.9 },
        { id: 'd3', icon: 'l3switch', label: 'DSW-B1', x: 7.8, y: 2.9 },
        { id: 'd4', icon: 'l3switch', label: 'DSW-B2', x: 10.2, y: 2.9 },
        { id: 'a1', icon: 'switch', label: 'ASW-A1', x: 1.4, y: 5 },
        { id: 'a2', icon: 'switch', label: 'ASW-A2', x: 4.6, y: 5 },
        { id: 'a3', icon: 'switch', label: 'ASW-B1', x: 7.4, y: 5 },
        { id: 'a4', icon: 'switch', label: 'ASW-B2', x: 10.6, y: 5 },
      ],
      links: [
        { from: 'c1', to: 'c2', style: 'thick' },
        { from: 'd1', to: 'c1' },
        { from: 'd1', to: 'c2' },
        { from: 'd2', to: 'c1' },
        { from: 'd2', to: 'c2' },
        { from: 'd3', to: 'c1' },
        { from: 'd3', to: 'c2' },
        { from: 'd4', to: 'c1' },
        { from: 'd4', to: 'c2' },
        { from: 'd1', to: 'd2' },
        { from: 'd3', to: 'd4' },
        { from: 'a1', to: 'd1' },
        { from: 'a1', to: 'd2' },
        { from: 'a2', to: 'd1' },
        { from: 'a2', to: 'd2' },
        { from: 'a3', to: 'd3' },
        { from: 'a3', to: 'd4' },
        { from: 'a4', to: 'd3' },
        { from: 'a4', to: 'd4' },
      ],
      groups: [
        { label: 'Core', x: 0.2, y: 0.2, w: 11.6, h: 1.5 },
        { label: 'Distribution', x: 0.2, y: 2.1, w: 11.6, h: 1.6 },
        { label: 'Access', x: 0.2, y: 4.2, w: 11.6, h: 1.6 },
      ],
    },
    caption: 'Each access switch dual-homes to its distribution pair; each distribution switch connects to both cores.',
    notes:
      "Cisco's **hierarchical campus design** stacks three layers, each with a distinct job. Endpoints plug into the **access** layer. Each access switch has two uplinks, one to each switch of a **distribution** pair; that pair plus its access switches is called a **distribution block**, often one per building. Every distribution switch then connects to both **core** switches, and the two cores connect to each other. The pattern is an extended star made redundant: no single switch or link failure isolates a building. Notice what is *missing*: access switches never connect to each other or directly to the core, and distribution blocks do not connect to each other — traffic between buildings always goes up to the core and back down. That discipline keeps the design modular: adding Building C means adding one more distribution block with two uplinks per distribution switch to the core, without touching Buildings A and B. The next slide defines each layer's responsibilities.",
  },
  {
    kind: 'definitions',
    title: 'Roles of each layer',
    terms: [
      { term: 'Access layer', def: 'Where endpoints connect: PoE, VLAN assignment, port security, 802.1X, QoS marking and trust.' },
      { term: 'Distribution layer', def: 'Aggregates access switches; the Layer 2/Layer 3 boundary — inter-VLAN routing, ACL policy, FHRP, route summarization.' },
      { term: 'Core layer', def: 'High-speed, highly available backbone joining distribution blocks — fast forwarding, fast convergence, minimal policy.' },
      { term: 'Distribution block', def: 'A distribution switch pair and the access switches that uplink to it, often one per building.' },
      { term: 'Dual-homed uplinks', def: 'Each access switch connects to both distribution switches; each distribution switch to both cores.' },
    ],
    notes:
      "Learn one sentence per layer. The **access layer** is the network's edge, so it carries the endpoint-facing features: Power over Ethernet for phones and APs, VLAN membership, port security, 802.1X authentication and QoS classification (the trust boundary). The **distribution layer** aggregates many access switches and is normally where Layer 2 ends and Layer 3 begins: it provides the default gateways (SVIs with a first-hop redundancy protocol such as HSRP), routes between VLANs, applies ACLs and other policy, and summarizes routes toward the core. The **core layer** exists to move traffic between distribution blocks as fast and reliably as possible; because anything slow or complex there affects everyone, the core avoids CPU-intensive policy and focuses on high bandwidth, redundancy and fast convergence. A classic exam question lists a feature — 'port security', 'route summarization', 'high-speed switching between buildings' — and asks for the layer. Policy belongs at distribution, endpoint features at access, speed at the core.",
  },
  {
    kind: 'diagram',
    title: 'Two-tier design: the collapsed core',
    diagram: {
      type: 'topology',
      width: 10,
      height: 5,
      nodes: [
        { id: 'r1', icon: 'router', label: 'WAN1', x: 3.5, y: 0.8 },
        { id: 'r2', icon: 'router', label: 'WAN2', x: 6.5, y: 0.8 },
        { id: 'cd1', icon: 'l3switch', label: 'CD1', sub: 'core + distribution', x: 3.5, y: 2.5, tone: 'accent' },
        { id: 'cd2', icon: 'l3switch', label: 'CD2', sub: 'core + distribution', x: 6.5, y: 2.5, tone: 'accent' },
        { id: 'a1', icon: 'switch', label: 'ASW1', x: 1.5, y: 4.3 },
        { id: 'a2', icon: 'switch', label: 'ASW2', x: 3.8, y: 4.3 },
        { id: 'a3', icon: 'switch', label: 'ASW3', x: 6.2, y: 4.3 },
        { id: 'a4', icon: 'switch', label: 'ASW4', x: 8.5, y: 4.3 },
      ],
      links: [
        { from: 'r1', to: 'cd1' },
        { from: 'r2', to: 'cd2' },
        { from: 'cd1', to: 'cd2', style: 'thick' },
        { from: 'a1', to: 'cd1' },
        { from: 'a1', to: 'cd2' },
        { from: 'a2', to: 'cd1' },
        { from: 'a2', to: 'cd2' },
        { from: 'a3', to: 'cd1' },
        { from: 'a3', to: 'cd2' },
        { from: 'a4', to: 'cd1' },
        { from: 'a4', to: 'cd2' },
      ],
    },
    caption: 'One switch pair performs both core and distribution roles.',
    notes:
      "Many campuses are too small to justify a separate core. In a **two-tier** design, one pair of multilayer switches performs both the distribution and core roles — hence the name **collapsed core**. Access switches still dual-home to the pair, the pair still provides default gateways, inter-VLAN routing and policy, and it also connects to the WAN routers, the data center or server farm, and the Internet edge. You save two or more expensive core switches and a layer of cabling, and troubleshooting is simpler because there are fewer hops. The limit appears as the campus grows. Every new building needs its own uplinks into the collapsed core pair, and if you add a second distribution pair, the two pairs must be interconnected; with three, four or five pairs, interconnecting them all turns into a full mesh with ==n(n − 1) / 2== links. That growth pain is exactly the problem the dedicated core of a three-tier design solves.",
  },
  {
    kind: 'compare',
    title: 'Two-tier vs three-tier',
    left: {
      heading: 'Two-tier (collapsed core)',
      bullets: [
        'Core and distribution combined in one switch pair',
        'Single building or small campus',
        'Fewer devices, lower cost, simpler operations',
        'Growth: every new block must mesh with the pair',
      ],
    },
    right: {
      heading: 'Three-tier',
      tone: 'accent',
      bullets: [
        'Dedicated core joins many distribution blocks',
        'Large or multi-building campus',
        'No full mesh between distribution pairs',
        'Scales cleanly and contains failures; costs more',
      ],
    },
    notes:
      "Choose based on size and growth. A **two-tier** design suits a single building or a small campus with one distribution block: fewer boxes, lower cost and fewer hops. A **three-tier** design suits a large campus with many buildings or distribution blocks, or one expected to grow: each distribution pair connects only to the two core switches, so adding a block adds a fixed number of links instead of meshing with every other block. The core also becomes a clean place to connect shared resources — data center, WAN edge, Internet edge — once, rather than to every distribution pair. The exam usually frames this as a scenario: 'a company occupies one building with 12 access switches' points to two-tier; 'a university campus with eight buildings' points to three-tier. If a question asks which design 'combines the core and distribution layers', the answer is two-tier or collapsed core. There is no fixed rule of thumb on the number of blocks — look for size, number of buildings and growth in the stem.",
  },
  {
    kind: 'diagram',
    title: 'Spine-leaf: the data center fabric',
    diagram: {
      type: 'topology',
      width: 10,
      height: 5.4,
      nodes: [
        { id: 's1', icon: 'l3switch', label: 'Spine1', x: 2.5, y: 1, tone: 'accent' },
        { id: 's2', icon: 'l3switch', label: 'Spine2', x: 5, y: 1, tone: 'accent' },
        { id: 's3', icon: 'l3switch', label: 'Spine3', x: 7.5, y: 1, tone: 'accent' },
        { id: 'l1', icon: 'switch', label: 'Leaf1', x: 1.3, y: 3 },
        { id: 'l2', icon: 'switch', label: 'Leaf2', x: 3.8, y: 3 },
        { id: 'l3', icon: 'switch', label: 'Leaf3', x: 6.2, y: 3 },
        { id: 'l4', icon: 'switch', label: 'Leaf4', sub: 'border leaf', x: 8.7, y: 3 },
        { id: 'v1', icon: 'server', label: 'Servers', x: 1.3, y: 4.6 },
        { id: 'v2', icon: 'server', label: 'Servers', x: 3.8, y: 4.6 },
        { id: 'v3', icon: 'database', label: 'Storage', x: 6.2, y: 4.6 },
        { id: 'wan', icon: 'router', label: 'WAN edge', x: 8.7, y: 4.6 },
      ],
      links: [
        { from: 'l1', to: 's1' },
        { from: 'l1', to: 's2' },
        { from: 'l1', to: 's3' },
        { from: 'l2', to: 's1' },
        { from: 'l2', to: 's2' },
        { from: 'l2', to: 's3' },
        { from: 'l3', to: 's1' },
        { from: 'l3', to: 's2' },
        { from: 'l3', to: 's3' },
        { from: 'l4', to: 's1' },
        { from: 'l4', to: 's2' },
        { from: 'l4', to: 's3' },
        { from: 'l1', to: 'v1' },
        { from: 'l2', to: 'v2' },
        { from: 'l3', to: 'v3' },
        { from: 'l4', to: 'wan' },
      ],
    },
    caption: 'Every leaf connects to every spine: 3 spines × 4 leaves = 12 fabric links.',
    notes:
      "Modern data centers use a **spine-leaf** (Clos) fabric. The **leaf** switches sit at the top of each rack and connect everything that plugs into the fabric: servers, storage, firewalls and load balancers — even the routers that lead out of the data center, which attach to a **border leaf**. The **spine** switches form the backbone, and they have one job: connect leaves together. Every leaf has a link to every spine, so the number of fabric links is simply spines × leaves (here 3 × 4 = 12). Because all links are active and the fabric is usually routed (or runs an overlay such as VXLAN), traffic is spread across all spines with **equal-cost multipath** rather than having STP block redundant links. Cisco ACI and most other modern fabrics use this design. The next slide lists the rules the exam asks about, and you should be able to spot a diagram that breaks them.",
  },
  {
    kind: 'bullets',
    title: 'Spine-leaf design rules',
    bullets: [
      'Every **leaf** connects to **every spine**',
      'No **leaf-to-leaf** links and no **spine-to-spine** links',
      'Endpoints — servers, storage, firewalls, routers — attach **only to leaves**',
      'Any leaf-to-leaf path is leaf → spine → leaf: ==predictable latency==',
      'All spines usable at once (ECMP) — no STP-blocked uplinks',
      'Scale out: add leaves for ports, add spines for bandwidth',
    ],
    notes:
      "Memorize the four structural rules — they come straight from the Cisco certification guide and are tested by 'which link or connection violates the design' questions. **Each leaf connects to every spine. Each spine connects to every leaf. Leaves never connect to each other. Spines never connect to each other.** Add a fifth rule: **endpoints connect only to leaves**, never to spines. The payoff is consistency: traffic between servers on any two different leaves always crosses exactly one spine, so every path has the same number of hops and similar latency, no matter which racks the servers are in. To add server ports, add a leaf and cable it to every spine. To add bandwidth between racks, add a spine and cable it to every leaf. Nothing else has to change. Watch for distractors that sound reasonable — 'connect servers directly to spines for lower latency' or 'link spines together for redundancy' — both violate the design.",
  },
  {
    kind: 'compare',
    title: 'Why data centers moved to spine-leaf',
    left: {
      heading: 'Three-tier data center (legacy)',
      bullets: [
        'Built for **north-south** traffic (users ↔ servers)',
        'STP may block redundant Layer 2 links',
        'Hop count varies with where servers sit',
        'Scale up with bigger, costlier boxes',
      ],
    },
    right: {
      heading: 'Spine-leaf fabric',
      tone: 'accent',
      bullets: [
        'Built for **east-west** traffic (server ↔ server)',
        'All fabric links active with ECMP',
        'Every leaf-to-leaf path crosses one spine',
        'Scale out by adding spines and leaves',
      ],
    },
    notes:
      "Data centers used to copy the campus model: access, aggregation and core layers, optimized for **north-south** traffic — clients outside the data center talking to servers inside it. Virtualization and distributed applications changed the traffic pattern: a single user request can trigger dozens of server-to-server calls to databases, storage and microservices, and virtual machines migrate between hosts. That **east-west** traffic now dominates. In a three-tier data center, two servers in different parts of the room may cross many hops, and Spanning Tree leaves some links idle. Spine-leaf fixes both problems: every server-to-server path across the fabric is the same length, and every link carries traffic. It also scales horizontally with identical, relatively inexpensive switches. On the exam, 'east-west' and 'predictable latency' point to spine-leaf; 'users in buildings' and 'distribution blocks' point to the campus hierarchy.",
  },
  {
    kind: 'bullets',
    title: 'SOHO networks',
    bullets: [
      'Small office / home office: a handful of users',
      'One **all-in-one wireless router** does nearly everything',
      'Router + built-in switch ports + Wi-Fi AP + firewall',
      '**DHCP** server hands out private addresses',
      '**NAT/PAT** lets every device share one public IP',
      'ISP link through a cable/DSL modem or fiber ONT',
    ],
    diagram: {
      type: 'topology',
      width: 10,
      height: 4.5,
      nodes: [
        { id: 'inet', icon: 'internet', label: 'Internet', x: 9, y: 1.1 },
        { id: 'modem', icon: 'modem', label: 'Modem / ONT', x: 6.8, y: 1.1 },
        { id: 'rtr', icon: 'router', label: 'SOHO router', sub: 'all-in-one', x: 4.4, y: 1.1, tone: 'accent' },
        { id: 'pc', icon: 'pc', label: 'PC', x: 1.2, y: 3.4 },
        { id: 'prn', icon: 'printer', label: 'Printer', x: 3.2, y: 3.4 },
        { id: 'lap', icon: 'laptop', label: 'Laptop', x: 5.5, y: 3.4 },
        { id: 'tab', icon: 'tablet', label: 'Tablet', x: 7.6, y: 3.4 },
      ],
      links: [
        { from: 'rtr', to: 'modem', label: 'WAN port' },
        { from: 'modem', to: 'inet' },
        { from: 'rtr', to: 'pc', label: 'LAN' },
        { from: 'rtr', to: 'prn' },
        { from: 'rtr', to: 'lap', style: 'wireless' },
        { from: 'rtr', to: 'tab', style: 'wireless' },
      ],
    },
    notes:
      "At the small end of the spectrum, **SOHO** (small office/home office) networks rarely justify separate devices. A single consumer-grade or small-business **wireless router** combines a router (the LAN's default gateway), a small Ethernet switch (typically four LAN ports), a wireless access point, a stateful firewall that blocks unsolicited inbound traffic, a **DHCP server** that gives every device a private address, mask, gateway and DNS server, and **NAT/PAT** that translates all those private addresses to the single public address the ISP assigns to the WAN port. Its WAN port connects to the ISP through a cable modem, DSL modem or fiber ONT — and sometimes the modem is built into the same box. Some SOHO sites also use the Internet to reach headquarters through a VPN. Exam questions typically list functions and ask which ones a SOHO router provides, or ask why every device appears to the Internet with the same address (PAT).",
  },
  {
    kind: 'table',
    title: 'Inside the SOHO router',
    columns: ['Function', 'What it does', 'Exam note'],
    rows: [
      ['Router', 'Default gateway for the LAN; routes to the ISP', 'LAN side uses a private subnet'],
      ['Switch', 'A few built-in Ethernet LAN ports', 'Same subnet as the Wi-Fi clients'],
      ['Wireless AP', 'Provides the SSID for laptops and phones', 'Bridged into the LAN subnet'],
      ['DHCP server', 'Leases IP, mask, gateway and DNS to clients', 'Clients receive private addresses'],
      ['NAT / PAT', 'Maps many private addresses to one public address', 'Port numbers keep sessions apart'],
      ['Firewall', 'Blocks unsolicited inbound traffic', 'Stateful: replies to inside requests allowed'],
    ],
    notes:
      "Take the all-in-one box apart logically and you find the same roles an enterprise spreads across many devices. The **router** function is the default gateway for the LAN and has a default route to the ISP. The built-in **switch** and **AP** usually belong to the same LAN, so wired and wireless devices share one subnet and one broadcast domain. The **DHCP server** means nothing needs manual configuration — plug in or join Wi-Fi and you are online. **PAT** (port address translation, also called NAT overload) is why dozens of devices can share one public IPv4 address: the router tracks each session by translating the source port as well as the address. The **firewall** is stateful: replies to connections started from inside are allowed back in, while connections started from the Internet are dropped unless you create a port-forwarding rule. Later lessons configure these same features, DHCP, NAT and ACLs, on Cisco routers.",
  },
  {
    kind: 'table',
    title: 'On-premises vs cloud as a topology choice',
    columns: ['Model', 'Who owns and runs it', 'How you reach it', 'Trade-offs'],
    rows: [
      ['**On-premises**', 'Your organization, in its own data center or closets', 'Your LAN and WAN', 'Full control; you buy capacity up front and run everything'],
      ['**Public cloud**', 'A provider, on infrastructure shared by many tenants', 'Internet, VPN or a private direct connection', 'Elastic, pay as you go; less control; data leaves your site'],
      ['**Private cloud**', 'Your organization (or a host) — cloud-style self-service for one tenant', 'Your network', 'Automation and control; you still own the capacity'],
      ['**Hybrid cloud**', 'Mix of on-premises/private and public cloud', 'Links between them (VPN or private WAN)', 'Flexibility; more complex networking and security'],
    ],
    notes:
      "Where the servers live is now a topology decision too. **On-premises** means the organization owns the servers and network in its own facilities: maximum control and predictable local latency, but capital expense, long procurement cycles and capacity that must be bought for the peak. **Public cloud** means renting compute, storage and services from a provider whose infrastructure is shared by many customers; you pay for what you use and can scale in minutes, but you depend on the provider and on the network path to it — the Internet, a site-to-site VPN, or a private connection. **Private cloud** brings cloud-style self-service and automation to infrastructure dedicated to one organization, usually on premises. **Hybrid cloud** combines private or on-premises resources with public cloud, for example keeping regulated data at home while web front ends scale in the public cloud. The cloud computing lesson later covers service models and NIST characteristics; here, focus on how the choice changes traffic paths.",
  },
  {
    kind: 'diagram',
    title: 'A hybrid topology in practice',
    diagram: {
      type: 'topology',
      width: 12,
      height: 5,
      nodes: [
        { id: 'srv', icon: 'server', label: 'On-prem servers', x: 1.3, y: 1.1 },
        { id: 'user', icon: 'laptop', label: 'Users', x: 1.3, y: 3.8 },
        { id: 'core', icon: 'l3switch', label: 'Core', x: 3.1, y: 2.4 },
        { id: 'edge', icon: 'router', label: 'Edge', x: 5.2, y: 2.4 },
        { id: 'inet', icon: 'internet', label: 'Internet', x: 7.35, y: 3.6 },
        { id: 'vm', icon: 'vm', label: 'Cloud VMs', x: 10, y: 1.3, tone: 'accent' },
        { id: 'saas', icon: 'cloud', label: 'SaaS apps', x: 10, y: 3.7 },
      ],
      links: [
        { from: 'srv', to: 'core' },
        { from: 'user', to: 'core' },
        { from: 'core', to: 'edge' },
        { from: 'edge', to: 'inet' },
        { from: 'inet', to: 'saas' },
        { from: 'edge', to: 'vm', label: 'VPN or direct connect', style: 'dashed', tone: 'accent' },
      ],
      groups: [
        { label: 'On-premises', x: 0.3, y: 0.3, w: 6.2, h: 4.4 },
        { label: 'Public cloud', x: 8.2, y: 0.3, w: 3.5, h: 4.4 },
      ],
    },
    caption: 'On-premises and public cloud resources joined into one design.',
    notes:
      "Here is what a hybrid design looks like at the topology level. Users and some servers stay **on premises**, connected through the campus core. The edge router (or firewall) now has two very different kinds of external paths. One leads to the **Internet**, which users take to reach SaaS applications such as hosted email or collaboration tools. The other is a dedicated path to the organization's **cloud VMs** — either a site-to-site IPsec VPN across the Internet or a private connection offered by the cloud provider or a colocation exchange — so that on-premises servers and cloud workloads can talk privately, with predictable performance and without exposing internal addresses. Designing a hybrid network raises new questions: which traffic crosses which link, where firewall policy is enforced, how much bandwidth the cloud connection needs, and how IP address ranges are kept from overlapping. When the exam describes 'some workloads on premises and some in a public cloud, connected together', the term it wants is **hybrid cloud**.",
  },
  {
    kind: 'diagram',
    title: 'Choosing an architecture',
    diagram: {
      type: 'flow',
      width: 12,
      height: 5,
      nodes: [
        { id: 'q1', label: 'Data center?', shape: 'diamond', x: 1.6, y: 1.2 },
        { id: 'a1', label: 'Spine-leaf', sub: 'east-west traffic', tone: 'accent', x: 1.6, y: 3.8 },
        { id: 'q2', label: 'Many buildings?', shape: 'diamond', x: 5, y: 1.2 },
        { id: 'a2', label: 'Three-tier', sub: 'dedicated core', x: 5, y: 3.8 },
        { id: 'q3', label: 'Enterprise campus?', shape: 'diamond', x: 8.4, y: 1.2 },
        { id: 'a3', label: 'Two-tier', sub: 'collapsed core', x: 8.4, y: 3.8 },
        { id: 'a4', label: 'SOHO router', sub: 'all-in-one', shape: 'round', x: 11, y: 3.8 },
      ],
      edges: [
        { from: 'q1', to: 'a1', label: 'yes' },
        { from: 'q1', to: 'q2', label: 'no' },
        { from: 'q2', to: 'a2', label: 'yes' },
        { from: 'q2', to: 'q3', label: 'no' },
        { from: 'q3', to: 'a3', label: 'yes' },
        { from: 'q3', to: 'a4', label: 'no' },
      ],
    },
    caption: 'Match the design to the traffic pattern and the size of the site.',
    notes:
      "Use a quick decision path when an exam scenario asks which architecture fits. First, is this a **data center** where servers talk mostly to each other? Then the answer is **spine-leaf**, because it delivers predictable latency for east-west traffic and scales out. If it is a campus, ask whether it spans **many buildings or distribution blocks**, or is expected to grow that way — if so, a **three-tier** design with a dedicated core avoids meshing distribution pairs together. A single building or small campus is well served by a **two-tier collapsed core**. And a home or tiny office with a few users needs neither: an **all-in-one SOHO router** provides routing, switching, Wi-Fi, DHCP, NAT and a firewall. Layered on top of any of these is the on-premises versus cloud decision, which depends on control, cost model, elasticity and data location. Real designs blend these patterns — a campus might be three-tier while its data center is spine-leaf and some workloads run in a public cloud.",
  },
  {
    kind: 'callout',
    tone: 'exam',
    title: 'Exam traps: topology architectures',
    body: 'In spine-leaf, **every leaf connects to every spine**, endpoints attach **only to leaves**, and there are **no leaf-leaf or spine-spine links**.',
    bullets: [
      'Two-tier = collapsed core: core and distribution in one switch pair',
      'Distribution = L2/L3 boundary, policy, FHRP; access = endpoint features',
      'Full mesh links = n(n − 1)/2; spine-leaf links = spines × leaves',
      'East-west = server to server; north-south = in and out of the DC',
      'SOHO router = router + switch + AP + firewall + DHCP + NAT',
      'Hybrid cloud = on-premises/private + public cloud, connected',
    ],
    notes:
      "These are the architecture facts the exam tests most. Spine-leaf questions often show a diagram with one illegal link — a leaf-to-leaf cable, a server plugged into a spine, or spines linked together — and ask you to find it; apply the rules mechanically. 'Collapsed core' always means two-tier, and it is the core and distribution layers that collapse, never access. Feature-to-layer questions reward the simple split: endpoint features at access, policy and routing boundary at distribution, speed and availability at the core. Keep the two formulas straight: a full mesh of n nodes needs n(n − 1)/2 links, while a spine-leaf fabric needs spines × leaves links. East-west traffic stays inside the data center; north-south enters or leaves it. For SOHO, remember the whole list of functions — especially DHCP and NAT/PAT, which people forget. And for cloud, 'hybrid' means combining on-premises or private resources with a public cloud, not 'a mix of topologies' — that is a hybrid *physical* topology.",
  },
  {
    kind: 'bullets',
    title: 'Summary',
    bullets: [
      'Campus hierarchy: **access** (endpoints), **distribution** (policy, L2/L3), **core** (speed)',
      '**Two-tier** collapses core + distribution; **three-tier** adds a dedicated core',
      '**Spine-leaf**: every leaf to every spine, endpoints on leaves, predictable latency',
      'Star → extended star → partial mesh → full mesh: more links, more redundancy, more cost',
      '**SOHO**: one all-in-one wireless router with DHCP, NAT and a firewall',
      'On-premises, public, private and **hybrid** cloud change where traffic flows',
    ],
    notes:
      "Let us recap. The hierarchical campus gives each layer a job: the access layer connects and protects endpoints, the distribution layer aggregates access switches and applies routing and policy at the Layer 2/Layer 3 boundary, and the core moves traffic between distribution blocks as quickly and reliably as possible. Small campuses collapse the core and distribution layers into one pair (two-tier); large, multi-building campuses keep them separate (three-tier) so they scale without meshing every block together. Data centers use spine-leaf fabrics, whose strict wiring rules give every server-to-server path the same length. Underneath every design are physical topologies whose redundancy and cost rise together, from star to full mesh, and most networks are hybrids. At the small end, a SOHO router does everything in one box. Finally, resources can live on premises or in public, private or hybrid clouds, and that choice shapes the WAN and Internet paths between sites, which the separate WAN architectures lesson explores.",
  },
];
