import type { Flashcard, Question } from '../../types';

export const flashcards: Flashcard[] = [
  { id: 'f1', front: 'VLSM', back: '**Variable-Length Subnet Masking**: using different prefix lengths for different segments carved from the same address block, instead of one mask for everything.' },
  { id: 'f2', front: 'Which routing protocols support VLSM?', back: '**Classless** protocols that carry the mask in updates: OSPF, EIGRP, RIPv2, IS-IS, BGP, and static routes. **RIPv1** is classful and cannot.' },
  { id: 'f3', front: 'VLSM allocation order', back: 'Allocate the **largest** subnets first, so every following subnet starts on a valid boundary for its own (smaller) block size.' },
  { id: 'f4', front: 'Rule for a subnet\'s starting address', back: 'It must be a **multiple of its own block size** (2^host-bits) within the parent block.' },
  { id: 'f5', front: 'Traditional point-to-point WAN mask', back: '**/30** — 255.255.255.252, block size 4, 2 usable host addresses.' },
  { id: 'f6', front: 'RFC 3021 point-to-point mask', back: '**/31** — 255.255.255.254, 2 addresses, **both usable** (no network ID or broadcast reserved).' },
  { id: 'f7', front: 'When do two subnets overlap?', back: 'When at least one address belongs to both — equivalently, when one subnet\'s range sits **inside** the other\'s.' },
  { id: 'f8', front: 'Binary shortcut to test if two subnets overlap', back: 'Apply the **shorter** of the two prefixes to both network IDs. Equal results mean the smaller subnet sits inside the larger one.' },
  { id: 'f9', front: 'IOS behavior for an overlapping IP address on the SAME router', back: 'Rejected: `% <subnet> overlaps with <interface>`. IOS checks new interface addresses against every other configured interface.' },
  { id: 'f10', front: 'Does IOS catch overlapping subnets on two DIFFERENT routers?', back: 'No. Each router only checks its own interfaces. The overlap surfaces later as **longest-prefix-match** misrouting.' },
  { id: 'f11', front: 'Route summarization (other names)', back: '**Supernetting** / route aggregation: advertising several contiguous subnets as one shorter-prefix route.' },
  { id: 'f12', front: 'How to find the best (longest) summary of a set of networks', back: 'Compare the networks in **binary**; count the identical **leading bits**; that count is the summary prefix. Zero the remaining bits.' },
  { id: 'f13', front: 'When is a summary of N networks exact?', back: 'When **N is a power of two** and the first network\'s value in the varying octet is a **multiple of N**.' },
  { id: 'f14', front: 'Four contiguous, aligned /24s summarize to', back: 'One **/22** (2 bits shorter than /24, since 2² = 4).' },
  { id: 'f15', front: 'Main benefit of route summarization', back: 'Smaller routing tables and faster, more **stable** convergence — a flapping subnet inside the summary stays hidden from routers beyond it.' },
  { id: 'f16', front: 'Main risk of route summarization', back: 'It can claim address space that is **unused or belongs elsewhere**, attracting traffic that then gets dropped or misrouted.' },
  { id: 'f17', front: 'Configuring a static summary route', back: '`ip route <summary-network> <summary-mask> <next-hop>` — the mask is a **subnet mask** (e.g. 255.255.252.0), never a wildcard mask.' },
  { id: 'f18', front: 'Host counts 100 / 50 / 25 / 12 need prefixes', back: '/25 (126 hosts) / **/26** (62) / **/27** (30) / **/28** (14) — the smallest prefix whose 2^h − 2 still meets the requirement.' },
  { id: 'f19', front: 'Block size of a /27', back: '**32** addresses (2^(32−27)).' },
  { id: 'f20', front: 'Is 192.168.1.32/25 a valid network ID?', back: 'No. A /25 block is 128 addresses, so the only /25 boundaries are **.0 and .128**; .32 falls inside 192.168.1.0/25.' },
  { id: 'f21', front: 'Range covered by 10.1.4.0/22', back: '**10.1.4.0 – 10.1.7.255** (block size 4 in the third octet).' },
  { id: 'f22', front: 'IOS routing-table heading "172.16.0.0/22 is subnetted, 1 subnets"', back: 'Every route shown under it shares **one mask** — a single /22 subnet within the classful 172.16.0.0/16 network. ("1 subnets" is IOS\'s literal wording.)' },
  { id: 'f23', front: 'Best single summary for six /24s, 172.16.8.0–172.16.13.0', back: '**172.16.8.0/21** — exact would need two routes instead: 172.16.8.0/22 (networks 8–11) + 172.16.12.0/23 (networks 12–13).' },
  { id: 'f24', front: 'Why avoid handing out address blocks at random across sites?', back: 'Summarization only works cleanly when each site\'s networks are **contiguous and aligned**, so plan addressing hierarchically from the start.' },
];

export const quiz: Question[] = [
  {
    id: 'q1',
    type: 'single',
    stem: 'When designing a VLSM address plan, which subnets should be allocated first?',
    options: ['The smallest subnets', 'The largest subnets', 'The WAN links', 'Whichever is listed first, in any size order'],
    answer: 1,
    difficulty: 1,
    explanation: 'Allocating the **largest** subnets first guarantees every later, smaller subnet starts on a valid boundary for its own block size. Starting small and working up is how out-of-order designs create accidental overlaps.',
  },
  {
    id: 'q2',
    type: 'input',
    stem: 'A LAN needs 90 usable host addresses. What is the smallest (most efficient) prefix that provides enough addresses?',
    answers: ['/25', '25'],
    placeholder: '/nn',
    difficulty: 1,
    explanation: 'A /25 gives 7 host bits: 2^7 − 2 = **126** usable hosts, which covers 90. A /26 gives only 2^6 − 2 = 62, too few.',
  },
  {
    id: 'q3',
    type: 'multi',
    stem: 'Which two statements about a /31 mask on a point-to-point link are true? (Choose two.)',
    options: [
      'It is permitted by RFC 3021',
      'Both addresses in the /31 are usable host addresses',
      'It requires OSPF to be running on the link',
      'It uses twice as many addresses as a /30 for the same link',
      'It can only be used on Ethernet access ports',
    ],
    answers: [0, 1],
    difficulty: 2,
    explanation: '**RFC 3021** defines the /31 point-to-point exception, and because no address is reserved for a network ID or broadcast, **both** addresses are usable. A /31 uses half the addresses of a /30, not twice as many, has nothing to do with which routing protocol runs, and applies to point-to-point links, not access ports.',
  },
  {
    id: 'q4',
    type: 'single',
    stem: 'Do the subnets 10.5.16.0/22 and 10.5.18.0/24 overlap?',
    options: [
      'Yes — 10.5.18.0 falls inside the range of 10.5.16.0/22',
      'No — different prefix lengths can never overlap',
      'No — they are in different major networks',
      'Only if both are configured on the same router',
    ],
    answer: 0,
    difficulty: 2,
    explanation: '10.5.16.0/22 spans 10.5.16.0 – 10.5.19.255 (block size 4 in the third octet). 10.5.18.0 sits inside that range, so the /24 is fully **contained** in the /22 — this is an overlap regardless of which router(s) they are configured on.',
  },
  {
    id: 'q5',
    type: 'single',
    stem: 'An engineer configures an IP address on a second interface of a router, and the subnet duplicates one already assigned to another interface on the same router. What happens?',
    options: [
      'IOS accepts it silently',
      'IOS rejects the command with an "overlaps with" error naming the other interface',
      'IOS accepts it but disables the older interface',
      'IOS converts the new address to the next free subnet automatically',
    ],
    answer: 1,
    difficulty: 1,
    explanation: 'IOS checks a new interface address against every other configured interface **on the same router** and rejects an overlapping subnet with a message naming the conflicting interface. It does not auto-correct the address, and it never disables an existing interface to make room.',
  },
  {
    id: 'q6',
    type: 'match',
    stem: 'Match each prefix to its block size (the spacing between valid subnet boundaries).',
    pairs: [
      { left: '/26', right: '64' },
      { left: '/27', right: '32' },
      { left: '/28', right: '16' },
      { left: '/30', right: '4' },
    ],
    difficulty: 1,
    explanation: 'Block size = 2^(32 − prefix) in the interesting octet: /26 → 2^6 = 64, /27 → 2^5 = 32, /28 → 2^4 = 16, /30 → 2^2 = 4. Every valid subnet of that prefix starts on a multiple of its block size.',
  },
  {
    id: 'q7',
    type: 'single',
    stem: 'What is the main benefit of advertising a route summary instead of several individual subnet routes?',
    options: [
      'It always creates a shorter path to every destination',
      'It removes the need for a default route',
      'It shrinks the routing table and hides instability in one of the summarized subnets from routers beyond the summarizing router',
      'It guarantees no address space is ever wasted',
    ],
    answer: 2,
    difficulty: 2,
    explanation: 'A summary replaces many specific routes with one, so routers beyond it carry less state and do not recompute anything when a subnet inside the summary flaps. It does not change the physical path, has nothing to do with default routes, and — as the deck showed — summaries can waste address space rather than guarantee against it.',
  },
];

export const exam: Question[] = [
  {
    id: 'e1',
    type: 'single',
    stem: 'Refer to the exhibit. An engineer is using VLSM to subnet 10.10.0.0/24 for four LANs. Which prefix should be assigned to LAN-A?',
    exhibit: {
      kind: 'table',
      columns: ['Segment', 'Hosts needed'],
      rows: [
        ['LAN-A', '60'],
        ['LAN-B', '28'],
        ['LAN-C', '12'],
        ['LAN-D', '6'],
      ],
    },
    options: ['/25', '/26', '/27', '/28'],
    answer: 1,
    difficulty: 2,
    explanation: 'A /26 leaves 6 host bits: 2^6 − 2 = **62** usable hosts, enough for 60 and the smallest prefix that fits. A /27 gives only 30 hosts (too few), and /25 (126 hosts) works but wastes more than half the subnet — not the most efficient choice.',
  },
  {
    id: 'e2',
    type: 'single',
    stem: 'Refer to the exhibit (same requirements as the previous question). LAN-A (60 hosts) is allocated first as 10.10.0.0/26. Which network should LAN-B (28 hosts, needs a /27) receive next?',
    exhibit: {
      kind: 'table',
      columns: ['Segment', 'Hosts needed'],
      rows: [
        ['LAN-A', '60'],
        ['LAN-B', '28'],
        ['LAN-C', '12'],
        ['LAN-D', '6'],
      ],
    },
    options: ['10.10.0.32/27', '10.10.0.64/27', '10.10.0.96/27', '10.10.0.128/27'],
    answer: 1,
    difficulty: 2,
    explanation: 'LAN-A\'s /26 occupies 10.10.0.0 – .63, so the next free address is .64, which is also a valid /27 boundary (a multiple of 32). 10.10.0.32/27 falls **inside** LAN-A\'s range, and .96 or .128 would skip usable space.',
  },
  {
    id: 'e3',
    type: 'input',
    stem: 'Continuing the same plan: LAN-A gets 10.10.0.0/26, LAN-B gets 10.10.0.64/27, and LAN-C (12 hosts) gets the next /28. What network address does LAN-D (6 hosts, needs a /29) receive?',
    answers: ['10.10.0.112/29', '10.10.0.112'],
    placeholder: 'a.b.c.d/nn',
    difficulty: 3,
    explanation: 'LAN-B\'s /27 ends at .95, so LAN-C\'s /28 starts at the next multiple of 16, which is .96, and ends at .111. LAN-D\'s /29 then starts at the next multiple of 8, which is **.112**, giving **10.10.0.112/29** (covering .112–.119).',
  },
  {
    id: 'e4',
    type: 'multi',
    stem: 'Which two statements about VLSM are true? (Choose two.)',
    options: [
      'It allows different prefix lengths within one major network block',
      'It requires a classful routing protocol to advertise the routes',
      'Allocating the largest subnets first avoids most alignment errors',
      'Every subnet in a VLSM design must be the same size',
      'It can only be used with private (RFC 1918) address ranges',
    ],
    answers: [0, 2],
    difficulty: 2,
    explanation: 'VLSM is defined by using **different prefix lengths** inside one block, and allocating **largest first** keeps every later subnet on a valid boundary. It needs a **classless** protocol (the opposite of classful), subnets are deliberately different sizes, and VLSM works with any address range, public or private.',
  },
  {
    id: 'e5',
    type: 'single',
    stem: 'Refer to the exhibit, which lists subnets already assigned inside 172.20.0.0/16. Which new /25 subnet can be assigned without overlapping any of them?',
    exhibit: {
      kind: 'table',
      columns: ['Subnet', 'Range covered'],
      rows: [
        ['172.20.4.0/23', '172.20.4.0 – 172.20.5.255'],
        ['172.20.8.0/24', '172.20.8.0 – 172.20.8.255'],
        ['172.20.9.0/25', '172.20.9.0 – 172.20.9.127'],
      ],
    },
    options: ['172.20.4.128/25', '172.20.5.0/25', '172.20.8.128/25', '172.20.9.128/25'],
    answer: 3,
    difficulty: 3,
    explanation: '172.20.9.128/25 covers .9.128 – .9.255, which none of the three existing subnets touch. 172.20.4.128/25 and 172.20.5.0/25 both fall inside the /23 (.4.0–.5.255), and 172.20.8.128/25 falls inside the /24 (.8.0–.8.255).',
  },
  {
    id: 'e6',
    type: 'single',
    stem: 'Refer to the exhibit. Hosts on R1\'s directly connected LAN, 10.20.0.0/23, intermittently cannot reach each other locally — some traffic instead crosses the WAN to R2 and back. What is the most likely cause?',
    exhibit: {
      kind: 'cli',
      text: `R1# show ip route | include 10.20
      10.0.0.0/8 is variably subnetted, 2 subnets, 2 masks
C        10.20.0.0/23 is directly connected, GigabitEthernet0/0/1
O        10.20.1.0/26 [110/20] via 10.0.12.2, 00:01:40, Serial0/1/0`,
    },
    options: [
      'R2 is advertising an overlapping, more specific subnet that wins by longest prefix match',
      'GigabitEthernet0/0/1 is administratively down',
      'R1 is missing a default route',
      'The OSPF process ID on R1 does not match R2',
    ],
    answer: 0,
    difficulty: 3,
    explanation: '10.20.1.0/26 sits entirely inside the connected 10.20.0.0/23. Because it is the **longer (more specific) match**, R1 forwards traffic for 10.20.1.0–.63 to R2 over OSPF instead of switching it locally — classic cross-router overlap. The connected route being present rules out a down interface, and neither a default route nor a process-ID mismatch explains a longest-match preference for a route that IS installed.',
  },
  {
    id: 'e7',
    type: 'match',
    stem: 'Match each term to its correct description.',
    pairs: [
      { left: 'VLSM', right: 'Different prefix lengths used within one address block' },
      { left: 'RFC 3021', right: 'Permits a /31 mask on point-to-point links' },
      { left: 'Longest prefix match', right: 'The most specific matching route in the table is always preferred' },
      { left: 'Supernetting', right: 'Combining contiguous networks into one shorter-prefix route' },
    ],
    difficulty: 1,
    explanation: 'VLSM varies prefix length within a block; RFC 3021 defines the /31 exception; longest prefix match is the forwarding rule that always wins regardless of administrative distance or metric; supernetting is another name for route summarization.',
  },
  {
    id: 'e8',
    type: 'order',
    stem: 'Put the steps of a VLSM design process in the correct order.',
    items: [
      'List every segment with its required number of hosts',
      'Sort the segments from largest to smallest',
      'Choose the smallest prefix that satisfies each segment',
      'Allocate each subnet starting at the next free address that is a multiple of its block size',
      'Record the plan and verify that no two subnets overlap',
    ],
    difficulty: 2,
    explanation: 'Sizing before sorting would allocate out of order and risk misaligned starting addresses; verifying only at the end catches mistakes without slowing down the allocation itself.',
  },
  {
    id: 'e9',
    type: 'categorize',
    stem: 'Sort each address into whether it is a valid /27 network ID inside 192.168.10.0/24.',
    categories: ['Valid /27 network ID', 'Not a valid /27 network ID'],
    items: [
      { text: '192.168.10.32', category: 0 },
      { text: '192.168.10.64', category: 0 },
      { text: '192.168.10.48', category: 1 },
      { text: '192.168.10.96', category: 0 },
      { text: '192.168.10.100', category: 1 },
      { text: '192.168.10.200', category: 1 },
    ],
    difficulty: 2,
    explanation: 'A /27 has a block size of 32, so valid network IDs are multiples of 32: .0, .32, .64, .96, .128, .160, .192, .224. 48, 100 and 200 are not multiples of 32, so they are host addresses inside some other /27, not network IDs.',
  },
  {
    id: 'e10',
    type: 'single',
    stem: 'Which routing protocol would fail to correctly advertise a VLSM design that uses mixed prefix lengths within one major network?',
    options: ['OSPFv2', 'EIGRP', 'RIPv2', 'RIPv1'],
    answer: 3,
    difficulty: 1,
    explanation: '**RIPv1** is a classful protocol: it does not carry a mask in its updates and assumes one mask per major network, so it cannot represent VLSM. OSPFv2, EIGRP and RIPv2 are all classless and send the mask with every route.',
  },
  {
    id: 'e11',
    type: 'single',
    stem: 'Refer to the exhibit. R1\'s LAN uses 10.5.5.0/25. The serial link to R2 needs only 2 host addresses. Which address/mask should be assigned to the WAN link so it neither overlaps the LAN nor wastes more address space than necessary?',
    exhibit: {
      kind: 'diagram',
      diagram: {
        type: 'topology',
        width: 8,
        height: 3,
        nodes: [
          { id: 'lan', icon: 'switch', label: 'LAN', sub: '10.5.5.0/25', x: 1, y: 1.5 },
          { id: 'r1', icon: 'router', label: 'R1', x: 3.8, y: 1.5, tone: 'accent' },
          { id: 'r2', icon: 'router', label: 'R2', x: 6.5, y: 1.5 },
        ],
        links: [
          { from: 'lan', to: 'r1' },
          { from: 'r1', to: 'r2', label: 'WAN link · 2 hosts', style: 'serial' },
        ],
      },
    },
    options: ['10.5.5.128/30', '10.5.5.64/30', '10.5.5.130/30', '10.5.5.192/29'],
    answer: 0,
    difficulty: 2,
    explanation: '10.5.5.128/30 is the first free, aligned block after the LAN\'s /25 (which ends at .127). 10.5.5.64/30 falls inside the LAN range; 10.5.5.130/30 is not a multiple of 4, so it is not a valid /30 network ID; 10.5.5.192/29 does not overlap but wastes 4 extra addresses for a link that only needs 2.',
  },
  {
    id: 'e12',
    type: 'input',
    stem: 'What is the best (longest, exact) single summary route for 192.168.16.0/24, 192.168.17.0/24, 192.168.18.0/24 and 192.168.19.0/24?',
    answers: ['192.168.16.0/22', '192.168.16.0 255.255.252.0'],
    placeholder: 'a.b.c.d/nn',
    difficulty: 2,
    explanation: '16, 17, 18 and 19 share their first six bits in the third octet (00010 0__), giving 16 + 6 = 22 matching bits. Because 16 is a multiple of 4 (the block size for 4 networks), **192.168.16.0/22** exactly covers all four with nothing extra.',
  },
  {
    id: 'e13',
    type: 'single',
    stem: 'Refer to the exhibit. Which single command replaces all four static routes with one equivalent summary route via 10.0.0.2?',
    exhibit: {
      kind: 'cli',
      text: `R1# show running-config | include ip route
ip route 10.4.4.0 255.255.255.0 10.0.0.2
ip route 10.4.5.0 255.255.255.0 10.0.0.2
ip route 10.4.6.0 255.255.255.0 10.0.0.2
ip route 10.4.7.0 255.255.255.0 10.0.0.2`,
    },
    options: [
      'ip route 10.4.4.0 255.255.252.0 10.0.0.2',
      'ip route 10.4.4.0 255.255.248.0 10.0.0.2',
      'ip route 10.4.0.0 255.255.252.0 10.0.0.2',
      'ip route 10.4.4.0 255.255.255.0 10.0.0.2',
    ],
    answer: 0,
    difficulty: 3,
    explanation: 'Networks 4–7 share their leading 6 bits in the third octet, giving a /22: **10.4.4.0 255.255.252.0** (255.255.252.0 = /22) covers exactly 10.4.4.0–10.4.7.255. 255.255.248.0 is a /21 whose valid boundary near here is 10.4.0.0, not 10.4.4.0; 10.4.0.0/22 covers networks 0–3, not 4–7; and 255.255.255.0 is only one /24, not a summary at all.',
  },
  {
    id: 'e14',
    type: 'multi',
    stem: 'Which two are genuine risks of route summarization? (Choose two.)',
    options: [
      'It can attract traffic for addresses that are not actually in use downstream',
      'It always improves routing accuracy',
      'An inexact summary can cover more address space than the site actually owns',
      'It eliminates the need for any routing protocol',
      'It doubles the number of routes advertised',
    ],
    answers: [0, 2],
    difficulty: 2,
    explanation: 'A summary can claim addresses that are unused or belong elsewhere, drawing traffic that is then dropped or misrouted, and an inexact summary (not an aligned power of two) always covers extra space. Summarization reduces route count, does not remove the need for a routing protocol, and does not by itself improve accuracy — it trades detail for smaller tables.',
  },
  {
    id: 'e15',
    type: 'single',
    stem: 'A network engineer wants to guarantee that a summary for N contiguous /24 networks is exact, with no extra addresses included. Which condition must be true?',
    options: [
      'N must be a power of two, and the first network\'s value in the varying octet must be a multiple of N',
      'N must be an even number',
      'All N networks must share the same second octet',
      'The summary must always be exactly one bit shorter than /24',
    ],
    answer: 0,
    difficulty: 2,
    explanation: 'An exact summary needs the group to align on its own block boundary: N networks need N to be a power of two (so the bit math works out evenly) and the first network to start on a multiple of N. An even N like 6 (not a power of two) or a misaligned starting point always leaves the summary either too short (missing networks) or too long (including unused ones).',
  },
  {
    id: 'e16',
    type: 'single',
    stem: 'Refer to the exhibit. What must be true about GigabitEthernet0/0/1 on R2?',
    exhibit: {
      kind: 'cli',
      text: `R2(config)# interface GigabitEthernet0/0/2
R2(config-if)# ip address 192.168.30.65 255.255.255.192
% 192.168.30.64 overlaps with GigabitEthernet0/0/1`,
    },
    options: [
      'It already has an IP address inside the 192.168.30.64/26 subnet',
      'It is administratively shut down',
      'It is configured as a trunk port',
      'It is running a different OSPF process than GigabitEthernet0/0/2',
    ],
    answer: 0,
    difficulty: 1,
    explanation: 'IOS only prints an "overlaps with" error when the new subnet duplicates one already assigned to another **active configuration** on the same router — so GigabitEthernet0/0/1 must already own an address inside 192.168.30.64/26. Shutdown state, trunk mode and OSPF process membership have nothing to do with this check.',
  },
  {
    id: 'e17',
    type: 'input',
    stem: 'A /24 network, 10.1.9.0/24, is divided with VLSM into one /26, one /27 and two /28 subnets, allocated in that order starting from 10.1.9.0. What is the network address of the second /28?',
    answers: ['10.1.9.112/28', '10.1.9.112'],
    placeholder: 'a.b.c.d/nn',
    difficulty: 3,
    explanation: 'The /26 occupies .0–.63, the /27 occupies the next block, .64–.95, and the first /28 occupies .96–.111. The second /28 then starts at the next multiple of 16, which is **10.1.9.112/28** (covering .112–.127).',
  },
  {
    id: 'e18',
    type: 'single',
    stem: 'Which statement correctly compares administrative distance, metric and longest prefix match when a router chooses how to forward a packet?',
    options: [
      'Longest prefix match is applied first; AD and metric only decide between competing routes to the identical prefix',
      'Administrative distance always overrides a longer prefix match from a different source',
      'Metric is compared before prefix length, regardless of protocol',
      'Longest prefix match only applies when static routes are involved',
    ],
    answer: 0,
    difficulty: 3,
    explanation: 'A router always forwards using the most specific (longest) matching prefix in the table, no matter which protocol installed it or its distance/metric. AD and metric only break ties among **multiple routes to the same prefix** — they never make a shorter prefix beat a longer, more specific one, which is exactly why an overlapping subnet from a different router can silently steal traffic.',
  },
];
