/**
 * The WizardCCNA curriculum: a single learning path that covers the union of the
 * CCNA 200-301 v1.1 exam topics (current exam, last test date 2 Feb 2027) and the
 * CCNA 200-301 v2.0 exam topics (first test date 3 Feb 2027).
 *
 * Lessons are listed in recommended learning order. `v11` holds the official v1.1 topic codes a
 * lesson covers; `v20` holds the v2.0 domain number. A lesson with no `v11` codes is v2.0-only,
 * and a lesson with no `v20` domain is v1.1-only. `focus` is the coverage checklist: every item must
 * be taught in the slides and tested by flashcards/questions.
 */

export type ExamVersion = 'v1.1' | 'v2.0';

export interface ExamDomain {
  num: number;
  title: string;
  /** Percentage of the exam. */
  weight: number;
}

export interface ExamVersionInfo {
  id: ExamVersion;
  name: string;
  /** Inclusive date range (YYYY-MM-DD) in which this version is the live exam. */
  from?: string;
  until?: string;
  domains: ExamDomain[];
  durationMin: number;
  questionCount: number;
}

export const EXAM_VERSIONS: Record<ExamVersion, ExamVersionInfo> = {
  'v1.1': {
    id: 'v1.1',
    name: 'CCNA 200-301 v1.1',
    until: '2027-02-02',
    durationMin: 120,
    questionCount: 100,
    domains: [
      { num: 1, title: 'Network Fundamentals', weight: 20 },
      { num: 2, title: 'Network Access', weight: 20 },
      { num: 3, title: 'IP Connectivity', weight: 25 },
      { num: 4, title: 'IP Services', weight: 10 },
      { num: 5, title: 'Security Fundamentals', weight: 15 },
      { num: 6, title: 'Automation and Programmability', weight: 10 },
    ],
  },
  'v2.0': {
    id: 'v2.0',
    name: 'CCNA 200-301 v2.0',
    from: '2027-02-03',
    durationMin: 120,
    questionCount: 100,
    domains: [
      { num: 1, title: 'Network Infrastructure and Connectivity', weight: 25 },
      { num: 2, title: 'Switching and Network Access', weight: 25 },
      { num: 3, title: 'IP Routing', weight: 20 },
      { num: 4, title: 'Network Services and Security', weight: 20 },
      { num: 5, title: 'AI and Network Operations', weight: 10 },
    ],
  },
};

/** The exam version that is live on a given date (YYYY-MM-DD). */
export function versionForDate(date: string): ExamVersion {
  return date >= (EXAM_VERSIONS['v2.0'].from as string) ? 'v2.0' : 'v1.1';
}

export interface LessonMeta {
  id: string;
  title: string;
  summary: string;
  /** Estimated minutes to study the deck + quiz. */
  minutes: number;
  /** v1.1 exam topic codes (e.g. "1.6", "2.5.c"). */
  v11?: string[];
  /** v2.0 domain number. */
  v20?: number;
  focus: string[];
}

export interface ModuleMeta {
  id: string;
  title: string;
  description: string;
  lessons: LessonMeta[];
}

export const MODULES: ModuleMeta[] = [
  {
    id: 'foundations',
    title: 'Network Foundations',
    description: 'How networks are built: models, devices, architectures, cabling, and the transport layer.',
    lessons: [
      {
        id: 'network-models',
        title: 'OSI & TCP/IP Models',
        summary: 'The layered models every networking conversation is built on, encapsulation and PDUs.',
        minutes: 40,
        v11: ['1.1', '1.5'],
        v20: 1,
        focus: [
          'Why layered models exist; OSI 7 layers with names, numbers, functions and example protocols/devices',
          'TCP/IP model (4-layer and 5-layer "updated" variants) mapped to OSI',
          'Encapsulation/de-encapsulation; PDU names: data, segment, packet, frame, bits',
          'Same-layer and adjacent-layer interaction; headers and trailers (Ethernet FCS)',
          'Which devices operate at which layer (hub L1, switch L2, router L3, L4-L7 firewall)',
          'Common mnemonics and exam traps (e.g. MAC=L2, IP=L3, port numbers=L4)',
        ],
      },
      {
        id: 'network-components',
        title: 'Network Components',
        summary: 'Routers, switches, firewalls, IPS, APs, controllers, endpoints and servers.',
        minutes: 45,
        v11: ['1.1', '1.1.a', '1.1.b', '1.1.c', '1.1.d', '1.1.e', '1.1.f', '1.1.g'],
        v20: 1,
        focus: [
          'Routers: connect networks, route between subnets, WAN edge; control vs data plane basics',
          'Layer 2 switches vs Layer 3 (multilayer) switches; collision and broadcast domains',
          'Next-generation firewalls (stateful inspection, AVC, URL filtering, IPS, AMP) vs traditional firewalls; zones',
          'IPS vs IDS (inline vs promiscuous), signatures; NGIPS',
          'Access points (autonomous vs lightweight) and wireless LAN controllers',
          'Controllers: WLC, Cisco Catalyst Center (formerly DNA Center), Meraki dashboard concept',
          'Endpoints (PCs, phones, IoT) and servers (client-server vs peer-to-peer)',
        ],
      },
      {
        id: 'topology-architectures',
        title: 'Topology Architectures',
        summary: 'Two-tier, three-tier, spine-leaf, SOHO, and on-premises vs cloud designs.',
        minutes: 40,
        v11: ['1.2', '1.2.a', '1.2.b', '1.2.c', '1.2.e', '1.2.f'],
        v20: 1,
        focus: [
          'Campus hierarchical design: access, distribution, core layers and their roles',
          'Two-tier (collapsed core) vs three-tier; when to choose each',
          'Spine-leaf data center design: every leaf connects to every spine, no leaf-leaf/spine-spine links, predictable latency, east-west traffic',
          'Physical topologies: star, extended star, full/partial mesh, hybrid; redundancy trade-offs',
          'SOHO networks: all-in-one wireless router (router, switch, AP, firewall, DHCP, NAT)',
          'On-premises vs cloud (public, private, hybrid) as a topology choice',
        ],
      },
      {
        id: 'wan-technologies',
        title: 'WAN Architectures',
        summary: 'Leased lines, MPLS, Metro Ethernet, Internet VPNs, SD-WAN and broadband access.',
        minutes: 40,
        v11: ['1.2.d'],
        v20: 1,
        focus: [
          'WAN topologies: point-to-point, hub-and-spoke, full mesh, dual-homed/single-homed',
          'Leased lines (serial, HDLC/PPP awareness), CSU/DSU, DCE/DTE',
          'MPLS VPN: CE, PE, P routers; Layer 3 MPLS VPN vs Layer 2',
          'Metro Ethernet services: E-Line (point-to-point), E-LAN (full mesh), E-Tree (hub-and-spoke)',
          'Internet access: DSL, cable, fiber (FTTH), 4G/5G, satellite',
          'Internet VPNs (site-to-site, remote access) and SD-WAN at a high level',
        ],
      },
      {
        id: 'cabling-interfaces',
        title: 'Cabling & Physical Interfaces',
        summary: 'Copper and fiber media, connectors, Ethernet standards, shared vs point-to-point.',
        minutes: 45,
        v11: ['1.3', '1.3.a', '1.3.b'],
        v20: 1,
        focus: [
          'Ethernet standards: 10BASE-T, 100BASE-T, 1000BASE-T, 10GBASE-T, 1000BASE-SX/LX, 10GBASE-SR/LR; IEEE names',
          'UTP categories (Cat5e, Cat6, Cat6a) and 100 m copper limit; RJ-45; pinouts',
          'Straight-through vs crossover cables, which pairs are used; Auto-MDIX',
          'Fiber: single-mode (laser, long distance, small core) vs multimode (LED/VCSEL, shorter, larger core); connectors (LC, SC); SFP/SFP+ transceivers',
          'Shared media (hubs, half duplex, CSMA/CD) vs point-to-point (switched, full duplex)',
          'Console cables (rollover, USB), serial WAN cables awareness',
        ],
      },
      {
        id: 'poe',
        title: 'Power over Ethernet',
        summary: 'PoE standards, PSE and PD roles, power budgets and switchport PoE configuration.',
        minutes: 25,
        v11: ['1.1.h'],
        v20: 2,
        focus: [
          'PoE purpose and devices powered (APs, IP phones, cameras, IoT)',
          'PSE (switch/injector) vs PD (powered device); detection and classification',
          'Standards and power: 802.3af (PoE, 15.4 W), 802.3at (PoE+, 30 W), 802.3bt (UPoE/PoE++, 60 W/90–100 W), Cisco UPOE',
          'Power budget planning on a switch',
          'IOS: `power inline auto|never|static`, `show power inline`',
        ],
      },
      {
        id: 'interface-issues',
        title: 'Interface & Cable Issues',
        summary: 'Diagnosing collisions, errors, duplex and speed mismatches with show commands.',
        minutes: 40,
        v11: ['1.4'],
        v20: 1,
        focus: [
          '`show interfaces` fields: line/protocol status combinations (up/up, up/down, down/down, administratively down)',
          'Error counters: input errors, CRC, runts, giants, frame, output errors, collisions, late collisions',
          'Duplex mismatch symptoms (late collisions on half side, CRC/runts on full side); speed mismatch (link down)',
          'Autonegotiation behavior and defaults when one side is hard-coded (duplex fallback rules)',
          '`speed` and `duplex` commands; `show interfaces status`; err-disabled state',
          'Physical layer troubleshooting: bad cables, EMI, wrong cable type, bad SFP',
        ],
      },
      {
        id: 'tcp-udp',
        title: 'TCP vs UDP',
        summary: 'Transport layer services, the three-way handshake, windowing and well-known ports.',
        minutes: 40,
        v11: ['1.5'],
        v20: 1,
        focus: [
          'Transport layer role: multiplexing with port numbers, sockets',
          'TCP: connection-oriented, three-way handshake (SYN, SYN-ACK, ACK), four-way termination (FIN/ACK), sequence and acknowledgment numbers',
          'Reliability: acknowledgments, retransmission; flow control with windowing (sliding windows)',
          'UDP: connectionless, low overhead, no reliability; use cases (VoIP, video, DNS, DHCP, TFTP, SNMP, syslog)',
          'TCP and UDP header fields comparison',
          'Well-known ports: FTP 20/21, SSH 22, Telnet 23, SMTP 25, DNS 53, DHCP 67/68, TFTP 69, HTTP 80, POP3 110, NTP 123, IMAP 143, SNMP 161/162, HTTPS 443, syslog 514',
          'Port ranges: well-known 0–1023, registered 1024–49151, dynamic/ephemeral 49152–65535',
        ],
      },
    ],
  },
  {
    id: 'ethernet-ios',
    title: 'Ethernet Switching & IOS',
    description: 'How switches forward frames, and how to drive Cisco IOS from the command line.',
    lessons: [
      {
        id: 'ethernet-switching',
        title: 'Ethernet & Switching Concepts',
        summary: 'Frames, MAC addresses, MAC learning and aging, forwarding, filtering and flooding.',
        minutes: 45,
        v11: ['1.13', '1.13.a', '1.13.b', '1.13.c', '1.13.d'],
        v20: 2,
        focus: [
          'Ethernet frame format (preamble, SFD, destination, source, type/length, data, FCS); min 64 / max 1518 bytes',
          'MAC address structure (OUI + NIC-specific), unicast/broadcast/multicast MACs',
          'MAC learning from source addresses; aging (default 300 seconds)',
          'Forward vs filter vs flood decisions; unknown unicast, broadcast and multicast flooding',
          'MAC address table: `show mac address-table`, dynamic vs static entries, `clear mac address-table dynamic`',
          'Collision domains vs broadcast domains; half/full duplex on switches',
          'Switching methods awareness: store-and-forward, cut-through, fragment-free',
        ],
      },
      {
        id: 'ios-cli-basics',
        title: 'Cisco IOS CLI Essentials',
        summary: 'CLI modes, help, configuration files, basic device settings and verification commands.',
        minutes: 50,
        v11: ['2.8', '5.3'],
        v20: 2,
        focus: [
          'Access methods: console, SSH, Telnet; terminal emulator settings (9600 8N1)',
          'User EXEC, privileged EXEC, global configuration and sub-configuration modes; prompts; enable/disable/exit/end/Ctrl+Z',
          'Context-sensitive help (?), command abbreviation, Tab completion, command history, `do` in config mode, `no` form',
          'running-config vs startup-config (RAM vs NVRAM); `copy running-config startup-config`, `write memory`, `reload`, `erase startup-config`',
          'Basic settings: hostname, enable secret, console/VTY passwords, banner motd, `no ip domain-lookup`, `logging synchronous`, `exec-timeout`',
          'Verification: `show running-config`, `show version`, `show ip interface brief`, `show interfaces`, `show history`',
          'Router boot sequence and memory types (ROM, flash, NVRAM, RAM) awareness',
          'Switch management: SVI (interface vlan 1) IP and `ip default-gateway`',
        ],
      },
    ],
  },
  {
    id: 'ipv4',
    title: 'IPv4 Addressing & Subnetting',
    description: 'Addressing, binary math, subnetting at exam speed, VLSM, private ranges and host verification.',
    lessons: [
      {
        id: 'ipv4-addressing',
        title: 'IPv4 Addressing',
        summary: 'The IPv4 header, binary and decimal, classes, prefixes, default gateways and ARP.',
        minutes: 50,
        v11: ['1.6'],
        v20: 1,
        focus: [
          'IPv4 header fields (version, IHL, DSCP/ECN, total length, ID, flags, fragment offset, TTL, protocol, checksum, source, destination)',
          'Binary ↔ decimal conversion of octets; powers of two',
          'Address classes A/B/C/D/E ranges and default masks (classful awareness); network vs host portion',
          'Special addresses: network address, broadcast address, 0.0.0.0, 255.255.255.255, 127.0.0.0/8 loopback, 169.254.0.0/16 APIPA',
          'Unicast vs broadcast vs multicast (224.0.0.0/4)',
          'Configuring IPv4 on router interfaces (`ip address`, `no shutdown`) and verifying (`show ip interface brief`, `show ip interface`)',
          'Default gateway role; ARP process (request broadcast, reply unicast), `show arp`, `arp -a`',
        ],
      },
      {
        id: 'subnetting',
        title: 'Subnetting',
        summary: 'Masks, CIDR, host and subnet math, and finding network/broadcast/range fast.',
        minutes: 90,
        v11: ['1.6'],
        v20: 1,
        focus: [
          'Subnet masks in dotted decimal and prefix length (CIDR) notation; valid mask octet values (0,128,192,224,240,248,252,254,255)',
          'Hosts per subnet = 2^h − 2; number of subnets = 2^s; /31 point-to-point (RFC 3021) and /32 host routes',
          'Finding the network ID, broadcast address, first/last usable host for any address and prefix',
          'The "magic number" (block size) method in the interesting octet; worked examples in octets 2, 3 and 4',
          'Choosing a mask to meet host or subnet requirements',
          'Determining whether two hosts are in the same subnet; identifying a subnet from a host address',
          'Common exam traps: /30 vs /31, off-by-one on broadcast, subnet zero is valid',
        ],
      },
      {
        id: 'vlsm',
        title: 'VLSM & Summarization',
        summary: 'Designing variable-length subnets without overlap, and summarizing routes.',
        minutes: 60,
        v11: ['1.6'],
        v20: 1,
        focus: [
          'Why VLSM: efficient allocation; allocate largest subnets first',
          'Step-by-step VLSM design from a given block with multiple host requirements, including /30 or /31 WAN links',
          'Detecting overlapping subnets',
          'Route summarization (supernetting): finding the best summary of contiguous networks by binary comparison',
          'Summarization benefits: smaller routing tables, stability; risk of including unused ranges',
        ],
      },
      {
        id: 'private-ipv4',
        title: 'Private IPv4 Addressing',
        summary: 'RFC 1918 ranges, why private addressing exists and how it relates to NAT.',
        minutes: 25,
        v11: ['1.7'],
        v20: 1,
        focus: [
          'IPv4 exhaustion; IANA/RIR allocation awareness',
          'RFC 1918: 10.0.0.0/8, 172.16.0.0/12 (172.16–172.31), 192.168.0.0/16',
          'Private addresses are not routed on the Internet; need for NAT/PAT to reach the Internet',
          'Other special-purpose ranges: 100.64.0.0/10 (CGNAT shared), 169.254.0.0/16, 127.0.0.0/8, documentation 192.0.2.0/24 etc.',
          'Identifying whether a given address is public or private',
        ],
      },
      {
        id: 'client-ip-verification',
        title: 'Verifying & Troubleshooting Client IP Settings',
        summary: 'Checking IP, mask, gateway and DNS on Windows, macOS and Linux — wired and wireless.',
        minutes: 40,
        v11: ['1.10'],
        v20: 1,
        focus: [
          'Windows: `ipconfig`, `ipconfig /all`, `ipconfig /release` and `/renew`, `ipconfig /flushdns`, `route print`, `netstat -rn`, `arp -a`, `nslookup`, `tracert`',
          'macOS: `ifconfig`, `networksetup -getinfo Wi-Fi`, `netstat -rn`, `scutil --dns`, `traceroute`',
          'Linux: `ip address`, `ip route`, `ifconfig`, `resolvectl`/`/etc/resolv.conf`, `nmcli`, `traceroute`',
          'Interpreting output: IP, mask/prefix, default gateway, DNS servers, MAC, DHCP lease, APIPA 169.254.x.x meaning',
          'Troubleshooting flow for a client that cannot reach a server: link, IP config, gateway, DNS, remote reachability',
          'Wireless client issues: wrong SSID/PSK, weak signal, band, DHCP failures',
        ],
      },
    ],
  },
  {
    id: 'ipv6',
    title: 'IPv6',
    description: 'IPv6 addressing, abbreviation, address types, EUI-64 and how hosts get addresses.',
    lessons: [
      {
        id: 'ipv6-fundamentals',
        title: 'IPv6 Addressing Fundamentals',
        summary: 'Hex notation, abbreviation rules, prefixes, the IPv6 header and configuration.',
        minutes: 50,
        v11: ['1.8'],
        v20: 1,
        focus: [
          'Why IPv6; 128-bit addresses, 8 hextets, hexadecimal ↔ binary',
          'Abbreviation rules: drop leading zeros, one :: for the longest run of all-zero hextets (leftmost if tie)',
          'Expanding abbreviated addresses to full form',
          'Prefix length notation; /64 standard for LANs; global routing prefix + subnet ID + interface ID',
          'IPv6 header fields vs IPv4 (version, traffic class, flow label, payload length, next header, hop limit); no fragmentation by routers, no checksum',
          'IOS configuration: `ipv6 unicast-routing`, `ipv6 address 2001:db8::1/64`, `ipv6 address ... eui-64`, `ipv6 address autoconfig`, `ipv6 enable`',
          'Verification: `show ipv6 interface brief`, `show ipv6 interface`, `show ipv6 route`',
        ],
      },
      {
        id: 'ipv6-address-types',
        title: 'IPv6 Address Types, EUI-64 & NDP',
        summary: 'Global unicast, unique local, link-local, anycast, multicast, EUI-64, SLAAC and DHCPv6.',
        minutes: 55,
        v11: ['1.9', '1.9.a', '1.9.b', '1.9.c', '1.9.d'],
        v20: 1,
        focus: [
          'Global unicast 2000::/3; unique local FC00::/7 (FD00::/8 in practice); link-local FE80::/10 (automatic, not routed)',
          'Multicast FF00::/8; well-known groups FF02::1 (all nodes), FF02::2 (all routers), FF02::5/::6 (OSPF), FF02::A, solicited-node FF02::1:FFxx:xxxx',
          'Anycast: same address on multiple devices, routed to nearest; no special range',
          'Special: :: unspecified, ::1 loopback; no broadcast in IPv6',
          'Modified EUI-64: split MAC, insert FFFE, flip the 7th (U/L) bit — worked examples',
          'NDP messages: RS, RA, NS, NA (replaces ARP), DAD; SLAAC vs stateless DHCPv6 vs stateful DHCPv6 (M and O flags)',
        ],
      },
    ],
  },
  {
    id: 'vlans',
    title: 'VLANs, Trunks & EtherChannel',
    description: 'Segmenting switched networks, carrying VLANs between switches, routing between them, and bundling links.',
    lessons: [
      {
        id: 'vlans',
        title: 'VLANs & Access Ports',
        summary: 'VLAN concepts, the default VLAN, data and voice VLANs, configuration and verification.',
        minutes: 50,
        v11: ['2.1', '2.1.a', '2.1.b'],
        v20: 2,
        focus: [
          'Why VLANs: broadcast domain segmentation, security, flexibility',
          'VLAN ranges: normal 1–1005 (1002–1005 reserved legacy), extended 1006–4094; VLAN 1 default (cannot delete); vlan.dat',
          'Creating and naming VLANs: `vlan 10`, `name SALES`; deleting VLANs and inactive ports',
          'Access ports: `switchport mode access`, `switchport access vlan 10`; unused ports to a parking VLAN and shutdown',
          'Voice VLAN: `switchport voice vlan 20`, IP phone with PC passthrough, CDP/LLDP role, CoS',
          'Verification: `show vlan brief`, `show interfaces switchport`, `show interfaces status`',
          'Troubleshooting: port in wrong VLAN, VLAN not created, VLAN shutdown',
        ],
      },
      {
        id: 'trunking',
        title: 'Trunking with 802.1Q',
        summary: '802.1Q tagging, native VLAN, allowed VLAN lists, DTP and VTP awareness.',
        minutes: 55,
        v11: ['2.2', '2.2.a', '2.2.b', '2.2.c'],
        v20: 2,
        focus: [
          '802.1Q tag: 4 bytes inserted after source MAC: TPID 0x8100, PCP (CoS, 3 bits), DEI, VID (12 bits); ISL is legacy/Cisco-proprietary',
          'Native VLAN: untagged frames; must match on both ends; native VLAN mismatch symptoms and CDP messages; best practice change from VLAN 1',
          'Configuring trunks: `switchport trunk encapsulation dot1q` (on multi-encap switches), `switchport mode trunk`, `switchport trunk native vlan`, `switchport trunk allowed vlan add|remove|except|none`',
          'DTP modes: access, trunk, dynamic desirable, dynamic auto, `switchport nonegotiate`; which combinations form a trunk (auto+auto = access)',
          'Verification: `show interfaces trunk` (allowed, active, forwarding in STP), `show interfaces switchport`',
          'VTP awareness: server/client/transparent/off modes, domain, revision number risk, VTPv3',
          'Troubleshooting: VLAN missing from allowed list, VLAN not existing on a switch, native mismatch',
        ],
      },
      {
        id: 'inter-vlan-routing',
        title: 'Inter-VLAN Routing',
        summary: 'Router-on-a-stick with subinterfaces and Layer 3 switch SVIs and routed ports.',
        minutes: 55,
        v11: ['2.1.c'],
        v20: 2,
        focus: [
          'Why routing is required between VLANs; one subnet per VLAN',
          'Router-on-a-stick: subinterfaces `interface g0/0.10`, `encapsulation dot1Q 10`, `encapsulation dot1Q 99 native`, trunk on switch side',
          'Layer 3 switch: `ip routing`, SVIs `interface vlan 10`, SVI up/up conditions (VLAN exists, a port in VLAN is up/forwarding, not shutdown)',
          'Routed ports on multilayer switches: `no switchport`',
          'Comparing legacy (one physical interface per VLAN), ROAS and L3 switch approaches',
          'Verification & troubleshooting: `show ip interface brief`, `show ip route`, wrong encapsulation VLAN, missing ip routing, host gateway wrong',
        ],
      },
      {
        id: 'discovery-protocols',
        title: 'CDP & LLDP',
        summary: 'Discovering neighbors with Cisco Discovery Protocol and LLDP; configuration and security.',
        minutes: 30,
        v11: ['2.3'],
        v20: 2,
        focus: [
          'CDP: Cisco-proprietary, Layer 2, enabled by default, 60 s timer / 180 s holdtime; CDPv2',
          'LLDP: IEEE 802.1AB, disabled by default on IOS, 30 s timer / 120 s holdtime, transmit/receive per interface',
          'Commands: `cdp run`, `no cdp enable`, `lldp run`, `lldp transmit`, `lldp receive`, `cdp timer`, `cdp holdtime`, `lldp timer`, `lldp holdtime`',
          'Verification: `show cdp neighbors`, `show cdp neighbors detail`, `show cdp entry *`, `show lldp neighbors [detail]`, `show cdp interface` — reading capability codes, local vs port ID',
          'Using discovery output to map a topology; security reasons to disable on edge ports',
        ],
      },
      {
        id: 'etherchannel',
        title: 'EtherChannel (LACP)',
        summary: 'Bundling links with LACP, PAgP or static on; Layer 2 and Layer 3 EtherChannels.',
        minutes: 50,
        v11: ['2.4'],
        v20: 2,
        focus: [
          'Why EtherChannel: bandwidth aggregation, redundancy, STP sees one logical link; up to 8 active links',
          'LACP (IEEE 802.3ad/802.1AX): active/passive; PAgP (Cisco): desirable/auto; static `on`; valid and invalid mode combinations',
          'Configuration: `interface range`, `channel-group 1 mode active`, port-channel interface settings',
          'Member requirements: same speed/duplex, same switchport mode, same access VLAN or trunk native/allowed VLANs',
          'Layer 3 EtherChannel: `no switchport` on members and port-channel, IP on the port-channel',
          'Load balancing: `port-channel load-balance src-dst-ip` etc.; flows not per-packet',
          'Verification: `show etherchannel summary` flags (P, D, I, s, SU, RU), `show etherchannel port-channel`, `show interfaces port-channel`',
          'Troubleshooting mismatched settings and suspended ports',
        ],
      },
    ],
  },
  {
    id: 'stp',
    title: 'Spanning Tree Protocol',
    description: 'Loop prevention with STP and Rapid PVST+, tuning the root, and protecting the edge.',
    lessons: [
      {
        id: 'stp-fundamentals',
        title: 'STP Fundamentals',
        summary: 'Why loops are deadly, bridge IDs, root election, port roles and costs.',
        minutes: 60,
        v11: ['2.5', '2.5.a', '2.5.b'],
        v20: 2,
        focus: [
          'Layer 2 loop problems: broadcast storms, MAC table instability, duplicate frames; no TTL in Ethernet',
          'BPDUs; Bridge ID = priority (default 32768, multiples of 4096) + extended system ID (VLAN) + MAC',
          'Root bridge election (lowest BID); root port selection (lowest root cost, then lowest sender BID, then lowest sender port ID)',
          'Designated port per segment; non-designated (blocking) ports',
          'Port costs (802.1D short: 10 Mbps=100, 100 Mbps=19, 1 Gbps=4, 10 Gbps=2) and awareness of long costs',
          '802.1D port states: blocking, listening, learning, forwarding, disabled; timers hello 2 s, max age 20 s, forward delay 15 s; convergence 30–50 s',
          'Working a full STP election example on a 3-switch triangle',
        ],
      },
      {
        id: 'rapid-pvst',
        title: 'Rapid PVST+',
        summary: 'RSTP roles and states, PVST+ per-VLAN trees, root primary/secondary, verification.',
        minutes: 55,
        v11: ['2.5', '2.5.a', '2.5.b'],
        v20: 2,
        focus: [
          'STP flavors: 802.1D, PVST+, 802.1w RSTP, Rapid PVST+, 802.1s MST; Cisco default PVST+ vs Rapid PVST+',
          'RSTP port roles: root, designated, alternate, backup, disabled; RSTP states: discarding, learning, forwarding',
          'RSTP link types (point-to-point, shared, edge) and proposal/agreement sync for rapid convergence',
          'Configuration: `spanning-tree mode rapid-pvst`, `spanning-tree vlan 10 root primary|secondary`, `spanning-tree vlan 10 priority 4096`, `spanning-tree cost`, `spanning-tree port-priority`',
          'Per-VLAN load sharing by making different switches root for different VLANs',
          'Reading `show spanning-tree` and `show spanning-tree vlan 10` (root ID, bridge ID, roles, states, costs, "This bridge is the root")',
        ],
      },
      {
        id: 'stp-protection',
        title: 'PortFast & STP Protection',
        summary: 'PortFast, BPDU Guard, BPDU Filter, Root Guard and Loop Guard.',
        minutes: 40,
        v11: ['2.5.c', '2.5.d'],
        v20: 2,
        focus: [
          'PortFast: edge ports skip listening/learning; `spanning-tree portfast`, `spanning-tree portfast default`; never on switch-to-switch links',
          'BPDU Guard: err-disable an edge port that receives a BPDU; interface and global forms; recovery (`shutdown`/`no shutdown`, `errdisable recovery cause bpduguard`)',
          'BPDU Filter: stop sending/receiving BPDUs; global vs interface behavior differences and risks',
          'Root Guard: prevent a port from becoming root port; root-inconsistent state',
          'Loop Guard: prevent alternate/root ports becoming designated on BPDU loss (unidirectional links); loop-inconsistent',
          'Where each feature goes in a campus design; verification with `show spanning-tree interface detail`, `show interfaces status err-disabled`',
        ],
      },
    ],
  },
  {
    id: 'routing',
    title: 'IP Routing',
    description: 'Reading routing tables, how routers choose paths, and static routing for IPv4 and IPv6.',
    lessons: [
      {
        id: 'routing-table',
        title: 'The Routing Table',
        summary: 'Route codes, prefix, mask, next hop, administrative distance, metric and gateway of last resort.',
        minutes: 45,
        v11: ['3.1', '3.1.a', '3.1.b', '3.1.c', '3.1.d', '3.1.e', '3.1.f', '3.1.g'],
        v20: 3,
        focus: [
          'Reading `show ip route`: codes (C, L, S, O, O IA, O E2, D, R, B, *), prefix/mask, [AD/metric], via next hop, age, exit interface',
          'Connected and local (/32) routes created by up/up interfaces with IP addresses',
          'Administrative distance table: connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, IS-IS 115, RIP 120, external EIGRP 170, iBGP 200, unusable 255',
          'Metrics per protocol (OSPF cost, RIP hop count, EIGRP composite) — compare only within the same protocol',
          'Gateway of last resort and default route (0.0.0.0/0) display',
          'Reading `show ipv6 route` codes (C, L, S, O, ND)',
        ],
      },
      {
        id: 'forwarding-decision',
        title: 'How Routers Forward Packets',
        summary: 'Longest prefix match, administrative distance and metric; the full forwarding process.',
        minutes: 45,
        v11: ['3.2', '3.2.a', '3.2.b', '3.2.c'],
        v20: 3,
        focus: [
          'Routing table construction vs packet forwarding lookups',
          'Longest prefix match: the most specific matching route always wins, regardless of AD/metric — worked examples',
          'Administrative distance: chooses between different sources for the SAME prefix; metric chooses within a protocol; ECMP',
          'Per-hop forwarding: de-encapsulate frame, check FCS, lookup, decrement TTL, recompute checksum, ARP for next hop, re-encapsulate with new MACs (IP addresses unchanged without NAT)',
          'CEF awareness (FIB and adjacency table) vs process switching',
          'Exam-style scenarios: which route is used for a given destination',
        ],
      },
      {
        id: 'static-routing',
        title: 'IPv4 Static Routing',
        summary: 'Network, host, default and floating static routes; configuration and troubleshooting.',
        minutes: 55,
        v11: ['3.3', '3.3.a', '3.3.b', '3.3.c', '3.3.d'],
        v20: 3,
        focus: [
          '`ip route prefix mask {next-hop | exit-interface | exit-interface next-hop} [AD]`; recursive lookup; fully specified routes',
          'Network route, host route (/32), default route (0.0.0.0 0.0.0.0) and gateway of last resort',
          'Floating static route: higher AD than the primary (e.g. 5 or above OSPF 110) as backup; when it appears in the table',
          'Why exit-interface-only static routes on Ethernet are discouraged (proxy ARP)',
          'Static route not installed: next hop unreachable, exit interface down',
          'Verification: `show ip route static`, `show ip route 10.1.1.0`, ping/traceroute',
          'Troubleshooting asymmetric/missing return routes, wrong masks, wrong next hops',
        ],
      },
      {
        id: 'ipv6-static-routing',
        title: 'IPv6 Static Routing',
        summary: 'IPv6 static, default, host and floating routes; link-local next hops; troubleshooting.',
        minutes: 40,
        v11: ['3.3', '3.3.a', '3.3.b', '3.3.c', '3.3.d'],
        v20: 3,
        focus: [
          '`ipv6 unicast-routing` prerequisite',
          '`ipv6 route prefix/len {next-hop | exit-interface [next-hop]} [AD]`; default route ::/0; host route /128; floating static',
          'Link-local next hop requires the exit interface (fully specified)',
          'Verification with `show ipv6 route`, `ping ipv6`, `traceroute`',
          'Troubleshooting IPv6 static routes: missing unicast-routing, wrong prefix length, link-local without interface',
        ],
      },
    ],
  },
  {
    id: 'ospf',
    title: 'OSPF & First Hop Redundancy',
    description: 'Single-area OSPFv2 and OSPFv3, adjacencies, DR/BDR, and FHRPs like HSRP and VRRP.',
    lessons: [
      {
        id: 'ospf-concepts',
        title: 'OSPF Concepts',
        summary: 'Link-state routing, LSAs, the LSDB, SPF, areas, router IDs, neighbor states and cost.',
        minutes: 55,
        v11: ['3.4', '3.4.a', '3.4.d'],
        v20: 3,
        focus: [
          'Distance vector vs link state; IGP vs EGP; OSPF is an open standard link-state IGP, IP protocol 89',
          'LSAs, LSDB, Dijkstra SPF; Type 1 (router) and Type 2 (network) LSAs; flooding to 224.0.0.5 / 224.0.0.6',
          'Areas and backbone area 0; ABR/ASBR/internal/backbone routers; single-area focus',
          'Router ID selection: `router-id` command > highest loopback IP > highest active interface IP; needs `clear ip ospf process` to change',
          'Hello packet contents and timers (10/40 broadcast & p2p); neighbor states Down, Init, 2-Way, ExStart, Exchange, Loading, Full',
          'Cost = reference bandwidth (default 100 Mbps) / interface bandwidth; `auto-cost reference-bandwidth`; `ip ospf cost`; `bandwidth` command',
        ],
      },
      {
        id: 'ospf-config',
        title: 'Configuring Single-Area OSPFv2',
        summary: 'network statements, interface mode, passive interfaces, default route origination, verification.',
        minutes: 60,
        v11: ['3.4', '3.4.a', '3.4.d'],
        v20: 3,
        focus: [
          '`router ospf <pid>` (process ID is locally significant), `network <addr> <wildcard> area <n>` matching logic',
          'Interface configuration: `ip ospf <pid> area <n>`',
          '`passive-interface` and `passive-interface default` + `no passive-interface`',
          '`default-information originate` to advertise a default route (O*E2)',
          '`auto-cost reference-bandwidth 10000` consistency; `maximum-paths` and ECMP',
          'Verification: `show ip ospf neighbor`, `show ip ospf interface [brief]`, `show ip protocols`, `show ip route ospf`, `show ip ospf database`',
        ],
      },
      {
        id: 'ospf-network-types',
        title: 'OSPF Network Types, DR/BDR & Adjacency Troubleshooting',
        summary: 'Point-to-point vs broadcast networks, DR/BDR election, and why neighbors fail to form.',
        minutes: 60,
        v11: ['3.4.a', '3.4.b', '3.4.c', '3.4.d'],
        v20: 3,
        focus: [
          'Broadcast network type (Ethernet default): DR/BDR election by highest priority (default 1, 0 = never), then highest RID; non-preemptive',
          'DROTHERs: FULL with DR/BDR, 2-WAY with each other; multicast 224.0.0.5 (AllSPFRouters) and 224.0.0.6 (AllDRouters)',
          'Point-to-point network type: no DR/BDR; `ip ospf network point-to-point` on Ethernet links; serial default',
          '`ip ospf priority`; reading `show ip ospf neighbor` (FULL/DR, FULL/BDR, 2WAY/DROTHER, FULL/ -)',
          'Adjacency requirements: same subnet/mask, area, hello/dead timers, authentication, MTU, network type compatibility, unique RIDs, not passive',
          'Troubleshooting scenarios and the symptoms of each mismatch (stuck in INIT/EXSTART, no neighbor)',
        ],
      },
      {
        id: 'ospfv3',
        title: 'OSPFv3 for IPv6',
        summary: 'Running OSPF for IPv6: configuration, link-local neighbors and verification.',
        minutes: 35,
        v20: 3,
        focus: [
          'OSPFv3 vs OSPFv2: runs per link, uses link-local addresses for neighbors, multicast FF02::5/FF02::6, 32-bit router ID still required',
          '`ipv6 unicast-routing`, `ipv6 router ospf 1`, `router-id 1.1.1.1`, interface `ipv6 ospf 1 area 0`',
          'Passive interfaces and default route origination in OSPFv3',
          'Verification: `show ipv6 ospf neighbor`, `show ipv6 ospf interface brief`, `show ipv6 route ospf`',
          'Troubleshooting: missing router ID when no IPv4 address exists, area mismatch',
        ],
      },
      {
        id: 'fhrp',
        title: 'First Hop Redundancy (HSRP, VRRP, GLBP)',
        summary: 'Default gateway redundancy with virtual IPs; interpreting HSRP and VRRP status.',
        minutes: 45,
        v11: ['3.5'],
        v20: 3,
        focus: [
          'Problem: single default gateway failure; FHRP concept of virtual IP and virtual MAC shared by routers',
          'HSRP (Cisco): active/standby, priority (default 100), preempt (off by default), hello 3 s/hold 10 s, v1 vs v2, virtual MAC 0000.0c07.acXX (v1) / 0000.0c9f.fXXX (v2), multicast 224.0.0.2 / 224.0.0.102',
          'VRRP (IEEE/RFC 5798): master/backup, priority 100, preempt on by default, virtual MAC 0000.5e00.01XX, can use a real interface IP',
          'GLBP (Cisco): AVG/AVF, load balancing across gateways',
          'Configuration: `standby 1 ip 10.1.1.254`, `standby 1 priority 110`, `standby 1 preempt`; `vrrp 1 ip ...`',
          'Interpreting `show standby [brief]` and `show vrrp [brief]`: state, active/standby router, virtual IP, priority',
        ],
      },
    ],
  },
  {
    id: 'wireless',
    title: 'Wireless LANs',
    description: 'RF principles, wireless architectures, WLC infrastructure, security and GUI configuration.',
    lessons: [
      {
        id: 'wireless-principles',
        title: 'Wireless Principles',
        summary: 'RF basics, bands and channels, SSIDs and BSS/ESS, interference and channel planning.',
        minutes: 55,
        v11: ['1.11', '1.11.a', '1.11.b', '1.11.c', '1.11.d'],
        v20: 1,
        focus: [
          'RF basics: frequency, wavelength, amplitude, dBm/mW, RSSI, SNR; absorption, reflection, refraction, scattering, diffraction',
          '802.11 standards: a/b/g/n (Wi-Fi 4)/ac (Wi-Fi 5)/ax (Wi-Fi 6/6E)/be (Wi-Fi 7) — bands and max rates',
          '2.4 GHz non-overlapping channels 1, 6, 11 (22/20 MHz); 5 GHz many non-overlapping channels, channel bonding 40/80/160 MHz; 6 GHz',
          'Band and channel selection trade-offs; causes of interference (co-channel, adjacent channel, non-Wi-Fi like microwaves/Bluetooth)',
          'Service sets: IBSS (ad hoc), BSS, BSSID (AP radio MAC), ESS, SSID; roaming; mesh (MBSS); repeater/workgroup bridge/outdoor bridge modes',
          'CSMA/CA, half duplex; 802.11 frame types (management, control, data) and client association (probe, authentication, association)',
          'Encryption overview preview (open, WEP, WPA/WPA2/WPA3)',
        ],
      },
      {
        id: 'wireless-architectures',
        title: 'Cisco Wireless Architectures & AP Modes',
        summary: 'Autonomous, lightweight/CAPWAP, cloud-based and FlexConnect; every AP mode.',
        minutes: 45,
        v11: ['2.6'],
        v20: 2,
        focus: [
          'Autonomous APs: standalone config, SSIDs mapped to VLANs, trunk to AP',
          'Lightweight APs with WLC: split-MAC (real-time functions on AP, management on WLC), CAPWAP control UDP 5246 (encrypted DTLS) and data UDP 5247',
          'Deployment models: centralized (unified), distributed/embedded, cloud-based (Meraki), Mobility Express/EWC awareness',
          'AP modes: local, FlexConnect, monitor, sniffer, rogue detector, SE-Connect, bridge/mesh, flex+bridge',
          'FlexConnect local switching when the WAN to the WLC is down',
        ],
      },
      {
        id: 'wlan-physical-infrastructure',
        title: 'WLAN Physical Infrastructure',
        summary: 'Connecting APs and WLCs: access vs trunk ports, WLC ports and interfaces, LAG.',
        minutes: 35,
        v11: ['2.7'],
        v20: 2,
        focus: [
          'Lightweight AP in local mode → switch access port (traffic tunneled in CAPWAP); FlexConnect/autonomous AP → trunk port for local switching of multiple VLANs',
          'WLC physical ports: service port (out-of-band), distribution system ports (trunk to switch), console, redundancy port',
          'WLC logical interfaces: management, dynamic (map WLANs to VLANs), virtual (e.g. 192.0.2.1 for DHCP relay/web auth), service-port, AP-manager awareness',
          'LAG on the WLC: all distribution ports bundled, EtherChannel mode `on` (no LACP/PAgP) on the switch',
          'PoE for APs and switch power budget',
        ],
      },
      {
        id: 'wireless-security',
        title: 'Wireless Security Protocols',
        summary: 'Open, WEP, WPA, WPA2, WPA3, personal vs enterprise, 802.1X/EAP and encryption.',
        minutes: 45,
        v11: ['5.9'],
        v20: 4,
        focus: [
          'Authentication vs encryption vs integrity for WLANs',
          'Open authentication, WEP weaknesses (RC4, static keys); shared key',
          'WPA (TKIP, MIC), WPA2 (802.11i, AES-CCMP), WPA3 (SAE, GCMP, PMF mandatory, forward secrecy, Enhanced Open/OWE)',
          'Personal (PSK / SAE) vs Enterprise (802.1X with RADIUS); supplicant, authenticator, authentication server',
          'EAP methods: LEAP, EAP-FAST, PEAP, EAP-TLS (certificates on both sides), EAP-TTLS',
          'Comparison table of WPA/WPA2/WPA3 by auth and encryption',
        ],
      },
      {
        id: 'wlc-gui-config',
        title: 'Configuring a WLAN in the WLC GUI',
        summary: 'Creating a WLAN, WPA2-PSK security, QoS profiles and advanced settings in the controller GUI.',
        minutes: 45,
        v11: ['2.9', '5.10'],
        v20: 2,
        focus: [
          'WLC GUI tour: Monitor, WLANs, Controller, Wireless, Security, Management tabs (AireOS) and Catalyst 9800 equivalents (WLAN profile, policy profile, tags)',
          'Creating a WLAN: profile name, SSID, WLAN ID, status enabled, interface/interface group (VLAN) mapping, broadcast SSID',
          'Security tab: Layer 2 security WPA+WPA2, WPA2 policy, AES encryption, PSK auth key management, key format ASCII/HEX; 802.1X with RADIUS servers',
          'QoS tab: Platinum (voice), Gold (video), Silver (best effort, default), Bronze (background)',
          'Advanced tab: allow AAA override, session timeout, client exclusion, DHCP required, FlexConnect local switching, max clients',
          'Creating dynamic interfaces for WLAN-to-VLAN mapping; RADIUS server configuration under Security > AAA',
        ],
      },
    ],
  },
  {
    id: 'ip-services',
    title: 'IP Services',
    description: 'NAT, DHCP, DNS, NTP, SSH, file transfer and QoS — the services that make networks usable.',
    lessons: [
      {
        id: 'nat',
        title: 'Network Address Translation',
        summary: 'Inside/outside local/global, static NAT, dynamic NAT with pools, and PAT.',
        minutes: 60,
        v11: ['4.1'],
        v20: 4,
        focus: [
          'NAT terminology: inside local, inside global, outside local, outside global — with a diagram',
          'Static NAT: `ip nat inside source static 10.1.1.10 203.0.113.10`; allows inbound connections',
          'Dynamic NAT: `ip nat pool NAME start end netmask|prefix-length`, ACL to match inside locals, `ip nat inside source list 1 pool NAME`; pool exhaustion',
          'PAT/overload: `ip nat inside source list 1 interface g0/1 overload` and pool overload; port translation',
          '`ip nat inside` / `ip nat outside` on interfaces; order of operations with routing',
          'Verification & troubleshooting: `show ip nat translations`, `show ip nat statistics`, `clear ip nat translation *`, `debug ip nat`; common mistakes (inside/outside swapped, ACL wrong, no route)',
        ],
      },
      {
        id: 'dhcp',
        title: 'DHCP Server, Client & Relay',
        summary: 'DORA, IOS DHCP server pools, exclusions, DHCP relay with helper addresses, troubleshooting.',
        minutes: 55,
        v11: ['4.3', '4.6'],
        v20: 4,
        focus: [
          'DHCP role and DORA (Discover, Offer, Request, Acknowledgment) with broadcast/unicast behavior, UDP 67/68; lease renewal (T1 50%, T2 87.5%)',
          'IOS DHCP server: `ip dhcp excluded-address`, `ip dhcp pool`, `network`, `default-router`, `dns-server`, `domain-name`, `lease`',
          'DHCP relay: `ip helper-address` on the client-facing interface; giaddr; relay forwards other UDP services (helper default list awareness)',
          'DHCP client on a router interface: `ip address dhcp` (e.g. ISP-facing)',
          'Verification: `show ip dhcp binding`, `show ip dhcp pool`, `show ip dhcp conflict`, `show ip interface` (helper)',
          'Troubleshooting DHCPv4: missing helper, wrong pool network, exclusions, APIPA on client, DHCP snooping blocking',
        ],
      },
      {
        id: 'dns',
        title: 'DNS',
        summary: 'Name resolution, record types, resolver behavior and IOS DNS settings.',
        minutes: 40,
        v11: ['4.3'],
        v20: 4,
        focus: [
          'DNS role; hierarchy (root, TLD, authoritative); recursive vs iterative queries; caching and TTL; UDP/TCP 53',
          'Record types: A, AAAA, CNAME, MX, NS, PTR, SOA, TXT — what each is used for (host, web application and mail access by name)',
          'Client resolution flow; hosts file; `nslookup`, `dig`',
          'IOS: `ip domain-lookup` (default on), `no ip domain-lookup`, `ip name-server`, `ip domain-name`, `ip host`',
          'Diagnosing DNS issues: can ping IP but not name; wrong DNS server; missing/incorrect records',
        ],
      },
      {
        id: 'ntp',
        title: 'NTP',
        summary: 'Why time matters, NTP client/server/peer modes, stratum, configuration and verification.',
        minutes: 35,
        v11: ['4.2'],
        v20: 4,
        focus: [
          'Why accurate time matters: logs, certificates, AAA, troubleshooting correlation',
          'NTP UDP 123; stratum levels (0 = reference clock, 1 = directly connected, up to 15; 16 = unsynchronized)',
          'Modes: server, client, symmetric active (peer), broadcast; `ntp server`, `ntp master [stratum]`, `ntp peer`, `ntp source`',
          'Authentication awareness: `ntp authenticate`, `ntp authentication-key`, `ntp trusted-key`',
          'Clock commands: `clock set`, `clock timezone`, `clock summer-time`; `show clock detail`',
          'Verification: `show ntp status`, `show ntp associations` (* sys.peer)',
        ],
      },
      {
        id: 'snmp',
        title: 'SNMP',
        summary: 'Managers and agents, MIBs and OIDs, Get/Set/Trap/Inform, and SNMP versions.',
        minutes: 35,
        v11: ['4.4'],
        v20: 5,
        focus: [
          'SNMP components: NMS/manager, agent, MIB, OID tree',
          'Operations: Get, GetNext, GetBulk, Set, Trap (unacknowledged), Inform (acknowledged); UDP 161 (agent) and 162 (traps)',
          'Versions: v1, v2c (community strings, RO/RW, GetBulk, Inform), v3 (users, noAuthNoPriv/authNoPriv/authPriv)',
          'IOS awareness: `snmp-server community`, `snmp-server location/contact`, `snmp-server host`, `snmp-server enable traps`, v3 groups/users',
          'SNMP vs streaming telemetry and syslog in operations',
        ],
      },
      {
        id: 'syslog',
        title: 'Syslog & Logging',
        summary: 'Syslog message format, facilities, the eight severity levels and logging destinations.',
        minutes: 35,
        v11: ['4.5'],
        v20: 5,
        focus: [
          'Syslog message format: timestamp, facility, severity, mnemonic, description (e.g. %LINEPROTO-5-UPDOWN)',
          'Severity levels 0–7: Emergency, Alert, Critical, Error, Warning, Notification, Informational, Debugging (mnemonics); lower number = more severe',
          'Logging destinations: console, monitor (VTY with `terminal monitor`), buffer, syslog server (UDP 514)',
          'Commands: `logging host`, `logging trap <level>`, `logging console <level>`, `logging buffered`, `service timestamps log datetime msec`, `service sequence-numbers`, `show logging`',
          'Level selection includes that level and all more-severe levels; debug output risks',
        ],
      },
      {
        id: 'qos',
        title: 'Quality of Service',
        summary: 'Per-hop behaviors: classification, marking, queuing, congestion avoidance, policing and shaping.',
        minutes: 55,
        v11: ['4.7'],
        v20: 4,
        focus: [
          'Why QoS: bandwidth, delay, jitter, loss; voice/video requirements (e.g. voice ≤150 ms one-way, ≤30 ms jitter, ≤1% loss)',
          'Classification and marking: ACLs/NBAR; CoS (802.1Q PCP, 3 bits), IP Precedence, DSCP (6 bits); EF (46), AF classes (AFxy drop precedence), CS selectors; trust boundary at phone/access switch',
          'Queuing: FIFO, round robin, CBWFQ, LLQ (priority queue for voice with policing); tail drop',
          'Congestion avoidance: RED/WRED, TCP global synchronization',
          'Policing (drop/re-mark, no delay) vs shaping (buffer/delay, usually at WAN edge); token bucket concept',
          'QoS models: best effort, IntServ (RSVP), DiffServ',
        ],
      },
      {
        id: 'ssh-remote-access',
        title: 'SSH & Remote Device Access',
        summary: 'Configuring SSH on IOS, VTY lines, and why Telnet should be disabled.',
        minutes: 40,
        v11: ['4.8'],
        v20: 4,
        focus: [
          'Telnet (TCP 23, cleartext) vs SSH (TCP 22, encrypted); SSHv2',
          'SSH prerequisites and steps: hostname (not default), `ip domain-name`, `crypto key generate rsa modulus 2048` (≥768 for SSHv2), `username admin secret ...`, `ip ssh version 2`',
          'VTY config: `line vty 0 15`, `login local`, `transport input ssh`, `exec-timeout`, `access-class` to restrict sources',
          'Verification: `show ip ssh`, `show ssh`, `show users`; connecting with `ssh -l user host`',
          'Switch remote management: SVI IP + default gateway required',
        ],
      },
      {
        id: 'tftp-ftp',
        title: 'TFTP, FTP & the IOS File System',
        summary: 'File transfer protocols, IOS file systems, copying images and configurations.',
        minutes: 30,
        v11: ['4.9'],
        v20: 4,
        focus: [
          'TFTP: UDP 69, no authentication, simple, small; FTP: TCP 20/21, authentication, active vs passive modes; SFTP/SCP secure alternatives',
          'IOS file systems: flash:, nvram:, usbflash:, tftp:, ftp:; `dir`, `show flash`, `show file systems`',
          '`copy tftp: flash:`, `copy running-config tftp:`, `ip ftp username/password`, `boot system flash:<image>`',
          'IOS image upgrade workflow and verifying with `show version`; MD5 verify awareness (`verify /md5`)',
        ],
      },
    ],
  },
  {
    id: 'security',
    title: 'Security Fundamentals',
    description: 'Threats and defenses, device hardening, AAA, VPNs, ACLs and Layer 2 security.',
    lessons: [
      {
        id: 'security-concepts',
        title: 'Security Concepts & Threats',
        summary: 'Threats, vulnerabilities, exploits and mitigations; common attack types.',
        minutes: 45,
        v11: ['5.1'],
        v20: 4,
        focus: [
          'Definitions: asset, vulnerability, threat, exploit, risk, mitigation; CIA triad',
          'Attacks: reconnaissance, DoS/DDoS, reflection and amplification, spoofing (IP/MAC/DHCP), MITM (ARP poisoning), malware (virus, worm, trojan, ransomware), password attacks (dictionary, brute force), social engineering (phishing, spear phishing, whaling, vishing, smishing, pretexting, tailgating)',
          'Mitigation techniques mapped to attacks (patching, ACLs, IPS, AAA, L2 security, encryption, training)',
          'Firewalls, IPS, endpoint security, and defense in depth',
        ],
      },
      {
        id: 'security-program',
        title: 'Security Program Elements',
        summary: 'User awareness, training, and physical access control.',
        minutes: 25,
        v11: ['5.2'],
        v20: 4,
        focus: [
          'User awareness programs (phishing simulations, policy communication)',
          'User training (formal role-based training)',
          'Physical access control (badges, locks, biometrics, mantraps, securing wiring closets and console ports)',
          'Security policy and its elements',
        ],
      },
      {
        id: 'device-access-control',
        title: 'Device Access Control & Local Passwords',
        summary: 'Securing console, VTY and privileged access with passwords, secrets and local users.',
        minutes: 45,
        v11: ['5.3'],
        v20: 4,
        focus: [
          '`enable password` vs `enable secret` (secret wins); password types 0, 5 (MD5), 7 (weak Vigenère), 8 (PBKDF2-SHA256), 9 (scrypt); `enable algorithm-type`',
          'Line passwords: `line console 0`, `password`, `login`; `login local` with `username NAME secret PASS`; privilege levels',
          '`service password-encryption` (type 7 only obscures)',
          '`exec-timeout`, `login block-for ... attempts ... within ...`, `security passwords min-length`',
          'Banners (`banner motd`, `banner login`) and legal warnings',
          'Verification: reading running-config password lines',
        ],
      },
      {
        id: 'password-policy',
        title: 'Password Policies & Alternatives',
        summary: 'Password management and complexity; MFA, certificates and biometrics.',
        minutes: 25,
        v11: ['5.4'],
        v20: 4,
        focus: [
          'Password policy elements: length, complexity, expiration/rotation guidance (NIST modern view), history, lockout',
          'Password managers and secrets management',
          'Multifactor authentication: something you know/have/are; examples',
          'Digital certificates and PKI basics (CA, public/private keys) as password alternatives',
          'Biometrics: fingerprint, face, iris; false accept/reject awareness',
        ],
      },
      {
        id: 'aaa',
        title: 'AAA, RADIUS, TACACS+ & 802.1X',
        summary: 'Authentication, authorization and accounting; RADIUS vs TACACS+; port-based 802.1X.',
        minutes: 45,
        v11: ['5.8', '2.8'],
        v20: 4,
        focus: [
          'AAA definitions with examples: authentication (who), authorization (what), accounting (what was done)',
          'RADIUS (open standard, UDP 1812/1813, encrypts only password, combines authn+authz, network access) vs TACACS+ (Cisco, TCP 49, encrypts entire payload, separates AAA, device administration)',
          'Cisco ISE as AAA server; local fallback',
          'IOS awareness: `aaa new-model`, `aaa authentication login default group tacacs+ local`, `tacacs server`, `radius server`',
          '802.1X roles: supplicant, authenticator (switch/WLC), authentication server (RADIUS); EAPoL; MAB and web auth awareness',
        ],
      },
      {
        id: 'device-management-access',
        title: 'Device Management Access',
        summary: 'Console, Telnet, SSH, HTTP/HTTPS, AAA-based and cloud-managed access to network devices.',
        minutes: 30,
        v11: ['2.8'],
        v20: 4,
        focus: [
          'In-band vs out-of-band management; console and AUX; management VLANs',
          'Telnet vs SSH; HTTP vs HTTPS web GUI (`ip http server`, `ip http secure-server`)',
          'Centralized authentication with TACACS+/RADIUS for administrators',
          'Cloud-managed devices (Meraki dashboard) and controller-managed devices',
          'Best practices: disable unused services, restrict VTY with ACLs, use SSHv2 and HTTPS only',
        ],
      },
      {
        id: 'acl-concepts',
        title: 'ACL Fundamentals & Standard ACLs',
        summary: 'ACL logic, wildcard masks, standard numbered and named ACLs and placement.',
        minutes: 55,
        v11: ['5.6'],
        v20: 4,
        focus: [
          'ACL uses (filtering, NAT, QoS classification); inbound vs outbound; one ACL per interface per direction per protocol',
          'Top-down first-match processing and the implicit deny any at the end',
          'Wildcard masks: 0 = match, 1 = ignore; `host` and `any` keywords; computing wildcards from subnet masks (255.255.255.255 − mask)',
          'Standard ACLs 1–99 and 1300–1999: match source only; place close to the destination',
          'Numbered vs named ACLs (`ip access-list standard NAME`); applying with `ip access-group NAME in|out`',
          'Verification: `show access-lists` (hit counters), `show ip interface`',
        ],
      },
      {
        id: 'extended-acls',
        title: 'Extended & Named ACLs',
        summary: 'Matching protocol, source, destination and ports; editing with sequence numbers; VTY ACLs.',
        minutes: 60,
        v11: ['5.6'],
        v20: 4,
        focus: [
          'Extended ACLs 100–199 and 2000–2699: protocol (ip, tcp, udp, icmp, ospf...), source, destination, ports; place close to the source',
          'Port operators eq, neq, gt, lt, range; source vs destination port position; `established`',
          'Named ACL editing: sequence numbers, inserting/deleting entries, `ip access-list resequence`',
          'Restricting VTY access with `access-class` on `line vty`',
          'Designing ACLs from requirements and predicting the effect of an ACL on specific traffic',
          'Common mistakes: wrong direction/interface, order of entries, forgetting to permit other traffic, blocking routing protocols',
          'IPv6 ACL awareness (`ipv6 traffic-filter`, implicit permit for ND)',
        ],
      },
      {
        id: 'l2-security',
        title: 'Layer 2 Security',
        summary: 'Port security, DHCP snooping, dynamic ARP inspection, storm control and RA guard.',
        minutes: 60,
        v11: ['5.7'],
        v20: 4,
        focus: [
          'Port security: `switchport port-security`, maximum, static and sticky MACs, violation modes protect/restrict/shutdown (default), err-disabled recovery; `show port-security interface`',
          'DHCP snooping: trusted vs untrusted ports, binding table, rogue DHCP server prevention, `ip dhcp snooping`, `ip dhcp snooping vlan`, `ip dhcp snooping trust`, rate limiting, option 82 (`no ip dhcp snooping information option`)',
          'Dynamic ARP Inspection: uses DHCP snooping bindings, `ip arp inspection vlan`, `ip arp inspection trust`, ARP ACLs for static hosts, validation options',
          'Storm control: `storm-control broadcast level`, actions (shutdown, trap)',
          'IPv6 RA guard: blocking rogue router advertisements on host ports',
          'Other attacks: MAC flooding, VLAN hopping (switch spoofing and double tagging) and mitigations (disable DTP, unused native VLAN)',
        ],
      },
      {
        id: 'vpns',
        title: 'IPsec VPNs',
        summary: 'Site-to-site and remote-access VPNs, IPsec protocols and modes, GRE over IPsec, TLS VPNs.',
        minutes: 45,
        v11: ['5.5'],
        v20: 4,
        focus: [
          'VPN goals: confidentiality, integrity, authentication, anti-replay',
          'Site-to-site IPsec VPN (VPN gateways, transparent to hosts) vs remote-access VPN (client software, TLS/SSL or IPsec; Cisco Secure Client/AnyConnect)',
          'IPsec components: IKE (IKEv1/IKEv2), ESP (encryption + integrity, IP protocol 50) vs AH (integrity only, protocol 51); tunnel mode vs transport mode',
          'Encryption (AES), hashing (SHA), key exchange (Diffie-Hellman), authentication (PSK, certificates)',
          'GRE over IPsec (multicast/routing protocol support), DMVPN awareness',
          'Clientless (browser) TLS VPN vs full-tunnel/split-tunnel client VPN',
        ],
      },
    ],
  },
  {
    id: 'virtualization-cloud',
    title: 'Virtualization & Cloud',
    description: 'Hypervisors, VMs, containers, VRFs and cloud computing models.',
    lessons: [
      {
        id: 'virtualization',
        title: 'Virtualization: VMs, Containers & VRFs',
        summary: 'Server virtualization, hypervisor types, virtual switching, containers and VRFs.',
        minutes: 45,
        v11: ['1.12'],
        v20: 1,
        focus: [
          'Server virtualization benefits; physical host, VMs, virtual NICs',
          'Type 1 (bare-metal: ESXi, Hyper-V, KVM) vs Type 2 (hosted: VirtualBox, Workstation) hypervisors',
          'Virtual switches (vSwitch) and how VM traffic reaches the physical network (trunks to hosts)',
          'Containers vs VMs: shared kernel, lightweight, images; Docker and Kubernetes awareness',
          'VRFs: multiple routing tables on one router, overlapping IP space, `vrf definition`, `vrf forwarding` awareness; VRF-lite',
          'NFV (virtual routers, firewalls) awareness',
        ],
      },
      {
        id: 'cloud-concepts',
        title: 'Cloud Computing',
        summary: 'Cloud characteristics, service and deployment models, and connecting to the cloud.',
        minutes: 35,
        v11: ['1.2.f'],
        v20: 1,
        focus: [
          'NIST cloud characteristics: on-demand self-service, broad network access, resource pooling, rapid elasticity, measured service',
          'Service models: IaaS, PaaS, SaaS (with examples) and responsibility split',
          'Deployment models: public, private, hybrid, community; multicloud',
          'Connecting to the cloud: Internet, Internet VPN, private WAN (MPLS), intercloud exchange/direct connect',
          'On-premises vs cloud trade-offs (capex vs opex, control, scalability, latency)',
        ],
      },
    ],
  },
  {
    id: 'automation',
    title: 'Automation, Programmability & AI',
    description: 'Controller-based networking, APIs, JSON, configuration management and AI in network operations.',
    lessons: [
      {
        id: 'automation-impact',
        title: 'How Automation Changes Network Management',
        summary: 'Why automate, what changes for network engineers, and the planes of a network device.',
        minutes: 30,
        v11: ['6.1'],
        v20: 5,
        focus: [
          'Problems with manual per-device CLI: time, errors, inconsistency, config drift, scale',
          'Benefits: consistency, speed, fewer errors, compliance, faster troubleshooting with telemetry',
          'Data, control and management planes explained with examples',
          'Automation tools overview: scripts (Python), controllers, config management tools, APIs',
          'Intent-based networking concept',
        ],
      },
      {
        id: 'network-management-approaches',
        title: 'Network Management Approaches',
        summary: 'Device-based, automation-based, cloud-based and controller-based network management.',
        minutes: 30,
        v11: ['6.2'],
        v20: 1,
        focus: [
          'Device-based (box-by-box CLI/GUI) management',
          'Automation-based management (scripts, Ansible, Terraform, IaC pipelines)',
          'Cloud-based management (Meraki dashboard: devices phone home to the cloud)',
          'Controller-based management (Catalyst Center, WLC, SD-WAN Manager)',
          'Comparison of the four approaches: scale, skills, visibility, failure domains',
        ],
      },
      {
        id: 'controller-networking',
        title: 'Controller-Based Networking & SDN',
        summary: 'Traditional vs controller-based networks, SDN architecture, overlay/underlay/fabric and APIs.',
        minutes: 50,
        v11: ['6.2', '6.3', '6.3.a', '6.3.b'],
        v20: 5,
        focus: [
          'Traditional distributed control plane vs centralized controller; separation of control and data planes',
          'SDN architecture: application layer, control layer (controller), infrastructure layer',
          'Northbound APIs (REST to apps) vs southbound APIs/protocols (NETCONF, RESTCONF, OpenFlow, OpFlex, SSH/SNMP, CLI)',
          'Overlay, underlay and fabric; VXLAN and LISP in Cisco SD-Access; fabric edge/border/control-plane nodes',
          'Cisco Catalyst Center (DNA Center) capabilities vs traditional management: intent, assurance, PnP, templates, software image management',
          'Cisco SD-WAN (vManage/SD-WAN Manager, vSmart/controller, vBond/validator, WAN edge) awareness',
        ],
      },
      {
        id: 'rest-apis',
        title: 'REST APIs',
        summary: 'REST characteristics, CRUD and HTTP verbs, status codes, authentication and data encoding.',
        minutes: 50,
        v11: ['6.5'],
        v20: 5,
        focus: [
          'API concept; REST constraints: client-server, stateless, cacheable, uniform interface, layered system',
          'CRUD mapped to HTTP verbs: Create=POST, Read=GET, Update=PUT/PATCH, Delete=DELETE',
          'URI structure, query parameters, headers (Content-Type, Accept, Authorization), request/response body',
          'HTTP status codes: 200, 201, 204, 301, 400, 401, 403, 404, 500, 503',
          'Authentication types: HTTP basic, API key, bearer token (e.g. Catalyst Center token), OAuth 2.0',
          'Data encoding: JSON, XML, YAML; model-driven programmability awareness (YANG models, NETCONF over SSH port 830, RESTCONF over HTTPS)',
          'Reading a sample Catalyst Center API call and response',
        ],
      },
      {
        id: 'json',
        title: 'JSON Data',
        summary: 'JSON syntax: objects, arrays, key/value pairs, data types and reading structured output.',
        minutes: 35,
        v11: ['6.7'],
        v20: 5,
        focus: [
          'JSON syntax: objects {}, arrays [], key/value pairs, keys are double-quoted strings, commas, no trailing commas',
          'Value types: string, number, boolean (true/false), null, object, array',
          'Identifying valid vs invalid JSON; counting objects/arrays; nesting',
          'Navigating nested data (e.g. response["response"][0]["hostname"])',
          'JSON vs XML vs YAML side by side',
        ],
      },
      {
        id: 'config-management',
        title: 'Configuration Management: Ansible & Terraform',
        summary: 'Ansible, Terraform, Puppet and Chef capabilities; infrastructure as code.',
        minutes: 40,
        v11: ['6.6'],
        v20: 5,
        focus: [
          'Configuration drift and configuration management goals; infrastructure as code (IaC); version control (Git)',
          'Ansible: agentless, push model, SSH/NETCONF/API, YAML playbooks, inventory, modules, tasks, idempotency; control node',
          'Terraform: declarative IaC, HCL, providers, plan/apply/state, provisioning focus',
          'Puppet and Chef awareness: agent-based, pull model, manifests (Puppet DSL) vs cookbooks/recipes (Ruby)',
          'Comparison table of the tools; reading a simple playbook or Terraform file',
        ],
      },
      {
        id: 'ai-ml-netops',
        title: 'AI & Machine Learning in Network Operations',
        summary: 'Predictive and generative AI, ML basics, AIOps use cases and prompting AI for network tasks.',
        minutes: 45,
        v11: ['6.4'],
        v20: 5,
        focus: [
          'AI vs ML vs deep learning; supervised, unsupervised and reinforcement learning',
          'Predictive AI (forecasting, anomaly detection, capacity planning, failure prediction) vs generative AI (LLMs creating text, configs, summaries)',
          'Network use cases: AIOps, Catalyst Center AI Network Analytics, baselining, root cause analysis, AI assistants',
          'Risks: hallucinations, data privacy, verification of generated configs, human in the loop',
          'Prompt components for network operations: persona, instructions/task, context, data classification (what may be shared), output format; good vs bad prompts',
        ],
      },
    ],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    description: 'A structured method and the tools that find faults fast: show commands, ping, traceroute, captures.',
    lessons: [
      {
        id: 'troubleshooting-methodology',
        title: 'Troubleshooting Methodology & Tools',
        summary: 'Structured troubleshooting, extended ping, traceroute, show logging and packet captures.',
        minutes: 55,
        v11: ['1.4', '1.10', '3.3'],
        v20: 2,
        focus: [
          'Structured methods: top-down, bottom-up, divide-and-conquer, follow-the-path, compare configs, swap components',
          'Ping and extended ping (source interface, repeat count, size, DF bit); interpreting ! . U Q M ? & codes',
          'Traceroute mechanics (TTL increments, ICMP time exceeded) and reading output with * * *',
          'Key show commands by layer and `show logging`; `debug` with care',
          'Reading packet capture (Wireshark) output: Ethernet/IP/TCP fields, ARP, DHCP, DNS, TCP handshake, retransmissions',
          'End-to-end troubleshooting scenarios combining L1–L4 checks',
        ],
      },
    ],
  },
];

/** Flat list of all lessons in learning order. */
export const LESSONS: LessonMeta[] = MODULES.flatMap((m) => m.lessons);

export const LESSON_BY_ID: Record<string, LessonMeta & { moduleId: string }> = Object.fromEntries(
  MODULES.flatMap((m) => m.lessons.map((l) => [l.id, { ...l, moduleId: m.id }])),
);

/** Domain number a lesson belongs to for a given exam version (undefined if not on that exam). */
export function lessonDomain(lesson: LessonMeta, version: ExamVersion): number | undefined {
  if (version === 'v2.0') return lesson.v20;
  if (!lesson.v11 || lesson.v11.length === 0) return undefined;
  return Number(lesson.v11[0].split('.')[0]);
}

export function lessonInVersion(lesson: LessonMeta, version: ExamVersion): boolean {
  return lessonDomain(lesson, version) !== undefined;
}
