import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-l3-switch-svis',
  title: 'Layer 3 Switch: SVIs and Routed Ports',
  summary: 'Turn a Catalyst 3650 into the routing core: SVIs for two VLANs, a trunk to the access switch, a routed port toward R1 and a default route to the Internet edge.',
  difficulty: 2,
  minutes: 45,
  lessons: ['inter-vlan-routing', 'vlans'],
  scenario:
    'The Lakeside clinic has outgrown router-on-a-stick. A Catalyst 3650 (**CORE**) is now the routing core and has to route between **STAFF** (VLAN 10, 10.10.10.0/24) and **DEVICES** (VLAN 20, 10.10.20.0/24) with switched virtual interfaces (SVIs). The access switch **ASW1** connects the users and uplinks to CORE.\n\n' +
    'R1 is the edge router and is already finished: G0/0/0 is 10.0.0.1/30, Loopback0 (198.51.100.1) stands in for the Internet, and a static route sends 10.10.0.0/16 back to CORE (10.0.0.2). PC1 (STAFF) and PC2 (DEVICES) are addressed and use their SVI address as default gateway. CORE and ASW1 still have factory settings.\n\n' +
    'Build the Layer 2 part first (VLANs, access ports and a trunk between CORE G1/0/1 and ASW1 G0/1), then the Layer 3 part: enable routing on CORE, create the SVIs, turn G1/0/24 into a routed port toward R1 and add a default route.',
  devices: [
    {
      id: 'R1',
      model: 'isr4321',
      x: 1,
      y: 3.5,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to CORE G1/0/24',
        ' ip address 10.0.0.1 255.255.255.252',
        ' no shutdown',
        'interface Loopback0',
        ' description Internet (simulated)',
        ' ip address 198.51.100.1 255.255.255.255',
        'ip route 10.10.0.0 255.255.0.0 10.0.0.2',
      ].join('\n'),
    },
    { id: 'CORE', model: 'c3650', x: 4.5, y: 3.5 },
    { id: 'ASW1', model: 'c2960', x: 8, y: 3.5 },
    { id: 'PC1', model: 'pc', x: 11, y: 1.5, host: { ip: '10.10.10.11', mask: '255.255.255.0', gateway: '10.10.10.1' } },
    { id: 'PC2', model: 'pc', x: 11, y: 5.5, host: { ip: '10.10.20.12', mask: '255.255.255.0', gateway: '10.10.20.1' } },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'CORE:g1/0/24' },
    { a: 'CORE:g1/0/1', b: 'ASW1:g0/1' },
    { a: 'ASW1:fa0/1', b: 'PC1:fa0' },
    { a: 'ASW1:fa0/2', b: 'PC2:fa0' },
  ],
  tasks: [
    {
      id: 'vlans',
      title: 'Create VLAN 10 **STAFF** and VLAN 20 **DEVICES** on both CORE and ASW1',
      details: 'VLANs are local to each switch (there is no VTP here), so they must exist on the core and on the access switch. An SVI only comes up when its VLAN exists on that switch.',
      hint: '`vlan 10` then `name STAFF`; verify with `show vlan brief` on both switches.',
      checks: [
        { type: 'vlan', device: 'CORE', vlan: 10, name: 'STAFF' },
        { type: 'vlan', device: 'CORE', vlan: 20, name: 'DEVICES' },
        { type: 'vlan', device: 'ASW1', vlan: 10, name: 'STAFF' },
        { type: 'vlan', device: 'ASW1', vlan: 20, name: 'DEVICES' },
      ],
    },
    {
      id: 'access-ports',
      title: 'Make ASW1 Fa0/1 (PC1) an access port in VLAN 10 and Fa0/2 (PC2) an access port in VLAN 20',
      details: 'Use `switchport mode access` and `switchport access vlan <id>` on each port.',
      hint: '`interface fa0/1` → `switchport mode access` → `switchport access vlan 10`',
      checks: [
        { type: 'switchport', device: 'ASW1', iface: 'Fa0/1', mode: 'access', accessVlan: 10 },
        { type: 'switchport', device: 'ASW1', iface: 'Fa0/2', mode: 'access', accessVlan: 20 },
      ],
    },
    {
      id: 'trunk',
      title: 'Build a static 802.1Q trunk between CORE G1/0/1 and ASW1 G0/1 that carries only VLANs 10 and 20',
      details: 'Configure `switchport mode trunk` and `switchport trunk allowed vlan 10,20` on both ends. Verify with `show interfaces trunk`.',
      hint: 'If an SVI later stays down/down, check that the VLAN is on the trunk and that the trunk is up.',
      checks: [
        { type: 'switchport', device: 'CORE', iface: 'Gi1/0/1', mode: 'trunk', allowed: '10,20' },
        { type: 'switchport', device: 'ASW1', iface: 'Gi0/1', mode: 'trunk', allowed: '10,20' },
      ],
    },
    {
      id: 'svis',
      title: 'Enable IP routing on CORE and create interface Vlan10 (10.10.10.1/24) and interface Vlan20 (10.10.20.1/24), both up',
      details: 'A multilayer switch does not route until you enter `ip routing` in global configuration mode. An SVI is created by `interface vlan <id>`, needs `no shutdown`, and is only up/up when its VLAN exists and at least one port in that VLAN is up. Verify with `show ip interface brief` and `show ip route`.',
      hint: '`ip routing`, then `interface vlan 10` → `ip address 10.10.10.1 255.255.255.0` → `no shutdown`',
      checks: [
        { type: 'interface', device: 'CORE', iface: 'Vlan10', ip: '10.10.10.1', mask: '255.255.255.0', status: 'up' },
        { type: 'interface', device: 'CORE', iface: 'Vlan20', ip: '10.10.20.1', mask: '255.255.255.0', status: 'up' },
        { type: 'route', device: 'CORE', prefix: '10.10.10.0/24', source: 'C' },
        { type: 'route', device: 'CORE', prefix: '10.10.20.0/24', source: 'C' },
      ],
    },
    {
      id: 'routed-port',
      title: 'Convert CORE G1/0/24 into a routed port with the address 10.0.0.2/30 toward R1 (10.0.0.1)',
      details: 'A switch port becomes a Layer 3 interface with `no switchport`; only then does `ip address` work on it. Test the link with a ping to R1.',
      hint: '`interface g1/0/24` → `no switchport` → `ip address 10.0.0.2 255.255.255.252`',
      checks: [
        { type: 'config', device: 'CORE', section: 'interface GigabitEthernet1/0/24', pattern: '^ no switchport$' },
        { type: 'interface', device: 'CORE', iface: 'Gi1/0/24', ip: '10.0.0.2', mask: '255.255.255.252', status: 'up' },
        { type: 'ping', from: 'CORE', to: '10.0.0.1' },
      ],
    },
    {
      id: 'default-route',
      title: 'Add a default route on CORE that points to R1 (10.0.0.1)',
      details: 'CORE only knows its connected networks. `ip route 0.0.0.0 0.0.0.0 <next-hop>` sends everything else to the edge router. It appears in `show ip route` as `S*`.',
      hint: '`ip route 0.0.0.0 0.0.0.0 10.0.0.1`',
      checks: [{ type: 'route', device: 'CORE', prefix: '0.0.0.0/0', source: 'S*', nextHop: '10.0.0.1' }],
    },
    {
      id: 'verify',
      title: 'Verify end-to-end routing: PC1 and PC2 reach each other through the SVIs and both reach the Internet address 198.51.100.1',
      details: 'The path to the Internet crosses the trunk, the SVI, the routed port, R1 and back, using R1\'s static route to 10.10.0.0/16. If a ping fails, check each hop in order: PC gateway, SVI state, routed port, default route.',
      hint: 'Ping the SVI gateway first, then the other VLAN, then 198.51.100.1.',
      checks: [
        { type: 'ping', from: 'PC1', to: '10.10.20.12' },
        { type: 'ping', from: 'PC2', to: '10.10.10.11' },
        { type: 'ping', from: 'PC1', to: '198.51.100.1' },
        { type: 'ping', from: 'PC2', to: '198.51.100.1' },
      ],
    },
  ],
  solution: {
    CORE: [
      'enable',
      'configure terminal',
      'ip routing',
      'vlan 10',
      ' name STAFF',
      'vlan 20',
      ' name DEVICES',
      ' exit',
      'interface g1/0/1',
      ' description Trunk to ASW1 G0/1',
      ' switchport mode trunk',
      ' switchport trunk allowed vlan 10,20',
      'interface vlan 10',
      ' ip address 10.10.10.1 255.255.255.0',
      ' no shutdown',
      'interface vlan 20',
      ' ip address 10.10.20.1 255.255.255.0',
      ' no shutdown',
      'interface g1/0/24',
      ' description Routed link to R1',
      ' no switchport',
      ' ip address 10.0.0.2 255.255.255.252',
      ' exit',
      'ip route 0.0.0.0 0.0.0.0 10.0.0.1',
      'end',
    ].join('\n'),
    ASW1: [
      'enable',
      'configure terminal',
      'vlan 10',
      ' name STAFF',
      'vlan 20',
      ' name DEVICES',
      ' exit',
      'interface fa0/1',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface fa0/2',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface g0/1',
      ' description Trunk to CORE G1/0/1',
      ' switchport mode trunk',
      ' switchport trunk allowed vlan 10,20',
      ' end',
    ].join('\n'),
  },
};

export default lab;
