import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-vlans-trunking',
  title: 'VLANs and 802.1Q Trunking',
  summary: 'Create and name VLANs on two switches, assign access ports, and build a hardened 802.1Q trunk with a dedicated native VLAN.',
  difficulty: 2,
  minutes: 35,
  lessons: ['vlans', 'trunking'],
  scenario:
    'Sales and Engineering share two access switches. Today every port is still in VLAN 1, so both departments sit in one broadcast domain.\n' +
    'Segment them: **VLAN 10 SALES** (192.168.10.0/24) and **VLAN 20 ENGINEERING** (192.168.20.0/24). The uplink between SW1 and SW2 (G0/1) must become an 802.1Q trunk that uses an unused **native VLAN 99 (NATIVE)**, only carries VLANs 10, 20 and 99, and does not negotiate with DTP.\n' +
    'PC addressing is already done: PC1 192.168.10.11 and PC3 192.168.10.13 (Sales), PC2 192.168.20.12 and PC4 192.168.20.14 (Engineering).',
  devices: [
    { id: 'SW1', model: 'c2960', x: 3, y: 2 },
    { id: 'SW2', model: 'c2960', x: 9, y: 2 },
    { id: 'PC1', model: 'pc', x: 1, y: 5, host: { ip: '192.168.10.11', mask: '255.255.255.0' } },
    { id: 'PC2', model: 'pc', x: 4, y: 5, host: { ip: '192.168.20.12', mask: '255.255.255.0' } },
    { id: 'PC3', model: 'pc', x: 8, y: 5, host: { ip: '192.168.10.13', mask: '255.255.255.0' } },
    { id: 'PC4', model: 'pc', x: 11, y: 5, host: { ip: '192.168.20.14', mask: '255.255.255.0' } },
  ],
  links: [
    { a: 'SW1:g0/1', b: 'SW2:g0/1' },
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'SW2:fa0/1', b: 'PC3:fa0' },
    { a: 'SW2:fa0/2', b: 'PC4:fa0' },
  ],
  tasks: [
    {
      id: 'create-vlans',
      title: 'Create VLAN 10 **SALES**, VLAN 20 **ENGINEERING** and VLAN 99 **NATIVE** on both switches',
      details: 'In global configuration mode use `vlan 10` then `name SALES`, and so on. The VLAN is committed when you leave VLAN configuration mode (`exit` or `end`). Verify with `show vlan brief`.',
      hint: '`vlan 10` → `name SALES` → `vlan 20` → `name ENGINEERING` → `vlan 99` → `name NATIVE` → `exit`',
      checks: [
        { type: 'vlan', device: 'SW1', vlan: 10, name: 'SALES' },
        { type: 'vlan', device: 'SW1', vlan: 20, name: 'ENGINEERING' },
        { type: 'vlan', device: 'SW1', vlan: 99, name: 'NATIVE' },
        { type: 'vlan', device: 'SW2', vlan: 10, name: 'SALES' },
        { type: 'vlan', device: 'SW2', vlan: 20, name: 'ENGINEERING' },
        { type: 'vlan', device: 'SW2', vlan: 99, name: 'NATIVE' },
      ],
    },
    {
      id: 'access-ports',
      title: 'Make Fa0/1 an access port in VLAN 10 and Fa0/2 an access port in VLAN 20 on both switches',
      details: 'Hard-code the mode with `switchport mode access` so the ports never negotiate a trunk, then assign the VLAN with `switchport access vlan`. `interface range` saves typing when several ports share a VLAN.',
      hint: '`interface fa0/1` → `switchport mode access` → `switchport access vlan 10`',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Fa0/1', mode: 'access', accessVlan: 10 },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/2', mode: 'access', accessVlan: 20 },
        { type: 'switchport', device: 'SW2', iface: 'Fa0/1', mode: 'access', accessVlan: 10 },
        { type: 'switchport', device: 'SW2', iface: 'Fa0/2', mode: 'access', accessVlan: 20 },
      ],
    },
    {
      id: 'trunk',
      title: 'Turn G0/1 on both switches into a static 802.1Q trunk with native VLAN 99 that allows only VLANs 10, 20 and 99',
      details: 'Use `switchport mode trunk`, `switchport trunk native vlan 99` and `switchport trunk allowed vlan 10,20,99`. The native VLAN must match on both ends or CDP reports a native VLAN mismatch. Check `show interfaces trunk`.',
      hint: '`interface g0/1` → `switchport mode trunk` → `switchport trunk native vlan 99` → `switchport trunk allowed vlan 10,20,99`',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Gi0/1', mode: 'trunk', nativeVlan: 99, allowed: '10,20,99' },
        { type: 'switchport', device: 'SW2', iface: 'Gi0/1', mode: 'trunk', nativeVlan: 99, allowed: '10,20,99' },
        { type: 'show', device: 'SW1', command: 'show interfaces trunk', pattern: '^Gi0/1\\s+on\\s+802\\.1q\\s+trunking\\s+99$' },
      ],
    },
    {
      id: 'nonegotiate',
      title: 'Disable DTP on the trunk ports',
      details: 'A static trunk still sends DTP frames. `switchport nonegotiate` stops them; it is only accepted on ports that are statically set to access or trunk mode.',
      hint: '`interface g0/1` → `switchport nonegotiate`',
      checks: [
        { type: 'config', device: 'SW1', section: 'interface GigabitEthernet0/1', pattern: '^ switchport nonegotiate$' },
        { type: 'config', device: 'SW2', section: 'interface GigabitEthernet0/1', pattern: '^ switchport nonegotiate$' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify that each VLAN reaches across the trunk',
      details: 'From PC1 ping PC3, and from PC2 ping PC4. Then look at `show interfaces trunk` on SW2: VLANs 10, 20 and 99 must be in the spanning-tree forwarding state.',
      hint: 'If a ping fails, compare `show vlan brief` and `show interfaces trunk` on both switches.',
      checks: [
        { type: 'ping', from: 'PC1', to: '192.168.10.13' },
        { type: 'ping', from: 'PC2', to: '192.168.20.14' },
        { type: 'show', device: 'SW2', command: 'show interfaces trunk', pattern: 'not pruned\\s*\\nGi0/1\\s+10,20,99' },
      ],
    },
  ],
  solution: {
    SW1: [
      'enable',
      'configure terminal',
      'vlan 10',
      ' name SALES',
      'vlan 20',
      ' name ENGINEERING',
      'vlan 99',
      ' name NATIVE',
      ' exit',
      'interface fa0/1',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface fa0/2',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface g0/1',
      ' switchport mode trunk',
      ' switchport trunk native vlan 99',
      ' switchport trunk allowed vlan 10,20,99',
      ' switchport nonegotiate',
      ' end',
    ].join('\n'),
    SW2: [
      'enable',
      'configure terminal',
      'vlan 10',
      ' name SALES',
      'vlan 20',
      ' name ENGINEERING',
      'vlan 99',
      ' name NATIVE',
      ' exit',
      'interface range fa0/1',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface fa0/2',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface g0/1',
      ' switchport mode trunk',
      ' switchport trunk native vlan 99',
      ' switchport trunk allowed vlan 10,20,99',
      ' switchport nonegotiate',
      ' end',
    ].join('\n'),
  },
};

export default lab;
