import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-nat-pat',
  title: 'Static NAT, Dynamic NAT and PAT',
  summary: 'Configure the edge router R1 for all three NAT flavours: a static mapping for the web server, a dynamic pool for staff PCs and PAT with overload for the guest LAN.',
  difficulty: 2,
  minutes: 45,
  lessons: ['nat'],
  scenario:
    'The Wizard Corp branch reaches the Internet through edge router R1 and a single ISP link (G0/2, 203.0.113.2/30). Behind R1 are two private networks: the **staff LAN** 10.1.1.0/24 (PC1, PC2 and the web server SRV1 at 10.1.1.10) and the **guest LAN** 10.1.2.0/24 (PC3). Interface addressing and the default route are done, and the ISP router (which you cannot access) already routes the public block **198.51.100.8/29** to R1. R1 does not translate anything yet, so private source addresses die at the ISP.\n\n' +
    'The ISP plan for the public block: **198.51.100.9** is the public address of the web server (static NAT), **198.51.100.10 - 198.51.100.12** form a pool for the staff PCs (dynamic NAT), and the guests get no public address of their own: they share R1\'s outside address **203.0.113.2** through PAT.\n\n' +
    'Configure R1 accordingly. INET (192.0.2.80) stands in for a machine on the Internet: use it to test inbound access, and the PCs to test outbound access.',
  devices: [
    { id: 'SRV1', model: 'server', x: 1, y: 1, host: { ip: '10.1.1.10', mask: '255.255.255.0', gateway: '10.1.1.1' }, services: { http: true } },
    { id: 'SW1', model: 'c2960', x: 2.5, y: 3 },
    {
      id: 'R1',
      model: 'isr2911',
      x: 6,
      y: 3,
      config: [
        'interface GigabitEthernet0/0',
        ' description Staff LAN',
        ' ip address 10.1.1.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description Guest LAN',
        ' ip address 10.1.2.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description Uplink to ISP',
        ' ip address 203.0.113.2 255.255.255.252',
        ' no shutdown',
        'ip route 0.0.0.0 0.0.0.0 203.0.113.1',
      ].join('\n'),
    },
    {
      id: 'ISP',
      model: 'isr2911',
      x: 9,
      y: 3,
      locked: true,
      config: [
        'interface GigabitEthernet0/0',
        ' description Customer R1',
        ' ip address 203.0.113.1 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description Internet',
        ' ip address 192.0.2.1 255.255.255.0',
        ' no shutdown',
        'ip route 198.51.100.8 255.255.255.248 203.0.113.2',
      ].join('\n'),
    },
    { id: 'INET', model: 'server', x: 11.5, y: 3, host: { ip: '192.0.2.80', mask: '255.255.255.0', gateway: '192.0.2.1' }, services: { http: true } },
    { id: 'PC1', model: 'pc', x: 1, y: 5.5, host: { ip: '10.1.1.11', mask: '255.255.255.0', gateway: '10.1.1.1' } },
    { id: 'PC2', model: 'pc', x: 4, y: 5.5, host: { ip: '10.1.1.12', mask: '255.255.255.0', gateway: '10.1.1.1' } },
    { id: 'PC3', model: 'pc', x: 6, y: 5.8, host: { ip: '10.1.2.11', mask: '255.255.255.0', gateway: '10.1.2.1' } },
  ],
  links: [
    { a: 'R1:g0/0', b: 'SW1:g0/1' },
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'SW1:fa0/3', b: 'SRV1:fa0' },
    { a: 'R1:g0/1', b: 'PC3:fa0' },
    { a: 'R1:g0/2', b: 'ISP:g0/0' },
    { a: 'ISP:g0/1', b: 'INET:fa0' },
  ],
  tasks: [
    {
      id: 'inside-outside',
      title: 'Mark R1 G0/0 and G0/1 as NAT **inside** interfaces and G0/2 (towards the ISP) as the NAT **outside** interface',
      details: 'NAT only translates packets that cross between an inside and an outside interface, so it does nothing until every interface has a role. Use `ip nat inside` on the two LAN interfaces and `ip nat outside` on the uplink. `show ip nat statistics` lists both groups of interfaces.',
      hint: '`interface g0/0` → `ip nat inside`',
      checks: [
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0', pattern: '^ ip nat inside$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/1', pattern: '^ ip nat inside$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/2', pattern: '^ ip nat outside$' },
      ],
    },
    {
      id: 'static-nat',
      title: 'Publish the web server SRV1 (10.1.1.10) on the public address **198.51.100.9** with static NAT',
      details: 'The ISP routes 198.51.100.8/29 to R1, so any address in that block can be an inside global address. A static entry is permanent and works in both directions: the Internet can start connections to 198.51.100.9, and SRV1 always appears as 198.51.100.9 when it connects out. Test it from INET (ping or HTTP to 198.51.100.9) and read `show ip nat translations`.',
      hint: '`ip nat inside source static INSIDE-LOCAL INSIDE-GLOBAL`',
      checks: [
        { type: 'show', device: 'R1', command: 'show ip nat translations', pattern: '198\\.51\\.100\\.9\\s+10\\.1\\.1\\.10' },
        { type: 'ping', from: 'INET', to: '198.51.100.9' },
        { type: 'traffic', from: 'INET', to: '198.51.100.9', proto: 'tcp', port: 80 },
      ],
    },
    {
      id: 'dynamic-nat',
      title: 'Give the staff LAN dynamic NAT: standard ACL **1** permitting 10.1.1.0/24, pool **STAFF** 198.51.100.10 - 198.51.100.12 (/29) and the mapping between them, then ping INET (192.0.2.80) from PC1 and PC2',
      details: 'Dynamic NAT hands every inside host one address from the pool (one-to-one, no port translation) for as long as it has active traffic. The standard ACL decides **which** inside hosts may be translated; the pool supplies the inside global addresses. Entries are created by traffic, so ping INET from the PC command prompts and compare the inside local and inside global columns in `show ip nat translations`.',
      hint: '`access-list 1 permit ...` → `ip nat pool STAFF FIRST LAST netmask 255.255.255.248` → `ip nat inside source list 1 pool STAFF`',
      checks: [
        { type: 'ping', from: 'PC1', to: '192.0.2.80' },
        { type: 'ping', from: 'PC2', to: '192.0.2.80' },
        { type: 'traffic', from: 'PC1', to: '192.0.2.80', proto: 'tcp', port: 80 },
        { type: 'show', device: 'R1', command: 'show ip nat translations', pattern: '198\\.51\\.100\\.1[0-2]\\S*\\s+10\\.1\\.1\\.11' },
        { type: 'show', device: 'R1', command: 'show ip nat translations', pattern: '198\\.51\\.100\\.1[0-2]\\S*\\s+10\\.1\\.1\\.12' },
      ],
    },
    {
      id: 'pat',
      title: 'Let the guest LAN (10.1.2.0/24) share R1\'s outside address with PAT: standard ACL **2** and an `overload` mapping on interface G0/2, then ping INET from PC3',
      details: 'Port Address Translation keeps a single inside global address (here the one configured on G0/2, 203.0.113.2) and tells the sessions apart by source port, so any number of guests fit behind it. `overload` is what turns NAT into PAT, and the `interface` keyword means "use whatever address the outside interface has". Ping INET from PC3 and look at the port numbers in `show ip nat translations`.',
      hint: '`access-list 2 permit ...` → `ip nat inside source list 2 interface g0/2 overload`',
      checks: [
        { type: 'ping', from: 'PC3', to: '192.0.2.80' },
        { type: 'traffic', from: 'PC3', to: '192.0.2.80', proto: 'tcp', port: 80 },
        { type: 'show', device: 'R1', command: 'show ip nat translations', pattern: '203\\.0\\.113\\.2:\\d+\\s+10\\.1\\.2\\.11:\\d+' },
      ],
    },
    {
      id: 'verify',
      title: 'Confirm that every inside host reaches the Internet and that the private networks stay hidden from the ISP',
      details: 'PC1, PC2, PC3 and SRV1 must all reach INET. The ISP has no route to 10.1.1.0/24 or 10.1.2.0/24, so INET must not be able to reach a private address directly: only the translated addresses are visible. `clear ip nat translation *` empties the dynamic entries if you want a fresh start.',
      hint: 'Compare `show ip nat translations` before and after each test.',
      checks: [
        { type: 'ping', from: 'PC1', to: 'INET' },
        { type: 'ping', from: 'PC2', to: 'INET' },
        { type: 'ping', from: 'PC3', to: 'INET' },
        { type: 'ping', from: 'SRV1', to: 'INET' },
        { type: 'ping', from: 'INET', to: '10.1.1.11', expect: false },
        { type: 'traffic', from: 'INET', to: '10.1.2.11', proto: 'tcp', port: 80, expect: false },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'configure terminal',
      'interface GigabitEthernet0/0',
      ' ip nat inside',
      'interface GigabitEthernet0/1',
      ' ip nat inside',
      'interface GigabitEthernet0/2',
      ' ip nat outside',
      ' exit',
      'ip nat inside source static 10.1.1.10 198.51.100.9',
      'access-list 1 permit 10.1.1.0 0.0.0.255',
      'ip nat pool STAFF 198.51.100.10 198.51.100.12 netmask 255.255.255.248',
      'ip nat inside source list 1 pool STAFF',
      'access-list 2 permit 10.1.2.0 0.0.0.255',
      'ip nat inside source list 2 interface GigabitEthernet0/2 overload',
      'end',
    ].join('\n'),
    PC1: 'ping 192.0.2.80',
    PC2: 'ping 192.0.2.80',
    PC3: 'ping 192.0.2.80',
  },
};

export default lab;
