import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-acl-standard',
  title: 'Standard ACLs: Blocking a Host and a Subnet',
  summary: 'Protect two server LANs with a numbered and a named standard ACL: deny one host and one subnet, permit everyone else, and apply each ACL outbound next to the destination.',
  difficulty: 2,
  minutes: 40,
  lessons: ['acl-concepts'],
  scenario:
    'Northwind Traders runs a small head office. Router **R1** serves the Staff LAN (**192.168.1.0/24**, through switch SW1) and the Guest Wi-Fi LAN (**192.168.3.0/24**). Over **10.0.0.0/30** it reaches the data-centre router **R2**, which fronts two server LANs: the **Server LAN 10.10.10.0/24** (intranet server SRV1) and the **Management LAN 10.10.20.0/24** (monitoring server SRV2). Static routing is already in place, so today every host can reach every server.\n\n' +
    'Security has issued two rules. (1) The contractor laptop **PC2 (192.168.1.50)** and the whole **Guest subnet** must be kept off the Management LAN; use a **numbered** standard ACL. (2) The Guest subnet must also be kept off the Server LAN; use a **named** standard ACL. Everybody else, including regular staff PC1, keeps full access, and each ACL must carry a `remark` so the next engineer knows why it exists.\n\n' +
    'A standard ACL only matches the **source** address, so it belongs as close to the **destination** as possible. Configure both ACLs on R2 and apply each one in the **outbound** direction on the interface that faces the LAN it protects. Do not touch R1: filtering at its Guest interface would cut the guests off from everything, not just the servers.',
  devices: [
    { id: 'PC1', model: 'pc', x: 0.8, y: 0.8, label: 'PC1 (Staff)', host: { ip: '192.168.1.10', mask: '255.255.255.0', gateway: '192.168.1.1' } },
    { id: 'PC2', model: 'laptop', x: 0.8, y: 3.6, label: 'PC2 (Contractor)', host: { ip: '192.168.1.50', mask: '255.255.255.0', gateway: '192.168.1.1' } },
    { id: 'SW1', model: 'c2960', x: 3.2, y: 2.2 },
    {
      id: 'R1',
      model: 'isr2911',
      x: 5.6,
      y: 2.2,
      config: [
        'interface GigabitEthernet0/0',
        ' description Staff LAN',
        ' ip address 192.168.1.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description Guest Wi-Fi LAN',
        ' ip address 192.168.3.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description Link to R2',
        ' ip address 10.0.0.1 255.255.255.252',
        ' no shutdown',
        'ip route 10.10.0.0 255.255.0.0 10.0.0.2',
      ].join('\n'),
    },
    { id: 'PC3', model: 'laptop', x: 5.6, y: 5.4, label: 'PC3 (Guest)', host: { ip: '192.168.3.10', mask: '255.255.255.0', gateway: '192.168.3.1' } },
    {
      id: 'R2',
      model: 'isr2911',
      x: 8.4,
      y: 2.2,
      config: [
        'interface GigabitEthernet0/0',
        ' description Link to R1',
        ' ip address 10.0.0.2 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description Server LAN',
        ' ip address 10.10.10.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description Management LAN',
        ' ip address 10.10.20.1 255.255.255.0',
        ' no shutdown',
        'ip route 0.0.0.0 0.0.0.0 10.0.0.1',
      ].join('\n'),
    },
    {
      id: 'SRV1',
      model: 'server',
      x: 11.2,
      y: 0.8,
      label: 'SRV1 (Intranet)',
      host: { ip: '10.10.10.10', mask: '255.255.255.0', gateway: '10.10.10.1' },
      services: { http: true },
    },
    {
      id: 'SRV2',
      model: 'server',
      x: 11.2,
      y: 3.6,
      label: 'SRV2 (Monitoring)',
      host: { ip: '10.10.20.10', mask: '255.255.255.0', gateway: '10.10.20.1' },
      services: { http: true },
    },
  ],
  links: [
    { a: 'PC1:fa0', b: 'SW1:fa0/1' },
    { a: 'PC2:fa0', b: 'SW1:fa0/2' },
    { a: 'SW1:g0/1', b: 'R1:g0/0' },
    { a: 'PC3:fa0', b: 'R1:g0/1' },
    { a: 'R1:g0/2', b: 'R2:g0/0' },
    { a: 'R2:g0/1', b: 'SRV1:fa0' },
    { a: 'R2:g0/2', b: 'SRV2:fa0' },
  ],
  tasks: [
    {
      id: 'acl10',
      title: 'On R2 create numbered standard ACL **10**: deny host **192.168.1.50**, deny the subnet **192.168.3.0/24**, permit everything else',
      details:
        'Standard ACLs use numbers 1-99 (and 1300-1999). Entries are checked top-down and the first match wins, so the catch-all `permit any` must come last; without it the implicit `deny any` at the end of every ACL would block everyone. The subnet needs a **wildcard** mask (the inverse of the subnet mask). Verify with `show access-lists`.',
      hint: 'Numbered syntax is `access-list <number> {permit|deny} <source> [wildcard]`. `host A.B.C.D` matches one address, `any` matches all of them.',
      checks: [
        { type: 'config', device: 'R2', pattern: '^access-list 10 deny\\s+(host\\s+)?192\\.168\\.1\\.50$' },
        { type: 'config', device: 'R2', pattern: '^access-list 10 deny\\s+192\\.168\\.3\\.0 0\\.0\\.0\\.255$' },
        { type: 'config', device: 'R2', pattern: '^access-list 10 permit\\s+any$' },
        { type: 'show', device: 'R2', command: 'show access-lists', pattern: 'Standard IP access list 10' },
      ],
    },
    {
      id: 'remark10',
      title: 'Document ACL 10 with a remark entry that says why it exists',
      details: 'A remark is a free-text comment stored inside the ACL (up to 100 characters). It does not filter anything, but it shows up in the running configuration and saves the next engineer a lot of guessing.',
      hint: '`access-list 10 remark <text>`; check it with `show running-config | include access-list 10`.',
      checks: [{ type: 'config', device: 'R2', pattern: '^access-list 10 remark\\s+\\S+' }],
    },
    {
      id: 'apply10',
      title: 'Apply ACL 10 outbound on R2 G0/2 (the Management LAN) so that PC2 and the Guest subnet can no longer reach SRV2',
      details:
        'Direction is always seen from the router: **out** filters packets that are leaving the interface towards SRV2. Applying the same ACL **in** on G0/2 would only inspect packets arriving *from* SRV2, whose source address is permitted, so nothing would be blocked. PC1 must keep working.',
      hint: 'ACLs are attached with `ip access-group <acl> {in|out}` under the interface. Check the result with `show ip interface g0/2`.',
      checks: [
        { type: 'config', device: 'R2', section: 'interface GigabitEthernet0/2', pattern: '^ ip access-group 10 out$' },
        { type: 'ping', from: 'PC2', to: '10.10.20.10', expect: false },
        { type: 'traffic', from: 'PC3', to: '10.10.20.10', proto: 'tcp', port: 80, expect: false },
        { type: 'ping', from: 'PC1', to: '10.10.20.10' },
        { type: 'traffic', from: 'PC1', to: '10.10.20.10', proto: 'tcp', port: 80 },
      ],
    },
    {
      id: 'acl-named',
      title: 'On R2 create named standard ACL **GUEST-BLOCK** with a remark, a deny for **192.168.3.0/24** and a final permit for everyone else',
      details: 'Named ACLs are edited in their own mode (`ip access-list standard NAME`, prompt `(config-std-nacl)#`). Inside it you type the entries without the `access-list` keyword: `remark`, `deny`, `permit`. Names are case-sensitive.',
      hint: 'Enter the mode with `ip access-list standard <name>`; inside it the entries have no `access-list` prefix. Verify with `show access-lists`.',
      checks: [
        { type: 'config', device: 'R2', section: 'ip access-list standard GUEST-BLOCK', pattern: '^ remark\\s+\\S+' },
        { type: 'config', device: 'R2', section: 'ip access-list standard GUEST-BLOCK', pattern: '^ deny\\s+192\\.168\\.3\\.0 0\\.0\\.0\\.255$' },
        { type: 'config', device: 'R2', section: 'ip access-list standard GUEST-BLOCK', pattern: '^ permit\\s+any$' },
        { type: 'show', device: 'R2', command: 'show access-lists', pattern: 'Standard IP access list GUEST-BLOCK' },
      ],
    },
    {
      id: 'apply-named',
      title: 'Apply GUEST-BLOCK outbound on R2 G0/1 (the Server LAN) so the Guest subnet can no longer reach SRV1',
      details: 'PC1 and the contractor laptop PC2 are still allowed on the Server LAN: ACL 10 only protects the Management LAN, and GUEST-BLOCK only names the guest subnet. Guests must still reach their own gateway, R1.',
      hint: 'Same idea as before, on the other interface. `show ip interface g0/1` lists the incoming and outgoing ACL of the port.',
      checks: [
        { type: 'show', device: 'R2', command: 'show ip interface GigabitEthernet0/1', pattern: 'Outgoing access list is GUEST-BLOCK' },
        { type: 'ping', from: 'PC3', to: '10.10.10.10', expect: false },
        { type: 'traffic', from: 'PC3', to: '10.10.10.10', proto: 'tcp', port: 80, expect: false },
        { type: 'ping', from: 'PC1', to: '10.10.10.10' },
        { type: 'traffic', from: 'PC2', to: '10.10.10.10', proto: 'tcp', port: 80 },
        { type: 'ping', from: 'PC3', to: '192.168.3.1' },
      ],
    },
    {
      id: 'save',
      title: 'Save the configuration on R2',
      details: 'ACLs live in the running configuration only until you save. Compare `show running-config` with `show startup-config` if you want to see the difference.',
      hint: '`copy running-config startup-config` or `write memory`',
      checks: [{ type: 'saved', device: 'R2' }],
    },
  ],
  solution: {
    R2: [
      'enable',
      'configure terminal',
      'access-list 10 remark Contractor laptop and guests are not allowed on the Management LAN',
      'access-list 10 deny host 192.168.1.50',
      'access-list 10 deny 192.168.3.0 0.0.0.255',
      'access-list 10 permit any',
      'interface GigabitEthernet0/2',
      ' ip access-group 10 out',
      ' exit',
      'ip access-list standard GUEST-BLOCK',
      ' remark Guest Wi-Fi must not reach the Server LAN',
      ' deny 192.168.3.0 0.0.0.255',
      ' permit any',
      ' exit',
      'interface GigabitEthernet0/1',
      ' ip access-group GUEST-BLOCK out',
      ' do write memory',
      ' end',
    ].join('\n'),
  },
};

export default lab;
