import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-ospf-troubleshooting',
  title: 'OSPF Troubleshooting: Four Faults, One Network',
  summary: 'Diagnose and repair a broken OSPF area 0: mismatched hello/dead timers, an area mismatch, a LAN missing from the network statements and a user-facing interface that should be passive.',
  difficulty: 3,
  minutes: 45,
  lessons: ['ospf-config', 'ospf-network-types'],
  scenario:
    'Contoso Retail runs OSPF across four routers: R2 is the hub, and R1 (site A), R3 (site B) and R4 (site C) each connect to it over a /30 link. Every site has a user LAN with one PC: **192.168.1.0/24** on R1, **192.168.3.0/24** on R3 and **192.168.4.0/24** on R4. All links and LANs were meant to run in **area 0** with default OSPF timers.\n\n' +
    'After the weekend change window the network is only half working: R2 has no OSPF neighbor on two of its three links, PC1 cannot reach the other sites, and the security team noticed OSPF hellos leaving a user-facing port. Four independent faults were reported, one on each of four different routers. IP addressing and cabling are fine, and the router IDs must stay as they are.\n\n' +
    'Diagnose with `show ip ospf neighbor`, `show ip ospf interface`, `show ip protocols` and `show ip route ospf`, then repair every fault with the smallest possible change.',
  devices: [
    {
      id: 'R1',
      model: 'isr4321',
      x: 2,
      y: 2.2,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to R2',
        ' ip address 10.0.12.1 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description User LAN',
        ' ip address 192.168.1.1 255.255.255.0',
        ' no shutdown',
        'router ospf 1',
        ' router-id 1.1.1.1',
        ' network 10.0.12.0 0.0.0.3 area 0',
        ' network 192.168.1.0 0.0.0.255 area 0',
      ].join('\n'),
    },
    {
      id: 'R2',
      model: 'isr2911',
      x: 6,
      y: 2.2,
      config: [
        'interface GigabitEthernet0/0',
        ' description Link to R1',
        ' ip address 10.0.12.2 255.255.255.252',
        ' ip ospf hello-interval 30',
        ' ip ospf dead-interval 120',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description Link to R3',
        ' ip address 10.0.23.1 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description Link to R4',
        ' ip address 10.0.24.1 255.255.255.252',
        ' no shutdown',
        'router ospf 1',
        ' router-id 2.2.2.2',
        ' network 10.0.12.0 0.0.0.3 area 0',
        ' network 10.0.23.0 0.0.0.3 area 0',
        ' network 10.0.24.0 0.0.0.3 area 0',
      ].join('\n'),
    },
    {
      id: 'R3',
      model: 'isr4321',
      x: 10,
      y: 2.2,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to R2',
        ' ip address 10.0.23.2 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description User LAN',
        ' ip address 192.168.3.1 255.255.255.0',
        ' no shutdown',
        'router ospf 1',
        ' router-id 3.3.3.3',
        ' passive-interface GigabitEthernet0/0/1',
        ' network 10.0.23.0 0.0.0.3 area 1',
        ' network 192.168.3.0 0.0.0.255 area 0',
      ].join('\n'),
    },
    {
      id: 'R4',
      model: 'isr4321',
      x: 6,
      y: 4.4,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to R2',
        ' ip address 10.0.24.2 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description User LAN',
        ' ip address 192.168.4.1 255.255.255.0',
        ' no shutdown',
        'router ospf 1',
        ' router-id 4.4.4.4',
        ' passive-interface GigabitEthernet0/0/1',
        ' network 10.0.24.0 0.0.0.3 area 0',
      ].join('\n'),
    },
    { id: 'PC1', model: 'pc', x: 2, y: 5, host: { ip: '192.168.1.10', mask: '255.255.255.0', gateway: '192.168.1.1' } },
    { id: 'PC3', model: 'pc', x: 10, y: 5, host: { ip: '192.168.3.10', mask: '255.255.255.0', gateway: '192.168.3.1' } },
    { id: 'PC4', model: 'pc', x: 6, y: 6.4, host: { ip: '192.168.4.10', mask: '255.255.255.0', gateway: '192.168.4.1' } },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'R2:g0/0' },
    { a: 'R2:g0/1', b: 'R3:g0/0/0' },
    { a: 'R2:g0/2', b: 'R4:g0/0/0' },
    { a: 'R1:g0/0/1', b: 'PC1:fa0' },
    { a: 'R3:g0/0/1', b: 'PC3:fa0' },
    { a: 'R4:g0/0/1', b: 'PC4:fa0' },
  ],
  tasks: [
    {
      id: 'timers',
      title: 'Bring up the R1-R2 adjacency on **10.0.12.0/30**: the hello and dead timers must match, and every link in this network uses the defaults (**hello 10, dead 40**)',
      details: 'OSPF neighbors ignore each other\'s hellos unless the hello and dead intervals agree. Compare `show ip ospf interface` on both ends of the link, then look at what the healthy links use. Repair the router that deviates by removing its custom timers instead of changing the rest of the network.',
      hint: '`show ip ospf interface` on R1 and on R2: compare the Hello and Dead values.',
      checks: [
        { type: 'ospfNeighbor', device: 'R1', neighbor: '2.2.2.2', state: 'FULL' },
        { type: 'ospfNeighbor', device: 'R2', neighbor: '1.1.1.1', state: 'FULL' },
        { type: 'show', device: 'R2', command: 'show ip ospf interface GigabitEthernet0/0', pattern: 'Hello 10, Dead 40' },
      ],
    },
    {
      id: 'area',
      title: 'Bring up the R2-R3 adjacency on **10.0.23.0/30**: both ends of the link must be in **area 0**',
      details: 'Two routers only become neighbors on a link when their interfaces belong to the same area. Compare the area that each end reports in `show ip ospf interface`, and read the `network` statements in `show ip protocols`. A network statement cannot be edited in place: remove the wrong one with `no network ...` and enter the right one.',
      hint: '`show ip protocols` lists every network statement together with its area.',
      checks: [
        { type: 'ospfNeighbor', device: 'R2', neighbor: '3.3.3.3', state: 'FULL' },
        { type: 'ospfNeighbor', device: 'R3', neighbor: '2.2.2.2', state: 'FULL' },
        { type: 'show', device: 'R3', command: 'show ip ospf interface GigabitEthernet0/0/0', pattern: 'Area 0\\b' },
      ],
    },
    {
      id: 'missing-lan',
      title: 'Advertise the user LAN **192.168.4.0/24** of R4 in area 0',
      details: 'R4\'s LAN interface is up and even passive, yet nobody has a route to 192.168.4.0/24. A passive interface is advertised only when a `network` statement (or `ip ospf area`) covers it. Compare the networks listed in `show ip protocols` on R4 with its interface addresses.',
      hint: '`show ip protocols` → Routing for Networks',
      checks: [{ type: 'route', device: 'R2', prefix: '192.168.4.0/24', source: 'O', nextHop: '10.0.24.2' }],
    },
    {
      id: 'passive',
      title: 'Stop OSPF hellos from leaving the user LAN of R1: make **GigabitEthernet0/0/1** passive on R1 while keeping the LAN advertised',
      details: 'Hellos on a user LAN waste bandwidth and let anyone who plugs in a router try to form an adjacency. A passive interface stays in OSPF and its network is still advertised, but no hellos are sent or accepted. R3 and R4 are already set up this way. Verify with `show ip protocols` (Passive Interface(s)).',
      hint: '`router ospf 1` → `passive-interface <interface>`',
      checks: [
        { type: 'config', device: 'R1', section: 'router ospf 1', pattern: '^ passive-interface GigabitEthernet0/0/1$' },
        { type: 'show', device: 'R1', command: 'show ip protocols', pattern: 'Passive Interface\\(s\\):\\s*\\n\\s+GigabitEthernet0/0/1' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify the repaired network: every router must know the three user LANs and all PCs must reach each other',
      details: 'Check `show ip route ospf` on each router: R1, R3 and R4 learn the two remote LANs as O routes through the hub R2. Then ping between the PCs.',
      hint: '`show ip route ospf`',
      checks: [
        { type: 'route', device: 'R1', prefix: '192.168.3.0/24', source: 'O', nextHop: '10.0.12.2' },
        { type: 'route', device: 'R1', prefix: '192.168.4.0/24', source: 'O', nextHop: '10.0.12.2' },
        { type: 'route', device: 'R3', prefix: '192.168.1.0/24', source: 'O', nextHop: '10.0.23.1' },
        { type: 'route', device: 'R4', prefix: '192.168.1.0/24', source: 'O', nextHop: '10.0.24.1' },
        { type: 'route', device: 'R4', prefix: '192.168.3.0/24', source: 'O', nextHop: '10.0.24.1' },
        { type: 'ping', from: 'PC1', to: '192.168.3.10' },
        { type: 'ping', from: 'PC1', to: '192.168.4.10' },
        { type: 'ping', from: 'PC3', to: '192.168.4.10' },
        { type: 'ping', from: 'PC4', to: '192.168.1.10' },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'configure terminal',
      'router ospf 1',
      ' passive-interface GigabitEthernet0/0/1',
      ' end',
    ].join('\n'),
    R2: [
      'enable',
      'configure terminal',
      'interface GigabitEthernet0/0',
      ' no ip ospf hello-interval',
      ' no ip ospf dead-interval',
      ' end',
    ].join('\n'),
    R3: [
      'enable',
      'configure terminal',
      'router ospf 1',
      ' no network 10.0.23.0 0.0.0.3 area 1',
      ' network 10.0.23.0 0.0.0.3 area 0',
      ' end',
    ].join('\n'),
    R4: [
      'enable',
      'configure terminal',
      'router ospf 1',
      ' network 192.168.4.0 0.0.0.255 area 0',
      ' end',
    ].join('\n'),
  },
};

export default lab;
