import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-ssh-remote-access',
  title: 'Secure Remote Access with SSH',
  summary: 'Replace Telnet with SSHv2 on a router and a switch: RSA keys, local accounts, VTY hardening, an access-class that only admits the admin workstation, plus enable secret and console protection.',
  difficulty: 2,
  minutes: 45,
  lessons: ['ssh-remote-access', 'device-access-control'],
  scenario:
    'A security audit flagged the management plane of the Wizard Corp office. R1 (the router) and SW1 (the access switch) both accept **Telnet** on their VTY lines with the shared password `cisco`, so credentials and whole sessions cross the network in clear text, and anyone who can reach the devices may try to log in. The privileged EXEC password is also the clear-text `enable password cisco`.\n\n' +
    'Move management to **SSH version 2 only** with an individual account, close idle sessions, and restrict who may even try: only the admin workstation **PC1 (10.10.10.10)** may manage the devices. The helpdesk PC, **PC2 (10.10.20.20)** on the user LAN, must be refused even with valid credentials, yet it keeps normal IP connectivity.\n\n' +
    'Addressing is done: R1 is 10.10.10.1 (admin LAN) and 10.10.20.1 (user LAN), SW1 is managed at 10.10.10.2. Use the account **admin** with secret **Ssh-Pass-2026** everywhere. Until the change is made you reach the devices on the console with the enable password `cisco`.',
  devices: [
    { id: 'PC1', model: 'pc', x: 1, y: 3, label: 'PC1 (admin)', host: { ip: '10.10.10.10', mask: '255.255.255.0', gateway: '10.10.10.1' } },
    {
      id: 'SW1',
      model: 'c2960',
      x: 4.2,
      y: 3,
      config: [
        'enable password cisco',
        'interface Vlan1',
        ' ip address 10.10.10.2 255.255.255.0',
        ' no shutdown',
        'ip default-gateway 10.10.10.1',
        'line vty 0 15',
        ' password cisco',
        ' login',
        ' transport input telnet',
      ].join('\n'),
    },
    {
      id: 'R1',
      model: 'isr4321',
      x: 7.6,
      y: 3,
      config: [
        'enable password cisco',
        'interface GigabitEthernet0/0/0',
        ' description Admin LAN',
        ' ip address 10.10.10.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description User LAN',
        ' ip address 10.10.20.1 255.255.255.0',
        ' no shutdown',
        'line vty 0 4',
        ' password cisco',
        ' login',
        ' transport input telnet',
      ].join('\n'),
    },
    { id: 'PC2', model: 'pc', x: 11, y: 3, label: 'PC2 (helpdesk)', host: { ip: '10.10.20.20', mask: '255.255.255.0', gateway: '10.10.20.1' } },
  ],
  links: [
    { a: 'PC1:fa0', b: 'SW1:fa0/1' },
    { a: 'SW1:g0/1', b: 'R1:g0/0/0' },
    { a: 'R1:g0/0/1', b: 'PC2:fa0' },
  ],
  tasks: [
    {
      id: 'ssh-prereq',
      title: 'On R1 set the domain name **wizard.local**, generate a **2048-bit** RSA key pair and enable **SSH version 2** with a 60-second timeout and 2 authentication retries',
      details: 'SSH needs a hostname other than the default, a domain name (the key pair is named hostname.domain) and an RSA key pair; SSHv2 requires at least 768 bits and 2048 is the usual choice. `ip ssh version 2` refuses SSHv1 clients, `ip ssh time-out` limits the time allowed for authentication and `ip ssh authentication-retries` the number of attempts. Confirm with `show ip ssh`: it must report "SSH Enabled - version 2.0".',
      hint: '`ip domain-name`, `crypto key generate rsa`, then the `ip ssh` options; `show ip ssh` shows the result',
      checks: [
        { type: 'show', device: 'R1', command: 'show ip ssh', pattern: 'SSH Enabled - version 2\\.0' },
        { type: 'config', device: 'R1', pattern: '^ip ssh time-out 60$' },
        { type: 'config', device: 'R1', pattern: '^ip ssh authentication-retries 2$' },
      ],
    },
    {
      id: 'local-user',
      title: 'Create the local account **admin** with privilege level 15 and secret **Ssh-Pass-2026** on R1',
      details: 'Individual accounts make every login attributable to a person, unlike the shared line password. `username NAME privilege 15 secret PASSWORD` stores a hash (`secret`) rather than clear text (`password`), and privilege 15 puts the user straight into privileged EXEC.',
      hint: '`username NAME privilege LEVEL secret PASSWORD`',
      checks: [{ type: 'config', device: 'R1', pattern: '^username admin privilege 15 secret ' }],
    },
    {
      id: 'vty-ssh',
      title: 'Limit R1\'s VTY lines to SSH with local authentication and a 5-minute idle timeout, and delete the shared line password',
      details: 'The legacy `line vty 0 4` accepts Telnet and the shared password. `transport input ssh` refuses Telnet, `login local` authenticates against the local username database, `exec-timeout 5 0` disconnects idle sessions after five minutes and `no password` removes the now unused shared password. From the PC1 command prompt, `ssh -l admin 10.10.10.1` must work; Telnet and a wrong password must not.',
      hint: 'Under `line vty 0 4`: `transport input`, `login local`, `exec-timeout MIN SEC` and the `no` form of `password`',
      checks: [
        { type: 'login', from: 'PC1', to: '10.10.10.1', protocol: 'ssh', username: 'admin', password: 'Ssh-Pass-2026' },
        { type: 'login', from: 'PC1', to: '10.10.10.1', protocol: 'ssh', username: 'admin', password: 'not-the-password', expect: false },
        { type: 'login', from: 'PC1', to: '10.10.10.1', protocol: 'telnet', password: 'cisco', expect: false },
        { type: 'config', device: 'R1', section: 'line vty 0 4', pattern: '^ exec-timeout 5 0$' },
        { type: 'config', device: 'R1', section: 'line vty 0 4', pattern: '^ password ', expect: false },
      ],
    },
    {
      id: 'vty-acl',
      title: 'Allow management sessions on R1 only from the admin workstation PC1 (10.10.10.10): standard ACL **10** applied with `access-class 10 in` on the VTY lines',
      details: 'SSH is still open to everyone who can reach the router. A standard ACL referenced by `access-class ... in` under the VTY lines filters the **source** of incoming management sessions without touching the traffic the router forwards. PC2 (10.10.20.20) must be refused even with valid credentials, but it must still be able to ping R1.',
      hint: '`access-list 10 permit host ...`, then under `line vty 0 4`: `access-class 10 in`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^access-list 10 permit (host )?10\\.10\\.10\\.10$' },
        { type: 'config', device: 'R1', section: 'line vty 0 4', pattern: '^ access-class 10 in$' },
        { type: 'login', from: 'PC1', to: '10.10.10.1', protocol: 'ssh', username: 'admin', password: 'Ssh-Pass-2026' },
        { type: 'login', from: 'PC2', to: '10.10.20.1', protocol: 'ssh', username: 'admin', password: 'Ssh-Pass-2026', expect: false },
        { type: 'ping', from: 'PC2', to: '10.10.20.1' },
      ],
    },
    {
      id: 'switch-ssh',
      title: 'Apply the same management hardening to SW1 (10.10.10.2): SSHv2 only, the **admin** account, 5-minute timeout and sources limited by ACL **10**',
      details: 'The switch needs the same ingredients as the router: domain name, RSA keys, `ip ssh version 2`, the local account, and on `line vty 0 15` the commands `transport input ssh`, `login local`, `exec-timeout 5 0` and `access-class 10 in` (ACL 10 permitting only PC1). A Layer 2 switch is managed through its SVI, here Vlan1. PC2 reaches that address through R1, so the ACL has to stop it.',
      hint: 'Same steps as on R1, but the switch has VTY lines 0 to 15.',
      checks: [
        { type: 'show', device: 'SW1', command: 'show ip ssh', pattern: 'SSH Enabled - version 2\\.0' },
        { type: 'login', from: 'PC1', to: '10.10.10.2', protocol: 'ssh', username: 'admin', password: 'Ssh-Pass-2026' },
        { type: 'login', from: 'PC1', to: '10.10.10.2', protocol: 'telnet', password: 'cisco', expect: false },
        { type: 'login', from: 'PC2', to: '10.10.10.2', protocol: 'ssh', username: 'admin', password: 'Ssh-Pass-2026', expect: false },
        { type: 'config', device: 'SW1', section: 'line vty 0 15', pattern: '^ access-class 10 in$' },
        { type: 'config', device: 'SW1', section: 'line vty 0 15', pattern: '^ exec-timeout 5 0$' },
      ],
    },
    {
      id: 'access-control',
      title: 'On R1 and SW1 replace the clear-text `enable password` with an `enable secret`, enable `service password-encryption` and require local login with a 5-minute timeout on the console',
      details: '`enable password` is stored in clear text, `enable secret` as a hash, so remove the old one with `no enable password`. `service password-encryption` obscures any plain passwords that remain in the configuration (type 7, weak but not readable at a glance). Under `line con 0` use `login local` and `exec-timeout 5 0` so that an unattended console does not stay logged in.',
      hint: '`enable secret ...`, `no enable password`, `service password-encryption`, `line con 0`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^enable password', expect: false },
        { type: 'config', device: 'R1', pattern: '^enable secret ' },
        { type: 'config', device: 'R1', pattern: '^service password-encryption$' },
        { type: 'config', device: 'R1', section: 'line con 0', pattern: '^ login local$' },
        { type: 'config', device: 'R1', section: 'line con 0', pattern: '^ exec-timeout 5 0$' },
        { type: 'config', device: 'SW1', pattern: '^enable password', expect: false },
        { type: 'config', device: 'SW1', pattern: '^enable secret ' },
        { type: 'config', device: 'SW1', pattern: '^service password-encryption$' },
        { type: 'config', device: 'SW1', section: 'line con 0', pattern: '^ login local$' },
        { type: 'config', device: 'SW1', section: 'line con 0', pattern: '^ exec-timeout 5 0$' },
      ],
    },
    {
      id: 'save',
      title: 'Save the configuration on R1 and SW1 so the new access rules survive a reload',
      details: 'Until the running configuration is copied to NVRAM, a reload brings back Telnet and the clear-text passwords. Use `copy running-config startup-config` (or `write memory`) on both devices; `show startup-config` shows what would be loaded.',
      hint: '`copy running-config startup-config`',
      checks: [
        { type: 'show', device: 'R1', command: 'show startup-config', pattern: 'transport input ssh' },
        { type: 'show', device: 'SW1', command: 'show startup-config', pattern: 'transport input ssh' },
        { type: 'saved', device: 'R1' },
        { type: 'saved', device: 'SW1' },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'cisco',
      'configure terminal',
      'ip domain-name wizard.local',
      'crypto key generate rsa modulus 2048',
      'ip ssh version 2',
      'ip ssh time-out 60',
      'ip ssh authentication-retries 2',
      'username admin privilege 15 secret Ssh-Pass-2026',
      'access-list 10 permit host 10.10.10.10',
      'line vty 0 4',
      ' transport input ssh',
      ' login local',
      ' exec-timeout 5 0',
      ' no password',
      ' access-class 10 in',
      ' exit',
      'enable secret Enable-Pass-2026',
      'no enable password',
      'service password-encryption',
      'line con 0',
      ' login local',
      ' exec-timeout 5 0',
      ' exit',
      'do write memory',
      'end',
    ].join('\n'),
    SW1: [
      'enable',
      'cisco',
      'configure terminal',
      'ip domain-name wizard.local',
      'crypto key generate rsa modulus 2048',
      'ip ssh version 2',
      'ip ssh time-out 60',
      'ip ssh authentication-retries 2',
      'username admin privilege 15 secret Ssh-Pass-2026',
      'access-list 10 permit host 10.10.10.10',
      'line vty 0 15',
      ' transport input ssh',
      ' login local',
      ' exec-timeout 5 0',
      ' no password',
      ' access-class 10 in',
      ' exit',
      'enable secret Enable-Pass-2026',
      'no enable password',
      'service password-encryption',
      'line con 0',
      ' login local',
      ' exec-timeout 5 0',
      ' exit',
      'do write memory',
      'end',
    ].join('\n'),
  },
};

export default lab;
