import type { Lab } from '../labTypes';

const vlanDb = ['vlan 10', ' name OFFICE', 'vlan 20', ' name WAREHOUSE', 'vlan 99', ' name NATIVE'];

const lab: Lab = {
  id: 'lab-troubleshoot-vlan-trunk',
  title: 'Troubleshooting VLANs and Trunks',
  summary:
    'Work a trouble ticket on a router-on-a-stick network: use show commands to find five hidden faults (shut port, wrong VLAN, trunk allowed list, native VLAN mismatch, wrong gateway) and fix them one layer at a time.',
  difficulty: 3,
  minutes: 40,
  lessons: ['trunking', 'vlans', 'interface-issues', 'troubleshooting-methodology'],
  scenario:
    'You are the on-call technician at **Contoso Freight**. The second-floor closet holds two access switches, **SW1** and **SW2**, joined by an 802.1Q trunk on G0/1, and **R1**, which routes between VLANs with router-on-a-stick over SW1 G0/2. The design is **VLAN 10 OFFICE** (192.168.10.0/24, gateway 192.168.10.1), **VLAN 20 WAREHOUSE** (192.168.20.0/24, gateway 192.168.20.1) and an unused **native VLAN 99**.\n\n' +
    'After last weekend\'s "cleanup", ticket #4821 arrived: *"Warehouse users cannot reach their gateway."* The warehouse PCs are PC2 and PC3 on SW1 and PC4 and PC5 on SW2; the office PC1 (on SW2) still works. R1 and its sub-interfaces were not touched, so the problems are on the switches and the hosts, and there is more than one of them.\n\n' +
    'Work bottom-up with `show` commands (`show interfaces status`, `show vlan brief`, `show interfaces trunk`, `ipconfig` on the PCs). Find each fault, fix it and re-test before you move on. Finish by proving that every warehouse PC reaches its gateway and the office, and save the switch configurations.',
  devices: [
    { id: 'R1', model: 'isr4321', x: 1.5, y: 3, config: [
      'interface GigabitEthernet0/0/0',
      ' description Trunk to SW1 G0/2',
      ' no shutdown',
      'interface GigabitEthernet0/0/0.10',
      ' description OFFICE gateway',
      ' encapsulation dot1Q 10',
      ' ip address 192.168.10.1 255.255.255.0',
      'interface GigabitEthernet0/0/0.20',
      ' description WAREHOUSE gateway',
      ' encapsulation dot1Q 20',
      ' ip address 192.168.20.1 255.255.255.0',
    ].join('\n') },
    { id: 'SW1', model: 'c2960', x: 5, y: 3, config: [
      ...vlanDb,
      'interface FastEthernet0/1',
      ' description PC2 (warehouse)',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface FastEthernet0/2',
      ' description PC3 (warehouse)',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface GigabitEthernet0/1',
      ' description Trunk to SW2 G0/1',
      ' switchport mode trunk',
      ' switchport trunk allowed vlan 10,20,99',
      'interface GigabitEthernet0/2',
      ' description Trunk to R1 G0/0/0',
      ' switchport mode trunk',
      ' switchport trunk allowed vlan 10,20',
    ].join('\n') },
    { id: 'SW2', model: 'c2960', x: 10, y: 3, config: [
      ...vlanDb,
      'interface FastEthernet0/1',
      ' description PC1 (office)',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface FastEthernet0/2',
      ' description PC4 (warehouse)',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface FastEthernet0/3',
      ' description PC5 (warehouse)',
      ' switchport mode access',
      ' switchport access vlan 20',
      ' shutdown',
      'interface GigabitEthernet0/1',
      ' description Trunk to SW1 G0/1',
      ' switchport mode trunk',
      ' switchport trunk native vlan 99',
      ' switchport trunk allowed vlan 10,99',
    ].join('\n') },
    { id: 'PC1', model: 'pc', x: 10, y: 0.8, host: { ip: '192.168.10.11', mask: '255.255.255.0', gateway: '192.168.10.1' } },
    { id: 'PC2', model: 'pc', x: 3.5, y: 6, host: { ip: '192.168.20.12', mask: '255.255.255.0', gateway: '192.168.20.1' } },
    { id: 'PC3', model: 'pc', x: 6.5, y: 6, host: { ip: '192.168.20.13', mask: '255.255.255.0', gateway: '192.168.20.254' } },
    { id: 'PC4', model: 'pc', x: 8.5, y: 6, host: { ip: '192.168.20.14', mask: '255.255.255.0', gateway: '192.168.20.1' } },
    { id: 'PC5', model: 'pc', x: 11.5, y: 6, host: { ip: '192.168.20.15', mask: '255.255.255.0', gateway: '192.168.20.1' } },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'SW1:g0/2' },
    { a: 'SW1:g0/1', b: 'SW2:g0/1' },
    { a: 'SW1:fa0/1', b: 'PC2:fa0' },
    { a: 'SW1:fa0/2', b: 'PC3:fa0' },
    { a: 'SW2:fa0/1', b: 'PC1:fa0' },
    { a: 'SW2:fa0/2', b: 'PC4:fa0' },
    { a: 'SW2:fa0/3', b: 'PC5:fa0' },
  ],
  tasks: [
    {
      id: 'port-up',
      title: 'Bring PC5\'s switch port (**SW2 Fa0/3**) up/up as an access port in **VLAN 20**',
      details: 'PC5 has no link light. `show interfaces status` on SW2 shows every port\'s state: `disabled` means an administrator shut the port, `err-disabled` means a protection feature did. Fix the cause, then confirm the port is connected and in VLAN 20.',
      hint: '`show interfaces status` on SW2 and read the Status column for Fa0/3.',
      checks: [
        { type: 'interface', device: 'SW2', iface: 'Fa0/3', status: 'up' },
        { type: 'switchport', device: 'SW2', iface: 'Fa0/3', mode: 'access', accessVlan: 20 },
      ],
    },
    {
      id: 'wrong-vlan',
      title: 'Move PC2 (**SW1 Fa0/1**) into **VLAN 20** so it can reach its gateway **192.168.20.1**',
      details: 'PC2 sits on the same switch as the router uplink, so the SW1–SW2 trunk cannot be the cause. Compare `show vlan brief` with the design: which VLAN is Fa0/1 really in? Prove the fix with a ping from PC2 to 192.168.20.1.',
      hint: '`show vlan brief`, then `show interfaces fa0/1 switchport`.',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Fa0/1', mode: 'access', accessVlan: 20 },
        { type: 'ping', from: 'PC2', to: '192.168.20.1' },
      ],
    },
    {
      id: 'trunk-allowed',
      title: 'Make the SW1–SW2 trunk (**G0/1**) carry **VLANs 10, 20 and 99** in both directions',
      details: 'PC1 (VLAN 10) works across the trunk, but the warehouse PCs on SW2 do not: something on the trunk passes VLAN 10 and drops VLAN 20. Compare the *Vlans allowed on trunk* list of **both** ends in `show interfaces trunk`. When you change a list, use the `add` keyword so the VLANs already allowed are kept.',
      hint: '`show interfaces trunk` on SW1 and on SW2, then `switchport trunk allowed vlan add …`.',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Gi0/1', mode: 'trunk', allowed: '10,20,99' },
        { type: 'switchport', device: 'SW2', iface: 'Gi0/1', mode: 'trunk', allowed: '10,20,99' },
        { type: 'ping', from: 'PC4', to: '192.168.20.1' },
      ],
    },
    {
      id: 'native-vlan',
      title: 'Fix the native VLAN mismatch: **both ends** of the SW1–SW2 trunk must use native VLAN **99**',
      details: 'Tagged traffic for VLANs 10 and 20 is not affected, which is why this fault hides so well. Compare the *Native vlan* column of `show interfaces trunk` on both switches; CDP also complains about the mismatch in the log.',
      hint: '`show interfaces trunk` — the Native vlan column must be identical on both ends.',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Gi0/1', mode: 'trunk', nativeVlan: 99 },
        { type: 'switchport', device: 'SW2', iface: 'Gi0/1', mode: 'trunk', nativeVlan: 99 },
        { type: 'show', device: 'SW1', command: 'show interfaces trunk', pattern: '^Gi0/1\\s+on\\s+802\\.1q\\s+trunking\\s+99$' },
      ],
    },
    {
      id: 'gateway',
      title: 'Correct the default gateway on **PC3** (192.168.20.13) so it can reach hosts outside VLAN 20',
      details: 'PC3 answers pings to 192.168.20.1 but cannot reach anything beyond its own subnet. Run `ipconfig` on PC3 and compare its Default Gateway with R1\'s sub-interface address (`show ip interface brief` on R1). A PC is fixed in its own IP settings, not with IOS commands.',
      hint: '`ipconfig` on PC3 and `show ip interface brief` on R1.',
      checks: [
        { type: 'host', device: 'PC3', gateway: '192.168.20.1' },
        { type: 'ping', from: 'PC3', to: '192.168.10.11' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify end to end: every warehouse PC reaches its gateway, the office and each other',
      details: 'Ping 192.168.20.1 from each warehouse PC. Then ping PC5 → PC2 (same VLAN across the trunk, no router involved) and PC4 → PC1 (routed by R1, crossing the trunk twice). In `show interfaces trunk` on SW2, VLANs 10, 20 and 99 must all be in the spanning-tree forwarding state.',
      hint: 'If one ping still fails, repeat the bottom-up checks for that PC: port, VLAN, trunk, then IP settings.',
      checks: [
        { type: 'ping', from: 'PC2', to: '192.168.20.1' },
        { type: 'ping', from: 'PC3', to: '192.168.20.1' },
        { type: 'ping', from: 'PC4', to: '192.168.20.1' },
        { type: 'ping', from: 'PC5', to: '192.168.20.1' },
        { type: 'ping', from: 'PC5', to: '192.168.20.12' },
        { type: 'ping', from: 'PC4', to: '192.168.10.11' },
        { type: 'show', device: 'SW2', command: 'show interfaces trunk', pattern: 'not pruned\\s*\\nGi0/1\\s+10,20,99' },
      ],
    },
    {
      id: 'save',
      title: 'Save the corrected configuration on **SW1** and **SW2**',
      details: 'Fixes that live only in the running-config disappear at the next reload. Confirm with `show startup-config` that your changes were really written. R1 was never changed, so it needs nothing.',
      hint: '`copy running-config startup-config` or `write memory`.',
      checks: [
        { type: 'saved', device: 'SW1' },
        { type: 'saved', device: 'SW2' },
        { type: 'show', device: 'SW1', command: 'show startup-config', pattern: 'switchport trunk native vlan 99' },
        { type: 'show', device: 'SW2', command: 'show startup-config', pattern: 'switchport trunk allowed vlan 10,20,99' },
      ],
    },
  ],
  solution: {
    SW1: [
      'enable',
      'configure terminal',
      'interface fa0/1',
      ' switchport access vlan 20',
      'interface g0/1',
      ' switchport trunk native vlan 99',
      ' do write memory',
      ' end',
    ].join('\n'),
    SW2: [
      'enable',
      'configure terminal',
      'interface fa0/3',
      ' no shutdown',
      'interface g0/1',
      ' switchport trunk allowed vlan add 20',
      ' do write memory',
      ' end',
    ].join('\n'),
    PC3: { ip: '192.168.20.13', mask: '255.255.255.0', gateway: '192.168.20.1' },
  },
};

export default lab;
