import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-stp-root-tuning',
  title: 'STP Root Placement and Protection with Rapid PVST+',
  summary: 'Move a three-switch triangle to Rapid PVST+, place the root bridges per VLAN for load sharing, and protect the edge with PortFast, BPDU guard and root guard.',
  difficulty: 2,
  minutes: 50,
  lessons: ['stp-fundamentals', 'rapid-pvst', 'stp-protection'],
  scenario:
    'Westfield Library runs a small switched core. **SW1** and **SW2** are the distribution switches and **SW3** is the access switch of the reading room, wired in a triangle with Gigabit trunks. Everything still runs default PVST+ with default priorities, so the root bridge is simply the switch with the lowest MAC address, which could even be the access switch. VLAN 10 (USERS) carries the staff PCs and the catalog server SRV1; trunks and access ports are already configured.\n\n' +
    'Make the design predictable. Move to **Rapid PVST+**, make SW1 the root bridge for VLAN 1 and SW2 the root bridge for VLAN 10, each acting as backup root for the other VLAN. SW3 then uses a different uplink as its root path for each VLAN (load sharing) and keeps the other uplink ready as an alternate port.\n\n' +
    'Then protect the edge: PortFast and BPDU guard on every access port, and root guard on the distribution ports that face SW3. A visitor has plugged a small desktop switch (SW4) into the wall socket on SW3 Fa0/3: BPDU guard must shut that port down as soon as SW4\'s BPDUs arrive, while the PCs stay connected.',
  devices: [
    {
      id: 'SW1',
      model: 'c2960',
      x: 2,
      y: 2,
      config: [
        'vlan 10',
        ' name USERS',
        'interface GigabitEthernet0/1',
        ' description Trunk to SW2 G0/1',
        ' switchport mode trunk',
        'interface GigabitEthernet0/2',
        ' description Trunk to SW3 G0/1',
        ' switchport mode trunk',
        'interface FastEthernet0/1',
        ' description SRV1 catalog server',
        ' switchport mode access',
        ' switchport access vlan 10',
      ].join('\n'),
    },
    {
      id: 'SW2',
      model: 'c2960',
      x: 10,
      y: 2,
      config: [
        'vlan 10',
        ' name USERS',
        'interface GigabitEthernet0/1',
        ' description Trunk to SW1 G0/1',
        ' switchport mode trunk',
        'interface GigabitEthernet0/2',
        ' description Trunk to SW3 G0/2',
        ' switchport mode trunk',
      ].join('\n'),
    },
    {
      id: 'SW3',
      model: 'c2960',
      x: 6,
      y: 4.5,
      config: [
        'vlan 10',
        ' name USERS',
        'interface GigabitEthernet0/1',
        ' description Trunk to SW1 G0/2',
        ' switchport mode trunk',
        'interface GigabitEthernet0/2',
        ' description Trunk to SW2 G0/2',
        ' switchport mode trunk',
        'interface FastEthernet0/1',
        ' description PC1',
        ' switchport mode access',
        ' switchport access vlan 10',
        'interface FastEthernet0/2',
        ' description PC2',
        ' switchport mode access',
        ' switchport access vlan 10',
        'interface FastEthernet0/3',
        ' description Reading-room wall socket',
        ' switchport mode access',
        ' switchport access vlan 10',
      ].join('\n'),
    },
    { id: 'SW4', model: 'c2960', x: 10, y: 6, label: 'SW4 (visitor)', locked: true },
    { id: 'SRV1', model: 'server', x: 2, y: 5.5, host: { ip: '192.168.10.100', mask: '255.255.255.0' } },
    { id: 'PC1', model: 'pc', x: 4.5, y: 6.5, host: { ip: '192.168.10.11', mask: '255.255.255.0' } },
    { id: 'PC2', model: 'pc', x: 7.5, y: 6.5, host: { ip: '192.168.10.12', mask: '255.255.255.0' } },
  ],
  links: [
    { a: 'SW1:g0/1', b: 'SW2:g0/1' },
    { a: 'SW1:g0/2', b: 'SW3:g0/1' },
    { a: 'SW2:g0/2', b: 'SW3:g0/2' },
    { a: 'SW1:fa0/1', b: 'SRV1:fa0' },
    { a: 'SW3:fa0/1', b: 'PC1:fa0' },
    { a: 'SW3:fa0/2', b: 'PC2:fa0' },
    { a: 'SW3:fa0/3', b: 'SW4:fa0/1' },
  ],
  tasks: [
    {
      id: 'rapid-pvst',
      title: 'Change SW1, SW2 and SW3 from PVST+ to Rapid PVST+',
      details: 'Rapid PVST+ (802.1w) is a global setting and every switch of the domain should run the same mode. Verify with `show spanning-tree summary`.',
      hint: '`spanning-tree mode ...` in global configuration mode.',
      checks: [
        { type: 'show', device: 'SW1', command: 'show spanning-tree summary', pattern: 'Switch is in rapid-pvst mode' },
        { type: 'show', device: 'SW2', command: 'show spanning-tree summary', pattern: 'Switch is in rapid-pvst mode' },
        { type: 'show', device: 'SW3', command: 'show spanning-tree summary', pattern: 'Switch is in rapid-pvst mode' },
      ],
    },
    {
      id: 'vlan1-root',
      title: 'Make SW1 the root bridge for VLAN 1 and SW2 the backup root bridge for VLAN 1',
      details: 'Use the macros `spanning-tree vlan 1 root primary` on SW1 and `spanning-tree vlan 1 root secondary` on SW2: they lower the priority below the default 32768 (24576 and 28672). SW3 then reaches the root directly through G0/1 (root port), and its G0/2 toward SW2 becomes the alternate port because SW2 has the better bridge ID on that segment. Check `show spanning-tree vlan 1` on all three switches.',
      hint: 'On SW3, `show spanning-tree vlan 1` lists the root port and the alternate (Altn) port.',
      checks: [
        { type: 'stpRoot', vlan: 1, device: 'SW1' },
        { type: 'show', device: 'SW2', command: 'show spanning-tree vlan 1', pattern: 'Bridge ID\\s+Priority\\s+28673' },
        { type: 'stpPort', device: 'SW2', vlan: 1, iface: 'Gi0/1', role: 'root', state: 'forwarding' },
        { type: 'stpPort', device: 'SW3', vlan: 1, iface: 'Gi0/1', role: 'root', state: 'forwarding' },
        { type: 'stpPort', device: 'SW3', vlan: 1, iface: 'Gi0/2', role: 'alternate', state: 'blocking' },
      ],
    },
    {
      id: 'vlan10-root',
      title: 'Load sharing: make SW2 the root bridge for VLAN 10 and SW1 the backup root bridge for VLAN 10',
      details: 'Use the same macros for VLAN 10 with the roles reversed. SW3 now reaches the VLAN 10 root through G0/2 and blocks G0/1, so each uplink is the root path of one VLAN and the alternate of the other.',
      hint: 'The two VLANs should show opposite port roles on SW3.',
      checks: [
        { type: 'stpRoot', vlan: 10, device: 'SW2' },
        { type: 'show', device: 'SW1', command: 'show spanning-tree vlan 10', pattern: 'Bridge ID\\s+Priority\\s+28682' },
        { type: 'stpPort', device: 'SW1', vlan: 10, iface: 'Gi0/1', role: 'root', state: 'forwarding' },
        { type: 'stpPort', device: 'SW3', vlan: 10, iface: 'Gi0/2', role: 'root', state: 'forwarding' },
        { type: 'stpPort', device: 'SW3', vlan: 10, iface: 'Gi0/1', role: 'alternate', state: 'blocking' },
      ],
    },
    {
      id: 'portfast-bpduguard',
      title: 'Enable PortFast and BPDU guard on every access port: SW3 Fa0/1, Fa0/2 and Fa0/3, and SW1 Fa0/1',
      details: 'PortFast moves a host port straight to forwarding; BPDU guard err-disables such a port when a BPDU arrives, because a host never sends one. The visitor\'s SW4 on Fa0/3 does send BPDUs, so that port must end up err-disabled while the PC ports stay up. Use the per-interface commands (`spanning-tree portfast`, `spanning-tree bpduguard enable`) or the global defaults (`spanning-tree portfast default` and `spanning-tree portfast bpduguard default`). Verify with `show spanning-tree interface fa0/1 detail` and `show interfaces status`.',
      hint: '`interface range fa0/1 - 3` saves typing on SW3.',
      checks: [
        { type: 'show', device: 'SW3', command: 'show spanning-tree interface Fa0/1 detail', pattern: 'in the portfast mode' },
        { type: 'show', device: 'SW3', command: 'show spanning-tree interface Fa0/1 detail', pattern: 'Bpdu guard is enabled' },
        { type: 'show', device: 'SW3', command: 'show spanning-tree interface Fa0/2 detail', pattern: 'in the portfast mode' },
        { type: 'show', device: 'SW3', command: 'show spanning-tree interface Fa0/2 detail', pattern: 'Bpdu guard is enabled' },
        { type: 'show', device: 'SW1', command: 'show spanning-tree interface Fa0/1 detail', pattern: 'in the portfast mode' },
        { type: 'show', device: 'SW1', command: 'show spanning-tree interface Fa0/1 detail', pattern: 'Bpdu guard is enabled' },
        { type: 'show', device: 'SW3', command: 'show interfaces status', pattern: '^Fa0/3\\s.*err-disabled' },
        { type: 'interface', device: 'SW3', iface: 'Fa0/1', status: 'up' },
        { type: 'interface', device: 'SW3', iface: 'Fa0/2', status: 'up' },
      ],
    },
    {
      id: 'root-guard',
      title: 'Enable root guard on SW1 G0/2 and SW2 G0/2, the ports that face the access switch SW3',
      details: 'Root guard puts a port into the root-inconsistent state when it receives a superior BPDU, so a misconfigured access switch can never take over as root. It belongs on designated ports facing switches that must never become root: `spanning-tree guard root`. The ports must stay designated and forwarding.',
      hint: 'Apply it on the distribution side of the link, not on SW3.',
      checks: [
        { type: 'config', device: 'SW1', section: 'interface GigabitEthernet0/2', pattern: '^ spanning-tree guard root$' },
        { type: 'config', device: 'SW2', section: 'interface GigabitEthernet0/2', pattern: '^ spanning-tree guard root$' },
        { type: 'stpPort', device: 'SW1', vlan: 1, iface: 'Gi0/2', role: 'designated', state: 'forwarding' },
        { type: 'stpPort', device: 'SW2', vlan: 10, iface: 'Gi0/2', role: 'designated', state: 'forwarding' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify that the network still works: PC1 and PC2 reach SRV1 and each other',
      details: 'VLAN 10 now follows SW3 G0/2 -> SW2 -> SW1 to reach SRV1 while the blocked G0/1 stays in reserve. If a ping fails, check that the PC ports were not err-disabled and that VLAN 10 is allowed on every trunk.',
      checks: [
        { type: 'ping', from: 'PC1', to: '192.168.10.100' },
        { type: 'ping', from: 'PC2', to: '192.168.10.100' },
        { type: 'ping', from: 'PC1', to: '192.168.10.12' },
      ],
    },
  ],
  solution: {
    SW1: [
      'enable',
      'configure terminal',
      'spanning-tree mode rapid-pvst',
      'spanning-tree vlan 1 root primary',
      'spanning-tree vlan 10 root secondary',
      'interface fa0/1',
      ' spanning-tree portfast',
      ' spanning-tree bpduguard enable',
      'interface g0/2',
      ' spanning-tree guard root',
      ' end',
    ].join('\n'),
    SW2: [
      'enable',
      'configure terminal',
      'spanning-tree mode rapid-pvst',
      'spanning-tree vlan 10 root primary',
      'spanning-tree vlan 1 root secondary',
      'interface g0/2',
      ' spanning-tree guard root',
      ' end',
    ].join('\n'),
    SW3: [
      'enable',
      'configure terminal',
      'spanning-tree mode rapid-pvst',
      'interface range fa0/1 - 3',
      ' spanning-tree portfast',
      ' spanning-tree bpduguard enable',
      ' end',
    ].join('\n'),
  },
};

export default lab;
