import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-capstone-branch-office',
  title: 'Capstone: Build a Branch Office',
  summary:
    'Build a branch office end to end: VLANs and router-on-a-stick, OSPF to headquarters, DHCP for the LAN, PAT to the ISP, an ACL that protects the server VLAN and SSH-only management.',
  difficulty: 3,
  minutes: 60,
  lessons: ['inter-vlan-routing', 'ospf-config', 'dhcp', 'nat', 'extended-acls', 'ssh-remote-access'],
  scenario:
    '**Contoso Retail** is opening a new branch office. The branch router **BR1** and the access switch **SW1** are racked and cabled, and the carrier has delivered two circuits: a private link to headquarters (**HQ1**, 10.0.0.0/30) and an Internet handoff from the ISP (198.51.100.0/30). Only the physical addressing of BR1\'s two WAN interfaces has been provisioned; everything else is yours to build. HQ1 and the ISP are already configured and must not be changed.\n\n' +
    'The branch has three VLANs: **STAFF** (VLAN 10, 192.168.10.0/24, DHCP), **GUEST** (VLAN 20, 192.168.20.0/24, DHCP) and **SERVERS** (VLAN 30, 192.168.30.0/24) with the file server SRV1 at a static 192.168.30.10. BR1 routes between them with router-on-a-stick, exchanges routes with HQ over **OSPF area 0** (HQ1 runs router ID 1.1.1.1 and serves the HQ LAN 10.1.0.0/24 with the intranet server HQ-SRV at 10.1.0.10) and reaches the Internet through the ISP (198.51.100.1, simulated Internet host 8.8.8.8) with **PAT** on its WAN address.\n\n' +
    'Security rules: only staff may reach the server VLAN, and only for web (TCP 80 and 443) and ping; guests, HQ and everything else are blocked. BR1 must be managed with **SSH version 2 only** (domain *contoso.example*, user **netadmin**, password **Wiz@rd2026**). Build it, verify it end to end and save the configuration.',
  devices: [
    { id: 'PC1', model: 'pc', x: 0.8, y: 1, label: 'PC1 (staff)', host: { dhcp: true } },
    { id: 'PC2', model: 'pc', x: 0.8, y: 3.5, label: 'PC2 (guest)', host: { dhcp: true } },
    { id: 'SRV1', model: 'server', x: 0.8, y: 6, label: 'SRV1 (files)', host: { ip: '192.168.30.10', mask: '255.255.255.0', gateway: '192.168.30.1' }, services: { http: true, https: true } },
    { id: 'SW1', model: 'c2960', x: 3.6, y: 3.5 },
    {
      id: 'BR1',
      model: 'isr2911',
      x: 6.6,
      y: 3.5,
      config: [
        'interface GigabitEthernet0/1',
        ' description WAN to HQ1',
        ' ip address 10.0.0.2 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description WAN to ISP',
        ' ip address 198.51.100.2 255.255.255.252',
        ' no shutdown',
      ].join('\n'),
    },
    {
      id: 'HQ1',
      model: 'isr4321',
      x: 9.4,
      y: 1.2,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description WAN to branch BR1',
        ' ip address 10.0.0.1 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description HQ LAN',
        ' ip address 10.1.0.1 255.255.255.0',
        ' no shutdown',
        'router ospf 1',
        ' router-id 1.1.1.1',
        ' network 10.0.0.0 0.0.0.3 area 0',
        ' network 10.1.0.0 0.0.0.255 area 0',
        ' passive-interface GigabitEthernet0/0/1',
      ].join('\n'),
    },
    {
      id: 'HQSRV',
      model: 'server',
      x: 11.4,
      y: 1.2,
      label: 'HQ-SRV',
      host: { ip: '10.1.0.10', mask: '255.255.255.0', gateway: '10.1.0.1' },
      services: { http: true, https: true, dns: [{ name: 'intranet.contoso.example', ip: '10.1.0.10' }] },
    },
    {
      id: 'ISP',
      model: 'isr4321',
      x: 9.4,
      y: 5.8,
      locked: true,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Customer Contoso branch',
        ' ip address 198.51.100.1 255.255.255.252',
        ' no shutdown',
        'interface Loopback0',
        ' description Internet',
        ' ip address 8.8.8.8 255.255.255.255',
      ].join('\n'),
    },
  ],
  links: [
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'SW1:fa0/3', b: 'SRV1:fa0' },
    { a: 'SW1:g0/1', b: 'BR1:g0/0' },
    { a: 'BR1:g0/1', b: 'HQ1:g0/0/0' },
    { a: 'HQ1:g0/0/1', b: 'HQSRV:fa0' },
    { a: 'BR1:g0/2', b: 'ISP:g0/0/0' },
  ],
  tasks: [
    {
      id: 'switch',
      title: 'Build the Layer 2 foundation on **SW1**: VLANs 10 **STAFF**, 20 **GUEST**, 30 **SERVERS**, access ports Fa0/1 → 10, Fa0/2 → 20, Fa0/3 → 30, and a trunk on **Gi0/1** that carries only VLANs 10, 20 and 30',
      details: 'PC1 (staff) is on Fa0/1, PC2 (guest) on Fa0/2 and the file server SRV1 on Fa0/3; Gi0/1 goes to BR1. Make the trunk static (`switchport mode trunk`) and prune it with `switchport trunk allowed vlan`. Verify with `show vlan brief` and `show interfaces trunk`.',
      hint: '`vlan 10` → `name STAFF`; then `switchport mode access` / `switchport access vlan` per port; `switchport mode trunk` on Gi0/1.',
      checks: [
        { type: 'vlan', device: 'SW1', vlan: 10, name: 'STAFF' },
        { type: 'vlan', device: 'SW1', vlan: 20, name: 'GUEST' },
        { type: 'vlan', device: 'SW1', vlan: 30, name: 'SERVERS' },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/1', mode: 'access', accessVlan: 10 },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/2', mode: 'access', accessVlan: 20 },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/3', mode: 'access', accessVlan: 30 },
        { type: 'switchport', device: 'SW1', iface: 'Gi0/1', mode: 'trunk', allowed: '10,20,30' },
      ],
    },
    {
      id: 'roas',
      title: 'Configure router-on-a-stick on **BR1 G0/0**: sub-interfaces **.10**, **.20** and **.30** with gateways **192.168.10.1**, **192.168.20.1** and **192.168.30.1** (/24)',
      details: 'The physical interface is shut down by default and carries no address; each sub-interface needs `encapsulation dot1Q <vlan>` **before** its IP address. A ping from SRV1 to its gateway proves the VLAN 30 path end to end.',
      hint: '`interface g0/0` → `no shutdown`; `interface g0/0.10` → `encapsulation dot1Q 10` → `ip address …`',
      checks: [
        { type: 'interface', device: 'BR1', iface: 'Gi0/0.10', ip: '192.168.10.1', mask: '255.255.255.0', status: 'up' },
        { type: 'interface', device: 'BR1', iface: 'Gi0/0.20', ip: '192.168.20.1', mask: '255.255.255.0', status: 'up' },
        { type: 'interface', device: 'BR1', iface: 'Gi0/0.30', ip: '192.168.30.1', mask: '255.255.255.0', status: 'up' },
        { type: 'ping', from: 'SRV1', to: '192.168.30.1' },
      ],
    },
    {
      id: 'dhcp',
      title: 'Serve DHCP from BR1 for STAFF and GUEST: gateway = BR1\'s address in each VLAN, DNS server **10.1.0.10**, first 20 addresses of each subnet excluded',
      details: 'Create one pool per VLAN (for example STAFF and GUEST) and reserve .1–.20 with `ip dhcp excluded-address` so the router and future static devices never collide with a lease. PC1 and PC2 are DHCP clients and lease an address as soon as a pool is active, so a lease taken before `default-router` and `dns-server` were configured has no gateway or DNS: use `ipconfig /release` and `ipconfig /renew` on the PC. Check `show ip dhcp binding` and `ipconfig /all`.',
      hint: '`ip dhcp excluded-address` → `ip dhcp pool` → `network`, `default-router`, `dns-server`',
      checks: [
        { type: 'host', device: 'PC1', dhcp: true, inSubnet: '192.168.10.0/24', gateway: '192.168.10.1', dns: '10.1.0.10' },
        { type: 'host', device: 'PC2', dhcp: true, inSubnet: '192.168.20.0/24', gateway: '192.168.20.1', dns: '10.1.0.10' },
        { type: 'show', device: 'BR1', command: 'show ip dhcp binding', pattern: '^192\\.168\\.10\\.(2[1-9]|[3-9]\\d|1\\d\\d|2[0-4]\\d)\\s' },
        { type: 'show', device: 'BR1', command: 'show ip dhcp binding', pattern: '^192\\.168\\.20\\.(2[1-9]|[3-9]\\d|1\\d\\d|2[0-4]\\d)\\s' },
      ],
    },
    {
      id: 'ospf',
      title: 'Run **OSPF area 0** on BR1 with router ID **2.2.2.2**: advertise the 10.0.0.0/30 WAN link and the three branch subnets, and keep hellos off the LAN sub-interfaces',
      details: 'HQ1 is already configured. Once the adjacency is FULL, BR1 must learn the HQ LAN 10.1.0.0/24 and HQ1 must learn all three branch subnets. Do **not** run OSPF toward the ISP. Passive interfaces keep a network in OSPF without sending hellos; `show ip protocols` lists them.',
      hint: '`router ospf 1` → `router-id` → `network … area 0`; `passive-interface default` + `no passive-interface g0/1` is the short way.',
      checks: [
        { type: 'ospfRouterId', device: 'BR1', rid: '2.2.2.2' },
        { type: 'ospfNeighbor', device: 'BR1', neighbor: '1.1.1.1', state: 'FULL' },
        { type: 'route', device: 'BR1', prefix: '10.1.0.0/24', source: 'O', nextHop: '10.0.0.1' },
        { type: 'route', device: 'HQ1', prefix: '192.168.10.0/24', source: 'O', nextHop: '10.0.0.2' },
        { type: 'route', device: 'HQ1', prefix: '192.168.20.0/24', source: 'O', nextHop: '10.0.0.2' },
        { type: 'route', device: 'HQ1', prefix: '192.168.30.0/24', source: 'O', nextHop: '10.0.0.2' },
        { type: 'show', device: 'BR1', command: 'show ip protocols', pattern: 'Passive Interface\\(s\\):[\\s\\S]*GigabitEthernet0/0\\.10' },
        { type: 'show', device: 'BR1', command: 'show ip protocols', pattern: 'Passive Interface\\(s\\):[\\s\\S]*GigabitEthernet0/0\\.30' },
      ],
    },
    {
      id: 'pat',
      title: 'Give staff and guests Internet access: default route to the ISP (**198.51.100.1**) and PAT of the STAFF and GUEST subnets behind BR1\'s ISP-facing address on **G0/2**',
      details: 'Mark the STAFF and GUEST sub-interfaces `ip nat inside` and G0/2 `ip nat outside`, permit 192.168.10.0/24 and 192.168.20.0/24 in an access list and translate it with `overload` on the G0/2 address. The server VLAN has no business on the Internet, so it stays out of NAT. Traffic to HQ leaves through G0/1, which is not a NAT interface, so HQ keeps seeing the real branch addresses. Test with a ping to 8.8.8.8.',
      hint: '`ip nat inside source list <acl> interface g0/2 overload` and `ip route 0.0.0.0 0.0.0.0 <next hop>`',
      checks: [
        { type: 'route', device: 'BR1', prefix: '0.0.0.0/0', source: 'S*', nextHop: '198.51.100.1' },
        { type: 'show', device: 'BR1', command: 'show ip nat statistics', pattern: 'Outside interfaces:\\s*\\n\\s*GigabitEthernet0/2' },
        { type: 'ping', from: 'PC1', to: '8.8.8.8' },
        { type: 'ping', from: 'PC2', to: '8.8.8.8' },
      ],
    },
    {
      id: 'acl',
      title: 'Protect the server VLAN with an extended ACL on BR1: staff (192.168.10.0/24) may reach SRV1 (**192.168.30.10**) on TCP **80** and **443** and by ping; guests, HQ and everything else are blocked',
      details: 'An ACL placed on the **outbound** side of G0/0.30 sees every packet headed for VLAN 30 from any source, so one list protects the VLAN from guests, HQ and the Internet alike. Keep the most specific permits first and remember the implicit `deny ip any any` at the end. `show access-lists` shows per-line match counters.',
      hint: '`ip access-list extended <name>` → `permit tcp <source> <wildcard> host <server> eq <port>` → `ip access-group <name> out` on the server sub-interface.',
      checks: [
        { type: 'traffic', from: 'PC1', to: '192.168.30.10', proto: 'tcp', port: 80 },
        { type: 'traffic', from: 'PC1', to: '192.168.30.10', proto: 'tcp', port: 443 },
        { type: 'ping', from: 'PC1', to: '192.168.30.10' },
        { type: 'traffic', from: 'PC1', to: '192.168.30.10', proto: 'tcp', port: 22, expect: false },
        { type: 'traffic', from: 'PC2', to: '192.168.30.10', proto: 'tcp', port: 80, expect: false },
        { type: 'ping', from: 'PC2', to: '192.168.30.10', expect: false },
        { type: 'traffic', from: 'HQSRV', to: '192.168.30.10', proto: 'tcp', port: 80, expect: false },
      ],
    },
    {
      id: 'ssh',
      title: 'Allow only SSH version 2 for management of BR1: domain **contoso.example**, user **netadmin** / **Wiz@rd2026**, 2048-bit RSA keys, VTY lines with local login and no Telnet',
      details: 'SSH needs a hostname other than Router, a domain name and an RSA key pair. Then restrict `line vty 0 4` to `transport input ssh` with `login local`. Prove it from HQ-SRV: SSH to BR1\'s WAN address 10.0.0.2 must work and Telnet must be refused.',
      hint: '`ip domain-name` → `username … secret …` → `crypto key generate rsa modulus 2048` → `ip ssh version 2` → `line vty 0 4`',
      checks: [
        { type: 'login', from: 'HQSRV', to: '10.0.0.2', protocol: 'ssh', username: 'netadmin', password: 'Wiz@rd2026' },
        { type: 'login', from: 'HQSRV', to: '10.0.0.2', protocol: 'telnet', username: 'netadmin', password: 'Wiz@rd2026', expect: false },
        { type: 'show', device: 'BR1', command: 'show ip ssh', pattern: 'SSH Enabled - version 2\\.0' },
      ],
    },
    {
      id: 'verify-save',
      title: 'Verify the branch end to end and save the configuration on **BR1** and **SW1**',
      details: 'Staff must reach HQ-SRV by address and by name (intranet.contoso.example) and HQ-SRV must reach staff PCs back; the Internet must answer both PCs. Finish with `copy running-config startup-config` on both devices and confirm with `show startup-config`.',
      hint: 'If a name does not resolve, check the DNS server your DHCP lease handed out (`ipconfig /all`).',
      checks: [
        { type: 'ping', from: 'PC1', to: '10.1.0.10' },
        { type: 'resolve', from: 'PC1', name: 'intranet.contoso.example', ip: '10.1.0.10' },
        { type: 'ping', from: 'HQSRV', to: '192.168.10.1' },
        { type: 'ping', from: 'PC1', to: '8.8.8.8' },
        { type: 'ping', from: 'PC2', to: '8.8.8.8' },
        { type: 'saved', device: 'BR1' },
        { type: 'saved', device: 'SW1' },
        { type: 'show', device: 'BR1', command: 'show startup-config', pattern: 'ip nat inside source list' },
        { type: 'show', device: 'SW1', command: 'show startup-config', pattern: 'switchport trunk allowed vlan 10,20,30' },
      ],
    },
  ],
  solution: {
    SW1: [
      'enable',
      'configure terminal',
      'vlan 10',
      ' name STAFF',
      'vlan 20',
      ' name GUEST',
      'vlan 30',
      ' name SERVERS',
      ' exit',
      'interface fa0/1',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface fa0/2',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface fa0/3',
      ' switchport mode access',
      ' switchport access vlan 30',
      'interface g0/1',
      ' switchport mode trunk',
      ' switchport trunk allowed vlan 10,20,30',
      ' exit',
      'do write memory',
      'end',
    ].join('\n'),
    BR1: [
      'enable',
      'configure terminal',
      'interface g0/0',
      ' no shutdown',
      'interface g0/0.10',
      ' description STAFF',
      ' encapsulation dot1Q 10',
      ' ip address 192.168.10.1 255.255.255.0',
      ' ip nat inside',
      'interface g0/0.20',
      ' description GUEST',
      ' encapsulation dot1Q 20',
      ' ip address 192.168.20.1 255.255.255.0',
      ' ip nat inside',
      'interface g0/0.30',
      ' description SERVERS',
      ' encapsulation dot1Q 30',
      ' ip address 192.168.30.1 255.255.255.0',
      ' ip access-group SERVERS-IN out',
      'interface g0/2',
      ' ip nat outside',
      ' exit',
      'ip dhcp excluded-address 192.168.10.1 192.168.10.20',
      'ip dhcp excluded-address 192.168.20.1 192.168.20.20',
      'ip dhcp pool STAFF',
      ' default-router 192.168.10.1',
      ' dns-server 10.1.0.10',
      ' network 192.168.10.0 255.255.255.0',
      'ip dhcp pool GUEST',
      ' default-router 192.168.20.1',
      ' dns-server 10.1.0.10',
      ' network 192.168.20.0 255.255.255.0',
      ' exit',
      'router ospf 1',
      ' router-id 2.2.2.2',
      ' network 10.0.0.0 0.0.0.3 area 0',
      ' network 192.168.10.0 0.0.0.255 area 0',
      ' network 192.168.20.0 0.0.0.255 area 0',
      ' network 192.168.30.0 0.0.0.255 area 0',
      ' passive-interface default',
      ' no passive-interface g0/1',
      ' exit',
      'ip route 0.0.0.0 0.0.0.0 198.51.100.1',
      'ip access-list standard NAT-LAN',
      ' permit 192.168.10.0 0.0.0.255',
      ' permit 192.168.20.0 0.0.0.255',
      ' exit',
      'ip nat inside source list NAT-LAN interface g0/2 overload',
      'ip access-list extended SERVERS-IN',
      ' permit tcp 192.168.10.0 0.0.0.255 host 192.168.30.10 eq 80',
      ' permit tcp 192.168.10.0 0.0.0.255 host 192.168.30.10 eq 443',
      ' permit icmp 192.168.10.0 0.0.0.255 host 192.168.30.10',
      ' exit',
      'ip domain-name contoso.example',
      'username netadmin secret Wiz@rd2026',
      'crypto key generate rsa modulus 2048',
      'ip ssh version 2',
      'line vty 0 4',
      ' login local',
      ' transport input ssh',
      ' exit',
      'do write memory',
      'end',
    ].join('\n'),
  },
};

export default lab;
