import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-dhcp-server-relay',
  title: 'DHCP Server and Relay Agent',
  summary: 'Turn R1 into the DHCP server for two VLANs and a remote branch LAN: excluded addresses, pools with gateway and DNS server, and ip helper-address on the branch router.',
  difficulty: 2,
  minutes: 40,
  lessons: ['dhcp'],
  scenario:
    'Wizard Corp runs two departments from the head office: **VLAN 10 SALES** (192.168.10.0/24) and **VLAN 20 ENGINEERING** (192.168.20.0/24). R1 routes them with router-on-a-stick (G0/0/0.10 and G0/0/0.20 towards SW1). A small branch office on **192.168.30.0/24** sits behind R2, which connects to R1 over 10.0.0.0/30. VLANs, trunking, interface addresses and static routes are already in place.\n\n' +
    'Until now every PC was addressed by hand. Ahead of the change window all four PCs were switched to DHCP, but nothing answers their requests yet, so none of them has a usable address.\n\n' +
    'Make **R1 the DHCP server for all three LANs**. Keep the first ten addresses of every subnet (.1 to .10) out of the pools for routers, printers and servers, hand out the correct default gateway and the DNS server **8.8.8.8**, and let the branch LAN, which is on a different subnet from the server, reach the pool through a relay agent on R2. After each change run `ipconfig /renew` on the affected PCs.',
  devices: [
    {
      id: 'SW1',
      model: 'c2960',
      x: 2.5,
      y: 2.5,
      config: [
        'vlan 10',
        ' name SALES',
        'vlan 20',
        ' name ENGINEERING',
        'interface FastEthernet0/1',
        ' switchport mode access',
        ' switchport access vlan 10',
        'interface FastEthernet0/2',
        ' switchport mode access',
        ' switchport access vlan 20',
        'interface GigabitEthernet0/1',
        ' description Trunk to R1',
        ' switchport mode trunk',
      ].join('\n'),
    },
    {
      id: 'R1',
      model: 'isr4321',
      x: 6,
      y: 2.5,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Trunk to SW1',
        ' no shutdown',
        'interface GigabitEthernet0/0/0.10',
        ' description SALES gateway',
        ' encapsulation dot1Q 10',
        ' ip address 192.168.10.1 255.255.255.0',
        'interface GigabitEthernet0/0/0.20',
        ' description ENGINEERING gateway',
        ' encapsulation dot1Q 20',
        ' ip address 192.168.20.1 255.255.255.0',
        'interface GigabitEthernet0/0/1',
        ' description Link to branch R2',
        ' ip address 10.0.0.1 255.255.255.252',
        ' no shutdown',
        'ip route 192.168.30.0 255.255.255.0 10.0.0.2',
      ].join('\n'),
    },
    {
      id: 'R2',
      model: 'isr4321',
      x: 9,
      y: 2.5,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to HQ R1',
        ' ip address 10.0.0.2 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description Branch LAN',
        ' ip address 192.168.30.1 255.255.255.0',
        ' no shutdown',
        'ip route 0.0.0.0 0.0.0.0 10.0.0.1',
      ].join('\n'),
    },
    { id: 'SW2', model: 'c2960', x: 9, y: 4.5 },
    { id: 'PC1', model: 'pc', x: 1, y: 5.5, host: { dhcp: true } },
    { id: 'PC2', model: 'pc', x: 4, y: 5.5, host: { dhcp: true } },
    { id: 'PC3', model: 'pc', x: 7.2, y: 6.5, host: { dhcp: true } },
    { id: 'PC4', model: 'pc', x: 10.8, y: 6.5, host: { dhcp: true } },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'SW1:g0/1' },
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'R1:g0/0/1', b: 'R2:g0/0/0' },
    { a: 'R2:g0/0/1', b: 'SW2:g0/1' },
    { a: 'SW2:fa0/1', b: 'PC3:fa0' },
    { a: 'SW2:fa0/2', b: 'PC4:fa0' },
  ],
  tasks: [
    {
      id: 'excluded',
      title: 'Exclude the first ten addresses (.1 to .10) of 192.168.10.0/24, 192.168.20.0/24 and 192.168.30.0/24 from DHCP on R1',
      details: 'Routers, printers and servers use those addresses statically, so the DHCP server must never lease them. Excluded ranges are global commands (`ip dhcp excluded-address LOW HIGH`), one range per subnet. Check them with `show running-config | include excluded`.',
      hint: '`ip dhcp excluded-address 192.168.10.1 192.168.10.10`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^ip dhcp excluded-address 192\\.168\\.10\\.1 192\\.168\\.10\\.10$' },
        { type: 'config', device: 'R1', pattern: '^ip dhcp excluded-address 192\\.168\\.20\\.1 192\\.168\\.20\\.10$' },
        { type: 'config', device: 'R1', pattern: '^ip dhcp excluded-address 192\\.168\\.30\\.1 192\\.168\\.30\\.10$' },
      ],
    },
    {
      id: 'vlan-pools',
      title: 'Create DHCP pools **SALES** (192.168.10.0/24) and **ENGINEERING** (192.168.20.0/24) on R1 with default gateway .1 and DNS server 8.8.8.8',
      details: '`ip dhcp pool NAME` enters the `(dhcp-config)#` mode. Inside the pool use `network ADDRESS MASK`, `default-router ADDRESS` and `dns-server ADDRESS`. R1 picks the pool whose network matches the subnet of the interface the request arrived on (G0/0/0.10 for VLAN 10, G0/0/0.20 for VLAN 20). Verify with `show ip dhcp pool` or `show running-config | section dhcp`.',
      hint: '`ip dhcp pool SALES` → `network 192.168.10.0 255.255.255.0` → `default-router 192.168.10.1` → `dns-server 8.8.8.8`',
      checks: [
        { type: 'config', device: 'R1', section: 'ip dhcp pool SALES', pattern: '^ network 192\\.168\\.10\\.0 255\\.255\\.255\\.0$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool SALES', pattern: '^ default-router 192\\.168\\.10\\.1$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool SALES', pattern: '^ dns-server 8\\.8\\.8\\.8$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool ENGINEERING', pattern: '^ network 192\\.168\\.20\\.0 255\\.255\\.255\\.0$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool ENGINEERING', pattern: '^ default-router 192\\.168\\.20\\.1$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool ENGINEERING', pattern: '^ dns-server 8\\.8\\.8\\.8$' },
      ],
    },
    {
      id: 'vlan-leases',
      title: 'Renew PC1 (VLAN 10) and PC2 (VLAN 20) and confirm that each leases the first free address of its own subnet',
      details: 'On each PC open the command prompt and run `ipconfig /renew`, then `ipconfig /all` to see address, gateway and DNS server. Because .1 to .10 are excluded, the first lease in each subnet must be **.11**. On R1, `show ip dhcp binding` lists the leases. Finally prove that the leased gateway works: PC1 must reach PC2 through R1.',
      hint: 'No lease? Compare the pool network with the subnet of the matching R1 subinterface (`show ip interface brief`) and make sure the exclusions do not cover the whole pool.',
      checks: [
        { type: 'host', device: 'PC1', inSubnet: '192.168.10.0/24', gateway: '192.168.10.1', dns: '8.8.8.8' },
        { type: 'host', device: 'PC2', inSubnet: '192.168.20.0/24', gateway: '192.168.20.1', dns: '8.8.8.8' },
        { type: 'show', device: 'R1', command: 'show ip dhcp binding', pattern: '192\\.168\\.10\\.11\\s' },
        { type: 'show', device: 'R1', command: 'show ip dhcp binding', pattern: '192\\.168\\.20\\.11\\s' },
        { type: 'ping', from: 'PC1', to: 'PC2' },
      ],
    },
    {
      id: 'branch-pool',
      title: 'Create DHCP pool **BRANCH** on R1 for 192.168.30.0/24 with default gateway 192.168.30.1 and DNS server 8.8.8.8',
      details: 'R1 has no interface in 192.168.30.0/24, so it cannot choose this pool by the incoming interface. For a relayed request R1 looks at the **giaddr** field (the address of the relay interface on R2, 192.168.30.1) and uses the pool that contains it. The default gateway handed to the clients is still R2\'s LAN address.',
      hint: 'Same three pool commands as before, with the branch network and gateway.',
      checks: [
        { type: 'config', device: 'R1', section: 'ip dhcp pool BRANCH', pattern: '^ network 192\\.168\\.30\\.0 255\\.255\\.255\\.0$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool BRANCH', pattern: '^ default-router 192\\.168\\.30\\.1$' },
        { type: 'config', device: 'R1', section: 'ip dhcp pool BRANCH', pattern: '^ dns-server 8\\.8\\.8\\.8$' },
      ],
    },
    {
      id: 'relay',
      title: 'Make R2 relay the branch DHCP broadcasts to the server 10.0.0.1, then renew PC3 and PC4',
      details: 'DHCP discovers are broadcasts and routers do not forward broadcasts. `ip helper-address` turns them into unicasts for the server and stamps the receiving interface address into giaddr. Configure it on the interface that **receives** the client broadcasts (the branch LAN, G0/0/1), not on the link towards R1. Then run `ipconfig /renew` on PC3 and PC4.',
      hint: '`interface g0/0/1` → `ip helper-address 10.0.0.1`',
      checks: [
        { type: 'config', device: 'R2', section: 'interface GigabitEthernet0/0/1', pattern: '^ ip helper-address 10\\.0\\.0\\.1$' },
        { type: 'host', device: 'PC3', inSubnet: '192.168.30.0/24', gateway: '192.168.30.1', dns: '8.8.8.8' },
        { type: 'host', device: 'PC4', inSubnet: '192.168.30.0/24', gateway: '192.168.30.1', dns: '8.8.8.8' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify all four leases on R1 and test end-to-end connectivity between the branch and head office',
      details: '`show ip dhcp binding` must list four automatic bindings: .11 for PC1 and PC2 in their own subnets, and .11 and .12 for the two branch PCs. The branch PCs reach head office through R2 and R1 using the gateway they were leased, and R1 reaches the branch through its static route.',
      hint: '`show ip dhcp binding` on R1; `ping` from a PC command prompt.',
      checks: [
        { type: 'show', device: 'R1', command: 'show ip dhcp binding', pattern: '192\\.168\\.30\\.11\\s[\\s\\S]*192\\.168\\.30\\.12\\s' },
        { type: 'ping', from: 'PC3', to: 'PC1' },
        { type: 'ping', from: 'PC4', to: 'PC2' },
        { type: 'ping', from: 'PC1', to: 'PC3' },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'configure terminal',
      'ip dhcp excluded-address 192.168.10.1 192.168.10.10',
      'ip dhcp excluded-address 192.168.20.1 192.168.20.10',
      'ip dhcp excluded-address 192.168.30.1 192.168.30.10',
      'ip dhcp pool SALES',
      ' network 192.168.10.0 255.255.255.0',
      ' default-router 192.168.10.1',
      ' dns-server 8.8.8.8',
      ' exit',
      'ip dhcp pool ENGINEERING',
      ' network 192.168.20.0 255.255.255.0',
      ' default-router 192.168.20.1',
      ' dns-server 8.8.8.8',
      ' exit',
      'ip dhcp pool BRANCH',
      ' network 192.168.30.0 255.255.255.0',
      ' default-router 192.168.30.1',
      ' dns-server 8.8.8.8',
      ' end',
    ].join('\n'),
    R2: [
      'enable',
      'configure terminal',
      'interface GigabitEthernet0/0/1',
      ' ip helper-address 10.0.0.1',
      ' end',
    ].join('\n'),
    PC1: { dhcp: true },
    PC2: { dhcp: true },
    PC3: { dhcp: true },
    PC4: { dhcp: true },
  },
};

export default lab;
