import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-syslog-snmp',
  title: 'Syslog and SNMPv2c Monitoring',
  summary: 'Forward logs to a syslog server, tune severity levels and local buffers, then lock down SNMPv2c with read-only and read-write communities and send traps to the NMS.',
  difficulty: 2,
  minutes: 40,
  lessons: ['syslog', 'snmp'],
  scenario:
    'The Wizard Corp network operations team has built a management server, **SRV1 (192.168.1.50)**, that runs both a syslog collector and an SNMP manager. R1 (the office router) and SW1 (the access switch) have to report to it. R2 is the branch router on the other side of R1 and is already done.\n\n' +
    'A recent audit found two problems on R1: log messages carry only the device uptime, so they cannot be matched against other systems, and the factory SNMP community strings **public** (read-only) and **private** (read-write) are still configured.\n\n' +
    'Send warnings and worse to the syslog server with proper timestamps, keep a local buffer for troubleshooting, replace the default SNMP communities with your own (read-write restricted to the NMS), and make R1 and SW1 send SNMPv2c traps to SRV1.',
  devices: [
    {
      id: 'SRV1',
      model: 'server',
      x: 1.5,
      y: 1.4,
      host: { ip: '192.168.1.50', mask: '255.255.255.0', gateway: '192.168.1.1' },
      services: { syslog: true },
    },
    {
      id: 'SW1',
      model: 'c2960',
      x: 4,
      y: 3.5,
      config: ['interface Vlan1', ' ip address 192.168.1.2 255.255.255.0', ' no shutdown', 'ip default-gateway 192.168.1.1'].join('\n'),
    },
    {
      id: 'R1',
      model: 'isr4321',
      x: 7.2,
      y: 3.5,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description LAN',
        ' ip address 192.168.1.1 255.255.255.0',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description Link to branch R2',
        ' ip address 10.0.0.1 255.255.255.252',
        ' no shutdown',
        'snmp-server community public RO',
        'snmp-server community private RW',
      ].join('\n'),
    },
    {
      id: 'R2',
      model: 'isr4321',
      x: 10.6,
      y: 3.5,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Link to HQ R1',
        ' ip address 10.0.0.2 255.255.255.252',
        ' no shutdown',
        'ip route 0.0.0.0 0.0.0.0 10.0.0.1',
      ].join('\n'),
    },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'SW1:g0/1' },
    { a: 'SW1:fa0/1', b: 'SRV1:fa0' },
    { a: 'R1:g0/0/1', b: 'R2:g0/0/0' },
  ],
  tasks: [
    {
      id: 'timestamps',
      title: 'Stamp log messages on R1 and SW1 with date and time to the millisecond: `service timestamps log datetime msec`',
      details: 'By default messages carry only the device uptime, which is useless when you correlate events from several devices. `datetime msec` adds the calendar date and time with millisecond precision (accurate only when the clock is right, which is what NTP is for). Debug output has its own `service timestamps debug` line; set both.',
      hint: '`service timestamps log datetime msec` and `service timestamps debug datetime msec`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^service timestamps log datetime msec$' },
        { type: 'config', device: 'SW1', pattern: '^service timestamps log datetime msec$' },
      ],
    },
    {
      id: 'syslog-server',
      title: 'Send messages of severity **warnings** (level 4) and worse from R1 and SW1 to the syslog server **192.168.1.50**',
      details: '`logging host ADDRESS` names the collector and `logging trap LEVEL` sets the severity sent to it. A level includes everything more severe, so `warnings` (4) covers warnings, errors, critical, alerts and emergencies, but not notifications (5) or informational (6). `show logging` shows the trap level and the destination.',
      hint: '`logging host ...` and `logging trap warnings`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^logging (host )?192\\.168\\.1\\.50$' },
        { type: 'config', device: 'R1', pattern: '^logging trap warnings$' },
        { type: 'config', device: 'SW1', pattern: '^logging (host )?192\\.168\\.1\\.50$' },
        { type: 'config', device: 'SW1', pattern: '^logging trap warnings$' },
        { type: 'show', device: 'R1', command: 'show logging', pattern: 'Trap logging: level warnings' },
        { type: 'show', device: 'R1', command: 'show logging', pattern: 'Logging to 192\\.168\\.1\\.50' },
        { type: 'show', device: 'SW1', command: 'show logging', pattern: 'Logging to 192\\.168\\.1\\.50' },
      ],
    },
    {
      id: 'local-logging',
      title: 'On R1 keep a 16384-byte log buffer at level **informational**, limit console logging to **errors**, then bounce G0/0/1 to generate events',
      details: '`logging buffered 16384 informational` stores messages in RAM so that `show logging` can replay them even when the collector was unreachable, and `logging console errors` keeps notifications off the console. Configure both, then shut down G0/0/1 and bring it back up. `show logging` must now hold `%LINK-3-UPDOWN` (severity 3) and `%LINEPROTO-5-UPDOWN` (severity 5) for the port. Only the first one is also forwarded to the syslog server, because the trap level is warnings.',
      hint: '`logging buffered ...`, `logging console ...`, then `interface g0/0/1` → `shutdown` → `no shutdown`',
      checks: [
        { type: 'show', device: 'R1', command: 'show logging', pattern: 'Buffer logging:\\s+level informational' },
        { type: 'show', device: 'R1', command: 'show logging', pattern: 'Console logging:\\s+level errors' },
        { type: 'show', device: 'R1', command: 'show logging', pattern: '%LINK-3-UPDOWN: Interface GigabitEthernet0/0/1, changed state to up' },
        { type: 'show', device: 'R1', command: 'show logging', pattern: '%LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/0/1, changed state to up' },
      ],
    },
    {
      id: 'snmp-communities',
      title: 'On R1 remove the default communities, then create **WizardRO** (read-only) and **WizardRW** (read-write, restricted by ACL 99 to the NMS 192.168.1.50); on SW1 create only the read-only **WizardRO**',
      details: 'SNMPv2c authenticates with a plain-text community string, and the factory defaults are the first thing every scanner tries. A read-only string lets the NMS poll counters; a read-write string lets it change the configuration, so tie it to the management station with a standard ACL: `snmp-server community NAME RO|RW [ACL]`. Delete the old strings with `no snmp-server community NAME`. The switch only needs to be polled, so it gets no read-write string.',
      hint: '`access-list 99 permit host ...`, `snmp-server community WizardRW RW 99`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^snmp-server community public\\b', expect: false },
        { type: 'config', device: 'R1', pattern: '^snmp-server community private\\b', expect: false },
        { type: 'config', device: 'R1', pattern: '^snmp-server community WizardRO RO$' },
        { type: 'config', device: 'R1', pattern: '^snmp-server community WizardRW RW 99$' },
        { type: 'config', device: 'R1', pattern: '^access-list 99 permit (host )?192\\.168\\.1\\.50$' },
        { type: 'config', device: 'SW1', pattern: '^snmp-server community WizardRO RO$' },
        { type: 'config', device: 'SW1', pattern: '^snmp-server community \\S+ RW', expect: false },
      ],
    },
    {
      id: 'snmp-traps',
      title: 'Make R1 and SW1 send SNMPv2c traps to **192.168.1.50** with community **WizardTRAP**, and set the location and contact on R1',
      details: '`snmp-server host ADDRESS version 2c COMMUNITY` defines the trap receiver (the string travels inside every trap) and `snmp-server enable traps` switches trap generation on: nothing is sent until trap types are enabled. `snmp-server location` and `snmp-server contact` tell the NMS where the device is and whom to call.',
      hint: '`snmp-server host 192.168.1.50 version 2c ...`, `snmp-server enable traps`, `snmp-server location ...`',
      checks: [
        { type: 'config', device: 'R1', pattern: '^snmp-server host 192\\.168\\.1\\.50 (traps )?version 2c WizardTRAP$' },
        { type: 'config', device: 'R1', pattern: '^snmp-server enable traps' },
        { type: 'config', device: 'R1', pattern: '^snmp-server location \\S+' },
        { type: 'config', device: 'R1', pattern: '^snmp-server contact \\S+' },
        { type: 'config', device: 'SW1', pattern: '^snmp-server host 192\\.168\\.1\\.50 (traps )?version 2c WizardTRAP$' },
        { type: 'config', device: 'SW1', pattern: '^snmp-server enable traps' },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'configure terminal',
      'service timestamps log datetime msec',
      'service timestamps debug datetime msec',
      'logging host 192.168.1.50',
      'logging trap warnings',
      'logging buffered 16384 informational',
      'logging console errors',
      'access-list 99 permit host 192.168.1.50',
      'no snmp-server community public',
      'no snmp-server community private',
      'snmp-server community WizardRO RO',
      'snmp-server community WizardRW RW 99',
      'snmp-server host 192.168.1.50 version 2c WizardTRAP',
      'snmp-server enable traps',
      'snmp-server location HQ-ServerRoom-Rack4',
      'snmp-server contact noc@wizard.example',
      'interface GigabitEthernet0/0/1',
      ' shutdown',
      ' no shutdown',
      ' end',
    ].join('\n'),
    SW1: [
      'enable',
      'configure terminal',
      'service timestamps log datetime msec',
      'service timestamps debug datetime msec',
      'logging host 192.168.1.50',
      'logging trap warnings',
      'snmp-server community WizardRO RO',
      'snmp-server host 192.168.1.50 version 2c WizardTRAP',
      'snmp-server enable traps',
      'end',
    ].join('\n'),
  },
};

export default lab;
