import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-troubleshoot-acl-nat',
  title: 'Troubleshooting NAT and ACLs',
  summary:
    'The office cannot browse the Internet and customers cannot reach the public web server. Peel back four stacked faults on the edge router: swapped NAT roles, a NAT ACL for the wrong subnet, an ACL applied in the wrong direction and an implicit deny that hides a needed permit.',
  difficulty: 3,
  minutes: 50,
  lessons: ['extended-acls', 'nat', 'troubleshooting-methodology'],
  scenario:
    '**Fabrikam Outfitters** connects three zones to its edge router **R1**: the staff LAN **192.168.10.0/24** (G0/0, PC1 and PC2 behind SW1), a DMZ **172.16.1.0/24** (G0/1) holding the public web server WEB1 (172.16.1.10) and the ISP link (G0/2, 203.0.113.2/30 towards 203.0.113.1). The ISP routes the customer block **203.0.113.8/29** to R1. WEB1 is published on **203.0.113.10** with static NAT, and every staff PC shares R1\'s WAN address through **PAT**.\n\n' +
    'Two tickets arrived this morning: *"Nobody in the office can browse the Internet"* and *"Customers say our website is down"*. The previous administrator also left an extended ACL named **WAN-IN** that is meant to protect the network: only web traffic for the public server and the answers to sessions that users started (TCP replies, ping replies, DNS answers) may enter from the Internet. SSH, Telnet and anything else must stay blocked.\n\n' +
    'R1 is the only device you need to change. Use `show ip nat statistics`, `show ip nat translations`, `show access-lists` (watch the match counters), `show ip interface` and test from PC1, PC2 and the Internet host INET. The problems are stacked: fixing one usually uncovers the next.',
  devices: [
    { id: 'SW1', model: 'c2960', x: 3, y: 3.5 },
    {
      id: 'R1',
      model: 'isr2911',
      x: 6,
      y: 3.5,
      config: [
        'ip access-list standard NAT-INSIDE',
        ' permit 192.168.100.0 0.0.0.255',
        'ip access-list extended WAN-IN',
        ' remark Inbound policy: public web server plus replies only',
        ' permit tcp any host 203.0.113.10 eq 80',
        ' permit tcp any host 203.0.113.10 eq 443',
        ' permit tcp any any established',
        ' permit icmp any any echo-reply',
        'interface GigabitEthernet0/0',
        ' description Staff LAN',
        ' ip address 192.168.10.1 255.255.255.0',
        ' ip nat outside',
        ' no shutdown',
        'interface GigabitEthernet0/1',
        ' description DMZ web server',
        ' ip address 172.16.1.1 255.255.255.0',
        ' ip nat inside',
        ' no shutdown',
        'interface GigabitEthernet0/2',
        ' description WAN to ISP',
        ' ip address 203.0.113.2 255.255.255.252',
        ' ip nat inside',
        ' ip access-group WAN-IN out',
        ' no shutdown',
        'ip route 0.0.0.0 0.0.0.0 203.0.113.1',
        'ip nat inside source list NAT-INSIDE interface GigabitEthernet0/2 overload',
        'ip nat inside source static 172.16.1.10 203.0.113.10',
      ].join('\n'),
    },
    {
      id: 'ISP',
      model: 'isr4321',
      x: 9,
      y: 3.5,
      locked: true,
      config: [
        'interface GigabitEthernet0/0/0',
        ' description Customer Fabrikam',
        ' ip address 203.0.113.1 255.255.255.252',
        ' no shutdown',
        'interface GigabitEthernet0/0/1',
        ' description Internet',
        ' ip address 198.51.100.1 255.255.255.0',
        ' no shutdown',
        'ip route 203.0.113.8 255.255.255.248 203.0.113.2',
      ].join('\n'),
    },
    { id: 'PC1', model: 'pc', x: 0.8, y: 1.2, host: { ip: '192.168.10.11', mask: '255.255.255.0', gateway: '192.168.10.1', dns: '198.51.100.10' } },
    { id: 'PC2', model: 'pc', x: 0.8, y: 5.8, host: { ip: '192.168.10.12', mask: '255.255.255.0', gateway: '192.168.10.1', dns: '198.51.100.10' } },
    { id: 'WEB1', model: 'server', x: 6, y: 6.2, host: { ip: '172.16.1.10', mask: '255.255.255.0', gateway: '172.16.1.1' }, services: { http: true, https: true } },
    {
      id: 'INET',
      model: 'server',
      x: 11.5,
      y: 3.5,
      label: 'INET',
      host: { ip: '198.51.100.10', mask: '255.255.255.0', gateway: '198.51.100.1' },
      services: { http: true, https: true, dns: [{ name: 'www.example.com', ip: '198.51.100.10' }] },
    },
  ],
  links: [
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'SW1:g0/1', b: 'R1:g0/0' },
    { a: 'R1:g0/1', b: 'WEB1:fa0' },
    { a: 'R1:g0/2', b: 'ISP:g0/0/0' },
    { a: 'ISP:g0/0/1', b: 'INET:fa0' },
  ],
  tasks: [
    {
      id: 'nat-roles',
      title: 'Restore the static NAT for WEB1: INET must reach **203.0.113.10** on TCP 80, with G0/0 and G0/1 **inside** and G0/2 **outside**',
      details: 'From INET, web requests to 203.0.113.10 loop between R1 and the ISP instead of reaching the DMZ. NAT only translates between an *inside* and an *outside* interface, in the right direction. `show ip nat statistics` lists which interfaces R1 treats as inside and outside.',
      hint: '`show ip nat statistics`, then `ip nat inside` / `ip nat outside` under the interfaces.',
      checks: [
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 80 },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0', pattern: '^ ip nat inside$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/1', pattern: '^ ip nat inside$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/2', pattern: '^ ip nat outside$' },
      ],
    },
    {
      id: 'acl-direction',
      title: 'Apply **WAN-IN** in the right direction: inbound on G0/2, so SSH from the Internet is blocked while the web server stays published',
      details: 'An ACL is evaluated against traffic *entering* (`in`) or *leaving* (`out`) an interface, and an interface holds one ACL per direction. `show ip interface GigabitEthernet0/2` shows which ACL is attached where. Applied the wrong way round, WAN-IN judges the staff\'s own outgoing requests (`denied by ACL WAN-IN outbound` in a ping result) and leaves the Internet-facing side unfiltered, so INET can reach any port of WEB1.',
      hint: '`show ip interface g0/2`, then `no ip access-group …` and apply the ACL again with the other direction keyword.',
      checks: [
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/2', pattern: '^ ip access-group WAN-IN in$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/2', pattern: '^ ip access-group WAN-IN out$', expect: false },
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 22, expect: false },
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 443 },
      ],
    },
    {
      id: 'nat-acl',
      title: 'Make PAT translate the staff LAN: ACL **NAT-INSIDE** must permit **192.168.10.0/24**, so PC1 can ping INET (**198.51.100.10**)',
      details: 'With the roles and the ACL direction right, PC1\'s ping still dies: the ISP has no route to a private 192.168.10.x address, so R1 let the packet out untranslated. PAT only translates packets that match the access list named in the `ip nat inside source list` command. Read it with `show ip access-lists NAT-INSIDE` and compare it with the staff LAN. Named ACL lines can be removed and re-added by sequence number.',
      hint: '`ip access-list standard NAT-INSIDE` → `no <sequence>` → `<sequence> permit <network> <wildcard>`',
      checks: [
        { type: 'show', device: 'R1', command: 'show ip access-lists NAT-INSIDE', pattern: 'permit 192\\.168\\.10\\.0, wildcard bits 0\\.0\\.0\\.255' },
        { type: 'show', device: 'R1', command: 'show ip access-lists NAT-INSIDE', pattern: '192\\.168\\.100\\.0', expect: false },
        { type: 'ping', from: 'PC1', to: '198.51.100.10' },
      ],
    },
    {
      id: 'dns-permit',
      title: 'Let the staff resolve names again: PC1 must resolve **www.example.com** to 198.51.100.10',
      details: 'Pings and web requests by IP address now work, but name lookups time out. DNS answers come back from UDP port 53, and WAN-IN ends with an implicit `deny ip any any` that quietly drops them. `show access-lists` shows which lines match; a permit that should exist but does not is invisible there. Add the missing permit for the DNS replies.',
      hint: '`nslookup www.example.com` on PC1, then ask yourself which direction DNS answers travel, which port they come from and which ACL line would let them in.',
      checks: [
        { type: 'resolve', from: 'PC1', name: 'www.example.com', ip: '198.51.100.10' },
        { type: 'resolve', from: 'PC2', name: 'www.example.com', ip: '198.51.100.10' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify the policy end to end: staff browse out, customers reach the web server, nothing else gets in',
      details: 'Staff PCs must resolve www.example.com and open TCP 80 and 443 to INET. From INET, TCP 80 and 443 to 203.0.113.10 must work while SSH (22) and Telnet (23) must not, and INET must not be able to reach the staff LAN at all.',
      hint: 'Run `nslookup` and `ping` on the PCs, then compare `show ip nat translations` and the match counters in `show access-lists`.',
      checks: [
        { type: 'resolve', from: 'PC1', name: 'www.example.com', ip: '198.51.100.10' },
        { type: 'traffic', from: 'PC1', to: '198.51.100.10', proto: 'tcp', port: 80 },
        { type: 'traffic', from: 'PC1', to: '198.51.100.10', proto: 'tcp', port: 443 },
        { type: 'traffic', from: 'PC2', to: '198.51.100.10', proto: 'tcp', port: 80 },
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 80 },
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 443 },
        { type: 'traffic', from: 'INET', to: '203.0.113.10', proto: 'tcp', port: 23, expect: false },
        { type: 'ping', from: 'INET', to: '192.168.10.11', expect: false },
        { type: 'show', device: 'R1', command: 'show ip nat statistics', pattern: 'Outside interfaces:\\s*\\n\\s*GigabitEthernet0/2' },
      ],
    },
    {
      id: 'save',
      title: 'Save the corrected configuration on **R1**',
      details: 'The ACL and NAT fixes are lost at the next reload unless they are written to the startup-config.',
      hint: '`copy running-config startup-config` or `write memory`.',
      checks: [
        { type: 'saved', device: 'R1' },
        { type: 'show', device: 'R1', command: 'show startup-config', pattern: 'ip access-group WAN-IN in' },
      ],
    },
  ],
  solution: {
    R1: [
      'enable',
      'configure terminal',
      'interface GigabitEthernet0/0',
      ' ip nat inside',
      'interface GigabitEthernet0/2',
      ' ip nat outside',
      ' no ip access-group WAN-IN out',
      ' ip access-group WAN-IN in',
      ' exit',
      'ip access-list standard NAT-INSIDE',
      ' no 10',
      ' 10 permit 192.168.10.0 0.0.0.255',
      ' exit',
      'ip access-list extended WAN-IN',
      ' permit udp any eq 53 any',
      ' exit',
      'do write memory',
      'end',
    ].join('\n'),
  },
};

export default lab;
