import type { Lab } from '../labTypes';

const lab: Lab = {
  id: 'lab-router-on-a-stick',
  title: 'Router-on-a-Stick Inter-VLAN Routing',
  summary: 'Build VLANs, access ports and an 802.1Q trunk on SW1, then route between VLANs 10, 20 and 30 with dot1Q subinterfaces on R1.',
  difficulty: 2,
  minutes: 40,
  lessons: ['inter-vlan-routing', 'vlans', 'trunking'],
  scenario:
    'The Harbor Street branch has one router (**R1**) and one access switch (**SW1**) for three groups: **Sales** (VLAN 10, 192.168.10.0/24), **Engineering** (VLAN 20, 192.168.20.0/24) and **Guest** (VLAN 30, 192.168.30.0/24). The PCs are already addressed and use the .1 address of their subnet as default gateway, but SW1 still has its factory configuration: every PC sits in VLAN 1 and nothing can leave its own broadcast domain.\n\n' +
    'There is only one cable between the two devices (R1 G0/0/0 to SW1 G0/1), so the routing has to be done as a **router on a stick**: SW1 trunks all VLANs to R1, and R1 terminates each VLAN on its own 802.1Q subinterface. VLAN 99 (**NATIVE**) is an unused VLAN reserved as the trunk\'s native VLAN, so untagged frames never land in a user VLAN.\n\n' +
    'When you are done, each subinterface is the default gateway (.1) of its VLAN and every PC can reach every other PC.',
  devices: [
    { id: 'R1', model: 'isr4321', x: 6, y: 1, config: ['interface GigabitEthernet0/0/0', ' description Trunk to SW1 G0/1'].join('\n') },
    { id: 'SW1', model: 'c2960', x: 6, y: 3.5, config: ['interface GigabitEthernet0/1', ' description Trunk to R1 G0/0/0'].join('\n') },
    { id: 'PC1', model: 'pc', x: 3, y: 6, host: { ip: '192.168.10.11', mask: '255.255.255.0', gateway: '192.168.10.1' } },
    { id: 'PC2', model: 'pc', x: 6, y: 6, host: { ip: '192.168.20.12', mask: '255.255.255.0', gateway: '192.168.20.1' } },
    { id: 'PC3', model: 'pc', x: 9, y: 6, host: { ip: '192.168.30.13', mask: '255.255.255.0', gateway: '192.168.30.1' } },
  ],
  links: [
    { a: 'R1:g0/0/0', b: 'SW1:g0/1' },
    { a: 'SW1:fa0/1', b: 'PC1:fa0' },
    { a: 'SW1:fa0/2', b: 'PC2:fa0' },
    { a: 'SW1:fa0/3', b: 'PC3:fa0' },
  ],
  tasks: [
    {
      id: 'vlans',
      title: 'Create VLAN 10 **SALES**, VLAN 20 **ENGINEERING**, VLAN 30 **GUEST** and VLAN 99 **NATIVE** on SW1',
      details: 'In global configuration mode use `vlan <id>` followed by `name <NAME>`. The VLAN is committed when you leave VLAN configuration mode. Verify with `show vlan brief`.',
      hint: '`vlan 10` then `name SALES`; repeat for the other three VLANs and check `show vlan brief`.',
      checks: [
        { type: 'vlan', device: 'SW1', vlan: 10, name: 'SALES' },
        { type: 'vlan', device: 'SW1', vlan: 20, name: 'ENGINEERING' },
        { type: 'vlan', device: 'SW1', vlan: 30, name: 'GUEST' },
        { type: 'vlan', device: 'SW1', vlan: 99, name: 'NATIVE' },
      ],
    },
    {
      id: 'access-ports',
      title: 'Make SW1 Fa0/1, Fa0/2 and Fa0/3 static access ports in VLANs 10, 20 and 30 respectively',
      details: 'PC1 is on Fa0/1, PC2 on Fa0/2 and PC3 on Fa0/3. Hard-code `switchport mode access` so the ports never negotiate a trunk, then assign the VLAN with `switchport access vlan`.',
      hint: '`interface fa0/1` → `switchport mode access` → `switchport access vlan 10`',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Fa0/1', mode: 'access', accessVlan: 10 },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/2', mode: 'access', accessVlan: 20 },
        { type: 'switchport', device: 'SW1', iface: 'Fa0/3', mode: 'access', accessVlan: 30 },
      ],
    },
    {
      id: 'trunk',
      title: 'Turn SW1 G0/1 into a static 802.1Q trunk toward R1 with native VLAN 99 that allows only VLANs 10, 20, 30 and 99',
      details: 'Use `switchport mode trunk`, `switchport trunk native vlan 99` and `switchport trunk allowed vlan 10,20,30,99`. The 2960 only supports 802.1Q, so there is no `switchport trunk encapsulation` command. Check the result with `show interfaces trunk`.',
      hint: 'In `show interfaces trunk` the native VLAN column must read 99 and the allowed list must match exactly.',
      checks: [
        { type: 'switchport', device: 'SW1', iface: 'Gi0/1', mode: 'trunk', nativeVlan: 99, allowed: '10,20,30,99' },
        { type: 'show', device: 'SW1', command: 'show interfaces trunk', pattern: '^Gi0/1\\s+on\\s+802\\.1q\\s+trunking\\s+99$' },
      ],
    },
    {
      id: 'subinterfaces',
      title: 'On R1 bring up G0/0/0 and create subinterfaces G0/0/0.10, .20 and .30 (dot1Q 10, 20, 30) with the gateways 192.168.10.1, 192.168.20.1 and 192.168.30.1, all /24',
      details: 'The physical interface carries no IP address, but it must be `no shutdown` or every subinterface stays down. On each subinterface enter `encapsulation dot1Q <vlan-id>` **before** `ip address`. Verify with `show ip interface brief`.',
      hint: '`interface g0/0/0.10` → `encapsulation dot1Q 10` → `ip address 192.168.10.1 255.255.255.0`',
      checks: [
        { type: 'interface', device: 'R1', iface: 'Gi0/0/0', status: 'up' },
        { type: 'interface', device: 'R1', iface: 'Gi0/0/0.10', ip: '192.168.10.1', mask: '255.255.255.0', status: 'up' },
        { type: 'interface', device: 'R1', iface: 'Gi0/0/0.20', ip: '192.168.20.1', mask: '255.255.255.0', status: 'up' },
        { type: 'interface', device: 'R1', iface: 'Gi0/0/0.30', ip: '192.168.30.1', mask: '255.255.255.0', status: 'up' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0/0.10', pattern: '^ encapsulation dot1Q 10$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0/0.20', pattern: '^ encapsulation dot1Q 20$' },
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0/0.30', pattern: '^ encapsulation dot1Q 30$' },
      ],
    },
    {
      id: 'native-subinterface',
      title: 'Add subinterface R1 G0/0/0.99 with `encapsulation dot1Q 99 native` and no IP address',
      details: 'SW1 sends and expects VLAN 99 untagged on the trunk. The `native` keyword tells R1 that this subinterface uses untagged frames, so both ends agree on the native VLAN (a mismatch makes CDP log `%CDP-4-NATIVE_VLAN_MISMATCH`).',
      hint: '`interface g0/0/0.99` → `encapsulation dot1Q 99 native`',
      checks: [
        { type: 'config', device: 'R1', section: 'interface GigabitEthernet0/0/0.99', pattern: '^ encapsulation dot1Q 99 native$' },
        { type: 'interface', device: 'R1', iface: 'Gi0/0/0.99', status: 'up' },
      ],
    },
    {
      id: 'verify',
      title: 'Verify that R1 routes between the VLANs: three connected subnets in the routing table and every PC can ping the other two',
      details: 'On R1 `show ip route` lists each VLAN subnet as a connected (`C`) network with its subinterface as exit interface. From PC1 ping PC2 and PC3, from PC2 ping PC3. If a ping fails, check the VLAN of the access port, the trunk and the subinterface encapsulation, in that order.',
      hint: 'Traffic between VLANs leaves SW1 tagged, is routed by R1 and returns tagged: watch for a missing VLAN on the trunk or a wrong dot1Q ID.',
      checks: [
        { type: 'route', device: 'R1', prefix: '192.168.10.0/24', source: 'C', exitIf: 'Gi0/0/0.10' },
        { type: 'route', device: 'R1', prefix: '192.168.20.0/24', source: 'C', exitIf: 'Gi0/0/0.20' },
        { type: 'route', device: 'R1', prefix: '192.168.30.0/24', source: 'C', exitIf: 'Gi0/0/0.30' },
        { type: 'ping', from: 'PC1', to: '192.168.20.12' },
        { type: 'ping', from: 'PC1', to: '192.168.30.13' },
        { type: 'ping', from: 'PC2', to: '192.168.30.13' },
        { type: 'ping', from: 'PC3', to: '192.168.10.11' },
      ],
    },
  ],
  solution: {
    SW1: [
      'enable',
      'configure terminal',
      'vlan 10',
      ' name SALES',
      'vlan 20',
      ' name ENGINEERING',
      'vlan 30',
      ' name GUEST',
      'vlan 99',
      ' name NATIVE',
      ' exit',
      'interface fa0/1',
      ' switchport mode access',
      ' switchport access vlan 10',
      'interface fa0/2',
      ' switchport mode access',
      ' switchport access vlan 20',
      'interface fa0/3',
      ' switchport mode access',
      ' switchport access vlan 30',
      'interface g0/1',
      ' switchport mode trunk',
      ' switchport trunk native vlan 99',
      ' switchport trunk allowed vlan 10,20,30,99',
      ' end',
    ].join('\n'),
    R1: [
      'enable',
      'configure terminal',
      'interface g0/0/0',
      ' no shutdown',
      'interface g0/0/0.10',
      ' description SALES gateway',
      ' encapsulation dot1Q 10',
      ' ip address 192.168.10.1 255.255.255.0',
      'interface g0/0/0.20',
      ' description ENGINEERING gateway',
      ' encapsulation dot1Q 20',
      ' ip address 192.168.20.1 255.255.255.0',
      'interface g0/0/0.30',
      ' description GUEST gateway',
      ' encapsulation dot1Q 30',
      ' ip address 192.168.30.1 255.255.255.0',
      'interface g0/0/0.99',
      ' description Native VLAN',
      ' encapsulation dot1Q 99 native',
      ' end',
    ].join('\n'),
  },
};

export default lab;
